import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {Analytics} from '../src/Analytics';import {crmRequests} from '../src/api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const container=document.querySelector('#fixture'),out=document.querySelector('#results'),results=[];
const assert=(v,m)=>{if(!v)throw Error(m)},flush=()=>act(()=>new Promise(r=>setTimeout(r,15)));
async function click(label){await act(async()=>{const b=[...container.querySelectorAll('button')].find(x=>x.textContent===label);assert(b,'button '+label);b.click()});await flush()}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',message:String(e)})}out.textContent=JSON.stringify(results,null,2)}
function make(){const metric=(id,name,value)=>({id,name,value,unit:'CNY',status:'complete',reason:'',basis:'虚构口径，仅组件测试',start:'2026-09-01',end:'2026-09-13',as_of:'2026-09-12',drillable:true,groups:[]});return {snapshot:'a'.repeat(64),calculated_at:'2026-09-12T00:00:00Z',filters:{start:'2026-09-01',end:'2026-09-13',as_of:'2026-09-12'},scope_note:'HTTP substitute',customers:[],regions:[],metrics:[metric('contracts','本期签约金额','123.45'),metric('receivables','应收未核销','67.89')]}}
async function setup(){const old=fetch,opened=[];let next=null,deny=false,detailDelay=null,changed=false,fail=false;const report=make();
 globalThis.fetch=async(url)=>{if(deny)return new Response(JSON.stringify({code:'FORBIDDEN'}),{status:403});const isDetail=String(url).includes('/details?');const data=isDetail?{snapshot:report.snapshot,filters:report.filters,metric:report.metrics[0],page:1,page_size:25,total:1,items:[{id:'c',label:'虚构原合同',value:'123.45',date:'2026-09-01',note:'',target:{kind:'contract',id:'c'}}]}:structuredClone(report);const wait=isDetail?detailDelay:next;if(isDetail)detailDelay=null;else next=null;if(wait)await wait;if(fail){fail=false;throw TypeError('fictional network failure')};if(isDetail&&changed)return new Response(JSON.stringify({code:'REPORT_CHANGED'}),{status:409});return new Response(JSON.stringify(data),{status:200})};
 crmRequests.bind({tenant_id:'A',context_id:'A1'});const root=createRoot(container);await act(async()=>root.render(<React.StrictMode><Analytics context={crmRequests.capture()} onContextError={()=>{}} onOpen={t=>opened.push(t)}/></React.StrictMode>));for(let i=0;i<4;i++)await flush();
 return{root,report,opened,deny(){deny=true},delay(p){next=p},delayDetail(p){detailDelay=p},change(){changed=true},fail(){fail=true},async close(){await act(async()=>root.unmount());fetch=old;crmRequests.bind(null)}};
}
await test('actual drill and original-source click preserve source identity',async()=>{const h=await setup();try{await click('123.45 CNY');assert(container.querySelector('dialog[open]'),'detail opened');await click('打开原业务');assert(h.opened[0].kind==='contract'&&h.opened[0].id==='c','original identity');assert(!container.querySelector('dialog'),'closed')}finally{await h.close()}});
await test('focus permission recheck clears amount and open detail immediately',async()=>{const h=await setup();try{await click('123.45 CNY');h.deny();await act(async()=>window.dispatchEvent(new Event('focus')));await flush();assert(!container.textContent.includes('123.45')&&!container.textContent.includes('67.89'),'no old financial values');assert(!container.querySelector('dialog'),'detail cleared');assert(container.textContent.includes('未授权'),'denied visible')}finally{await h.close()}});
await test('delayed successful report cannot enter a new enterprise',async()=>{const h=await setup();let release;try{h.delay(new Promise(r=>release=r));await click('刷新分析');assert(!container.textContent.includes('123.45'),'old cleared at start');crmRequests.bind({tenant_id:'B',context_id:'B1'});await act(async()=>release());await flush();assert(!container.textContent.includes('123.45'),'late success discarded')}finally{release?.();await h.close()}});
await test('delayed successful detail after refresh never repopulates dialog',async()=>{const h=await setup();let release;try{h.delayDetail(new Promise(r=>release=r));await click('123.45 CNY');await click('刷新分析');await act(async()=>release());await flush();assert(!container.querySelector('dialog'),'late old details discarded');assert(![...container.querySelectorAll('button')].find(b=>b.textContent==='123.45 CNY').disabled,'fresh report remains drillable')}finally{release?.();await h.close()}});
await test('source snapshot mismatch removes whole report then explicit refresh restores',async()=>{const h=await setup();try{h.change();await click('123.45 CNY');assert(!container.textContent.includes('123.45'),'old aggregate removed');assert(container.textContent.includes('来源数据已变化'),'explained');await click('刷新分析');assert(container.textContent.includes('123.45'),'fresh data restored')}finally{await h.close()}});
await test('failed reload never falls back to old successful data',async()=>{const h=await setup();try{h.fail();await click('刷新分析');assert(container.querySelector('[role=alert]'),'error shown');assert(!container.textContent.includes('123.45'),'old amount gone');await click('刷新分析');assert(container.textContent.includes('123.45'),'retry recovers')}finally{await h.close()}});
await test('date input event changes the next real component request',async()=>{const h=await setup();const original=fetch,urls=[];try{globalThis.fetch=async(url,...args)=>{urls.push(String(url));return original(url,...args)};await act(async()=>{const input=container.querySelector('input[type=date]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'2026-01-01');input.dispatchEvent(new Event('input',{bubbles:true}))});await flush();assert(urls.some(u=>u.includes('start=2026-01-01')),'new date reached request')}finally{await h.close()}});
