import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {Assembly} from '../src/Assembly';import {crmRequests} from '../src/api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;const container=document.querySelector('#fixture'),out=document.querySelector('#results');const results=[];
const assert=(v,m)=>{if(!v)throw Error(m)};const flush=()=>act(()=>new Promise(r=>setTimeout(r,20)));
async function click(label){await act(async()=>{const b=[...container.querySelectorAll('button')].find(x=>x.textContent===label);assert(b,'button '+label);b.click()});await flush()}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',message:String(e)})}out.textContent=JSON.stringify(results,null,2)}
const work={id:'work',order_id:'order',product_sku_id:'sku',manager_id:'user',planned_on:'2026-09-11',notes:'',version:1,state:'draft',checks:[],requirements:[],included:[],reservations:[],issues:[],devices:[],history:[],wip_cost:'0.00'};
async function setup(){const old=fetch;let lose=false,pending=null,keys=[],saved=new Map();globalThis.fetch=async(url,init={})=>{const path=String(url).replace('/api/v1','');let data=[];
 if(path==='/inventory/context')data={permissions:['assembly.read','assembly.write','device.read']};
 if(path==='/assembly/works'&&init.method==='POST'){const key=new Headers(init.headers).get('Idempotency-Key');keys.push(key);if(!saved.has(key))saved.set(key,{...work,id:'work-'+saved.size});data=saved.get(key);if(lose){lose=false;throw Error('response lost after commit')}}
 else if(path==='/assembly/works'){if(pending){const p=pending;pending=null;await p;data=[{...work,id:'OLD_A_WORK'}]}else data=[...saved.values()]}
 return new Response(JSON.stringify(data),{status:200})};crmRequests.bind({tenant_id:'A',context_id:'A1'});const root=createRoot(container);await act(async()=>root.render(<React.StrictMode><Assembly context={crmRequests.capture()} members={[]} onContextError={()=>{}}/></React.StrictMode>));for(let i=0;i<5;i++)await flush();return {root,keys,saved,lose(){lose=true},delay(p){pending=p},async close(){await act(async()=>root.unmount());globalThis.fetch=old;crmRequests.bind(null)}}}
await test('create response lost: same intent replay then explicit new intent',async()=>{const h=await setup();try{h.lose();await click('创建工单');assert(container.querySelector('[role=alert]'),'visible failure');assert(!container.textContent.includes('操作已保存'),'no false success');await click('创建工单');assert(h.keys[0]===h.keys[1]&&h.saved.size===1,'single creation');await click('新建单台工单');await click('创建工单');assert(h.saved.size===2&&h.keys[2]!==h.keys[1],'explicit new identity')}finally{await h.close()}});
await test('delayed successful A list does not update B',async()=>{const h=await setup();let release;try{h.delay(new Promise(r=>release=r));await click('刷新查询');crmRequests.bind({tenant_id:'B',context_id:'B1'});await act(async()=>h.root.render(<Assembly key="B" context={crmRequests.capture()} members={[]} onContextError={()=>{}}/>));release();for(let i=0;i<8;i++)await flush();assert(!container.textContent.includes('OLD_A_WO'),'old result rejected')}finally{release?.();await h.close()}});
