import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {Delivery} from '../src/Delivery';import {crmRequests} from '../src/api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;const container=document.querySelector('#fixture'),out=document.querySelector('#results'),results=[];
const assert=(v,m)=>{if(!v)throw Error(m)},flush=()=>act(()=>new Promise(r=>setTimeout(r,20)));
async function click(name){await act(async()=>{const b=[...container.querySelectorAll('button')].find(b=>b.textContent===name);assert(b,'button '+name);b.click()});await flush()}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',message:String(e)})}out.textContent=JSON.stringify(results,null,2)}
async function setup(){const old=fetch;let lose=false,pending=null;const saved=new Map(),keys=[];globalThis.fetch=async(url,init={})=>{const path=String(url).replace('/api/v1','');let data=[];
 if(path==='/inventory/context')data={permissions:['delivery.read','delivery.ship']};
 if(path==='/delivery/shipments'&&init.method==='POST'){const key=new Headers(init.headers).get('Idempotency-Key');keys.push(key);if(!saved.has(key))saved.set(key,{id:'ship'+saved.size,state:'draft',version:1,recipient:'fictional',address:'fictional',contact:'fictional',lines:[],reversals:[],progress:{remaining:1}});data=saved.get(key);if(lose){lose=false;throw Error('committed response lost')}}
 else if(path==='/delivery/shipments')data=[...saved.values()];
 else if(path==='/delivery/orders'&&pending){const p=pending;pending=null;await p;data=[{order_id:'OLD_A',number:'OLD_A_ORDER',quantity:1}]}
 return new Response(JSON.stringify(data),{status:200})};crmRequests.bind({tenant_id:'A',context_id:'A1'});const root=createRoot(container);await act(async()=>root.render(<React.StrictMode><Delivery context={crmRequests.capture()} onContextError={()=>{}}/></React.StrictMode>));for(let i=0;i<5;i++)await flush();return{root,keys,saved,lose(){lose=true},delay(p){pending=p},async close(){await act(async()=>root.unmount());globalThis.fetch=old;crmRequests.bind(null)}}}
await test('lost successful create replays; explicit new draft creates a distinct intent',async()=>{const h=await setup();try{h.lose();await click('保存发货草稿');assert(container.querySelector('[role=alert]'),'real error visible');await click('保存发货草稿');assert(h.saved.size===1&&h.keys[0]===h.keys[1],'same intent retry');await click('新建发货草稿');await click('保存发货草稿');assert(h.saved.size===2&&h.keys[2]!==h.keys[0],'new intent')}finally{await h.close()}});
await test('delayed successful A aggregate cannot enter B after enterprise change',async()=>{const h=await setup();let release;try{h.delay(new Promise(r=>release=r));await click('刷新查询');crmRequests.bind({tenant_id:'B',context_id:'B1'});await act(async()=>h.root.render(<Delivery key="B" context={crmRequests.capture()} onContextError={()=>{}}/>));release();for(let i=0;i<8;i++)await flush();assert(!container.textContent.includes('OLD_A_ORDER'),'stale success rejected')}finally{release?.();await h.close()}});
