import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {Assembly} from '../src/Assembly';import {crmRequests} from '../src/api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const container=document.querySelector('#fixture'),out=document.querySelector('#results'),results=[];
const assert=(v,m)=>{if(!v)throw Error(m)},flush=()=>act(()=>new Promise(r=>setTimeout(r,20)));
async function click(label){await act(async()=>{const b=[...container.querySelectorAll('button')].find(x=>x.textContent===label);assert(b,'button '+label);b.click()});await flush()}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',message:String(e)})}out.textContent=JSON.stringify(results,null,2)}
const device={id:'d',serial:'SN-FICTIONAL',product:{number:'HOST',name:'虚构主机',manufacturer:'虚构制造商',brand:'硅屿',brand_kind:'own'},inventory_unit_id:'unit',customer_name:'虚构客户',order_number:'SO-FICTIONAL',contract_number:'CT-FICTIONAL',quote_version_id:'q',project_id:'p',inventory:[{state:'pending',quantity:1}],installations:[],completions:[],delivery_state:'not_started'};
const work={id:'WORK-ONLY',state:'draft',version:1,requirements:[],checks:[],included:[],reservations:[],issues:[],devices:[],history:[],completions:[],planned_on:'2026-09-11'};
async function setup(){const old=fetch;let allowed=false,advertised=false,delay=null;
globalThis.fetch=async(url)=>{const u=new URL(String(url),location.origin),p=u.pathname.replace('/api/v1','');let data=[];
if(p==='/inventory/context')data={permissions:['inventory.read','device.read','assembly.read','assembly.write',...(advertised?['delivery.read']:[])]};
if(p==='/assembly/works')data=[work];
if(p==='/assembly/devices')data=u.searchParams.get('q')==='absent'?[]:[device];
if(p==='/assembly/devices/d')data=device;
if(p.startsWith('/delivery/devices')){if(!allowed)return new Response(JSON.stringify({code:'PERMISSION_DENIED'}),{status:403});data={...device,eligibility:'pass',tests:[{id:'t',result:'pass',performed_at:'HISTORY-SECRET',completion_id:'c'}],deliveries:[]};if(delay){const wait=delay;delay=null;await wait;}if(p==='/delivery/devices')data=[data];}
return new Response(JSON.stringify(data),{status:200});};
crmRequests.bind({tenant_id:'A',context_id:'A1'});const root=createRoot(container);await act(async()=>root.render(<Assembly context={crmRequests.capture()} members={[]} onContextError={()=>{}}/>));for(let n=0;n<5;n++)await flush();
return {root,grant(){allowed=advertised=true},revoke(){allowed=false},delay(p){delay=p},async close(){await act(async()=>root.unmount());globalThis.fetch=old;crmRequests.bind(null)}};}
await test('device and assembly work remain usable without delivery.read',async()=>{const h=await setup();try{assert(container.textContent.includes('SN-FICTIONAL'),'base device list visible');await click('打开工单 WORK-ONL');assert(container.textContent.includes('确认需求'),'permitted work operations loaded');await click('查询设备');await click('设备详情 SN-FICTIONAL');assert(container.textContent.includes('虚构制造商'),'base detail visible');assert(!container.textContent.includes('HISTORY-SECRET'),'no delivery history');assert(!container.querySelector('[role=alert]'),'no unrelated authorization failure')}finally{await h.close()}});
await test('authorized history, revoked 403 clears history but preserves base detail',async()=>{const h=await setup();try{h.grant();await click('刷新查询');await click('设备详情 SN-FICTIONAL');assert(container.textContent.includes('HISTORY-SECRET'),'authorized history visible');h.revoke();await click('设备详情 SN-FICTIONAL');assert(container.textContent.includes('虚构制造商'),'base survives 403');assert(!container.textContent.includes('HISTORY-SECRET'),'revoked history erased');assert(container.textContent.includes('交付查询权限不足或已撤销'),'explicit optional denial');assert(!container.querySelector('[role=alert]'),'base not failed')}finally{await h.close()}});
await test('late successful history cannot cross enterprise or closed detail',async()=>{const h=await setup();let release;try{h.grant();await click('刷新查询');h.delay(new Promise(r=>release=r));await click('设备详情 SN-FICTIONAL');assert(container.textContent.includes('虚构制造商'),'base shown before history arrives');await click('关闭设备详情');release();for(let n=0;n<5;n++)await flush();assert(!container.textContent.includes('HISTORY-SECRET'),'closed history stays closed');h.delay(new Promise(r=>release=r));await click('设备详情 SN-FICTIONAL');crmRequests.bind({tenant_id:'B',context_id:'B1'});await act(async()=>h.root.render(<Assembly key="B" context={crmRequests.capture()} members={[]} onContextError={()=>{}}/>));release();for(let n=0;n<8;n++)await flush();assert(!container.textContent.includes('HISTORY-SECRET'),'late A history rejected')}finally{release?.();await h.close()}});
