import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {Finance,FinanceSummary,difference} from '../src/Finance';import {crmRequests} from '../src/api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const container=document.querySelector('#fixture'),out=document.querySelector('#results'),results=[];
const assert=(v,m)=>{if(!v)throw Error(m)},flush=()=>act(()=>new Promise(r=>setTimeout(r,20)));
async function click(label){await act(async()=>{const b=[...container.querySelectorAll('button')].find(x=>x.textContent===label);assert(b,'button '+label);b.click()});await flush()}
async function input(label,value){await act(async()=>{const l=[...container.querySelectorAll('label')].find(x=>x.firstChild.textContent===label);assert(l,'label '+label);const e=l.querySelector('input,select');const proto=e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}))});await flush()}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',message:String(e)})}out.textContent=JSON.stringify(results,null,2)}
const source={id:'s',direction:'receivable',party_id:'p',party_name:'虚构客户',number:'CT-TEST',amount:'100',base_amount:'100',version:1,order_ids:[],nodes:[],tax_basis:'manual'};
const summary={receivable:'0.00',payable:'0.00',overdue_receivable:'0.00',overdue_payable:'0.00',received:'0.00',paid:'0.00',customer_refunds:'0.00',supplier_refunds:'0.00',net_cash_flow:'0.00',advance_received:'0.00',advance_paid:'0.00',unallocated_received:'0.00',unallocated_paid:'0.00',as_of:'fictional-test'};
async function setup(){const old=fetch;const records=[],replays=new Map(),posts=[];let lose=false,delay=null;
 globalThis.fetch=async(url,init={})=>{const path=new URL(String(url),location.origin).pathname.replace('/api/v1/finance','');let data=[];
 if(init.method==='POST'){
  const body=JSON.parse(init.body),key=new Headers(init.headers).get('Idempotency-Key');posts.push({path,key,body});const sig=path+key;
  if(replays.has(sig))data=replays.get(sig);else{if(path==='/cash'){data={...body,id:'c'+records.length,state:'draft',version:1,party_name:'虚构客户',allocated:'0.00',refunded:'0.00',available:'0.00',reversed:false,allocations:[],actor_id:'test-actor'};records.push(data);}else{data={...records.find(x=>path.includes(x.id)),state:'confirmed',version:2};records[records.findIndex(x=>x.id===data.id)]=data;}replays.set(sig,data);}
  if(lose){lose=false;throw new TypeError('simulated successful commit / lost response');}
 }else if(path==='/context')data={permissions:['finance.read','finance.cash','finance.plan','finance.confirm']};
 else if(path==='/sources')data=[source];else if(path==='/parties')data=[{id:'p',name:'虚构客户',direction:'receivable'}];else if(path==='/cash')data=records;else if(path==='/summary')data=summary;
 if(delay&&init.method==='POST'){const d=delay;delay=null;await d;}
 return new Response(JSON.stringify(data),{status:200});};
 crmRequests.bind({tenant_id:'A',context_id:'A1'});const root=createRoot(container);await act(async()=>root.render(<React.StrictMode><Finance context={crmRequests.capture()} onContextError={()=>{}}/></React.StrictMode>));for(let i=0;i<4;i++)await flush();
 return {root,records,posts,lose(){lose=true},delay(p){delay=p},async close(){await act(async()=>root.unmount());globalThis.fetch=old;crmRequests.bind(null)}};
}
async function form(){await click('实收实付与核销');await input('往来单位','p');await input('资金金额 CNY','100.00');await input('内部账户标识（未连接银行）','test');await input('资金备注（必填）','虚构现金事实');}
await test('actual new intent, lost creation response and retry create only one fact',async()=>{const h=await setup();try{await form();h.lose();await click('保存资金草稿');assert(h.records.length===1,'committed once');assert(container.querySelector('[role=alert]'),'lost response shown');await click('保存资金草稿');assert(h.records.length===1,'retry does not duplicate');assert(h.posts[0].key===h.posts[1].key,'same creation identity');await click('新建资金草稿');await click('保存资金草稿');assert(h.records.length===2,'explicit identical second creation');assert(h.posts[2].key!==h.posts[0].key,'new identity');h.lose();await click('确认已实际收付');const lost=h.posts.at(-1);assert(container.querySelector('[role=alert]'),'confirmation response loss visible');await click('确认已实际收付');assert(h.posts.at(-1).key===lost.key,'confirmation retry retains intent');assert(h.records[1].state==='confirmed'&&h.records[0].state==='draft','second fact action isolated')}finally{await h.close()}});
await test('late successful creation cannot replace new enterprise state',async()=>{const h=await setup();let release;try{await form();h.delay(new Promise(r=>release=r));await click('保存资金草稿');crmRequests.bind({tenant_id:'B',context_id:'B1'});await act(async()=>h.root.render(<p>企业 B 基础页面</p>));release();for(let i=0;i<6;i++)await flush();assert(container.textContent==='企业 B 基础页面','old successful result discarded')}finally{release?.();await h.close()}});
await test('finance summary revocation clears protected values and preserves base page',async()=>{const old=fetch;let allowed=true;const root=createRoot(container);try{globalThis.fetch=async()=>new Response(JSON.stringify(allowed?{source,plans:[],invoiced:'987.65'}:{code:'FORBIDDEN'}),{status:allowed?200:403});crmRequests.bind({tenant_id:'A',context_id:'A1'});await act(async()=>root.render(<><p>合同基础内容</p><FinanceSummary context={crmRequests.capture()} direction="receivable" sourceId="s"/></>));for(let i=0;i<4;i++)await flush();assert(container.textContent.includes('987.65'),'authorized summary');allowed=false;await act(async()=>window.dispatchEvent(new Event('focus')));for(let i=0;i<4;i++)await flush();assert(!container.textContent.includes('987.65'),'revoked amount erased');assert(container.textContent.includes('合同基础内容')&&container.textContent.includes('未授权查询资金摘要'),'base remains with explicit denial')}finally{await act(async()=>root.unmount());globalThis.fetch=old;crmRequests.bind(null)}});
await test('integer-cent display subtraction stays exact',async()=>{assert(difference('1000000000000.30','0.20')==='1000000000000.10','exact large amount');assert(difference('0.10','0.30')==='-0.20','negative exact');assert(difference('1','bad')==='待输入有效金额','invalid not zero')});
