import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {Service,ServiceSummary} from '../src/Service';import {crmRequests} from '../src/api';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const container=document.querySelector('#fixture'),out=document.querySelector('#results'),results=[];
const assert=(v,m)=>{if(!v)throw Error(m)},flush=()=>act(()=>new Promise(r=>setTimeout(r,20)));
async function click(label){await act(async()=>{const b=[...container.querySelectorAll('button')].find(x=>x.textContent===label);assert(b,'button '+label);b.click()});await flush()}
async function input(label,value){await act(async()=>{const l=[...container.querySelectorAll('label')].find(x=>x.firstChild.textContent===label);assert(l,'label '+label);const e=l.querySelector('input,select');const proto=e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}))});await flush()}
async function test(name,fn){try{await fn();results.push({name,status:'passed'})}catch(e){results.push({name,status:'failed',message:String(e)})}out.textContent=JSON.stringify(results,null,2)}

async function setup(){const old=fetch,records=[],posts=[],replays=new Map();let lose=false,delay=null,allowed=true;
 globalThis.fetch=async(url,init={})=>{const path=new URL(String(url),location.origin).pathname.replace('/api/v1/service','');let data=[];
 if(!allowed)return new Response(JSON.stringify({code:'FORBIDDEN'}),{status:403});
 if(init.method==='POST'){const body=JSON.parse(init.body),key=new Headers(init.headers).get('Idempotency-Key');posts.push({key,body,path});
 if(replays.has(key))data=replays.get(key);else{data={...body,id:'w'+records.length,version:1,state:'new',config_version:1,serial:'TEST-SN',customer_name:'虚构客户',order_number:'SO-TEST',custody:'customer',test_valid:false,warranty:'pending',receipts:[],returns:[],tests:[],history:[],reservations:[],issues:[],changes:[],old_parts:[],rmas:[],installations:[],original_configuration:[]};records.push(data);replays.set(key,data);}
 if(lose){lose=false;throw TypeError('committed / response lost')}
 if(delay){const wait=delay;delay=null;await wait;}}
 else if(path==='/context')data={permissions:['service.read','service.manage'],people:[{id:'u',name:'虚构负责人'}]};else if(path==='/devices')data=[{id:'d',serial:'TEST-SN',customer_name:'虚构客户',order_number:'SO-TEST'}];else if(path==='/works')data=records;else if(path==='/options')data={locations:[],suppliers:[],stock:[]};
 return new Response(JSON.stringify(data),{status:200});};
 crmRequests.bind({tenant_id:'A',context_id:'A1'});const root=createRoot(container);await act(async()=>root.render(<React.StrictMode><Service context={crmRequests.capture()} onContextError={()=>{}}/></React.StrictMode>));for(let i=0;i<5;i++)await flush();
 return{root,records,posts,lose(){lose=true},delay(p){delay=p},revoke(){allowed=false},async close(){await act(async()=>root.unmount());fetch=old;crmRequests.bind(null)}};
}
async function form(){await input('设备 / SN','d');await input('工单编号','TEST-1');await input('故障描述','虚构故障');await input('报修联系人','虚构');await input('售后负责人','u');await input('计划日期','2026-10-01');}
await test('StrictMode initializes and lost create response retries identical operation',async()=>{const h=await setup();try{await form();h.lose();await click('登记售后工单');assert(h.records.length===1,'first commit');assert(container.querySelector('[role=alert]'),'failure visible');await click('登记售后工单');assert(h.records.length===1,'same create retry');assert(h.posts[0].key===h.posts[1].key,'same command key');await click('新建售后工单');await click('登记售后工单');assert(h.records.length===2,'new explicit intent');}finally{await h.close()}});
await test('delayed successful service response cannot populate another tenant',async()=>{const h=await setup();let release;try{await form();h.delay(new Promise(r=>release=r));await click('登记售后工单');crmRequests.bind({tenant_id:'B',context_id:'B1'});await act(async()=>h.root.render(<p>企业 B</p>));release();for(let i=0;i<5;i++)await flush();assert(container.textContent==='企业 B','late response discarded')}finally{release?.();await h.close()}});
await test('focus revocation removes previously visible service facts',async()=>{const h=await setup();try{await form();await click('登记售后工单');assert(container.textContent.includes('TEST-SN'),'visible');h.revoke();await act(async()=>window.dispatchEvent(new Event('focus')));for(let i=0;i<5;i++)await flush();assert(!container.textContent.includes('TEST-SN'),'revoked facts cleared');assert(container.querySelector('[role=alert]'),'permission error visible')}finally{await h.close()}});

await test('optional service summary denial preserves underlying device',async()=>{const old=fetch,root=createRoot(container);let allowed=true;try{fetch=async()=>new Response(JSON.stringify(allowed?[{id:'x',number:'PRIVATE-SERVICE',state:'working'}]:{code:'FORBIDDEN'}),{status:allowed?200:403});crmRequests.bind({tenant_id:'A',context_id:'S'});await act(async()=>root.render(<><p>基础设备 SN</p><ServiceSummary context={crmRequests.capture()} deviceId="d" onOpen={()=>{}}/></>));for(let i=0;i<5;i++)await flush();assert(container.textContent.includes('PRIVATE-SERVICE'),'initial visible');allowed=false;await act(async()=>window.dispatchEvent(new Event('focus')));for(let i=0;i<5;i++)await flush();assert(container.textContent.includes('基础设备 SN')&&!container.textContent.includes('PRIVATE-SERVICE'),'base retained and protected fact cleared')}finally{await act(async()=>root.unmount());fetch=old;crmRequests.bind(null)}});
