import {useEffect,useRef,useState} from 'react';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket} from './api';
import type {components} from '../../../packages/api-client/schema';
import './analytics.css';
type S=components['schemas'];type Report=S['AnalyticsReport'];type Metric=S['Metric'];type Details=S['AnalyticsDetails'];type Target=S['AnalyticsTarget'];
const groups=[['经营规模',['contracts','contract_count','dispatched','returned','net_delivery','receipts','payments','customer_refunds','supplier_refunds','net_cash']],['资金与库存',['receivables','payables','overdue_receivables','due_payables','inventory_known_cost','inventory_unknown']],['待处理事项',['overdue_orders','inventory_age','held_devices','rma_outside','rma_overdue','rma_held']]] as const;
const statuses:Record<string,string>={complete:'完整',partial:'部分数据',unavailable:'暂不可计算',unauthorized:'未授权',not_applicable:'不适用'};
const utcDay=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
export function Analytics({context,onContextError,onOpen}:{context:ContextTicket;onContextError:(e:unknown)=>void;onOpen:(t:Target)=>void}){
 const [start,setStart]=useState(utcDay().slice(0,7)+'-01'),[end,setEnd]=useState(new Date(new Date(utcDay()).getTime()+86400000).toISOString().slice(0,10)),[asof,setAsof]=useState(utcDay());
 const [region,setRegion]=useState(''),[customer,setCustomer]=useState(''),[threshold,setThreshold]=useState('180');
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mapMetric,setMapMetric]=useState('contracts');
 const [detail,setDetail]=useState<Details|null>(null),[detailBusy,setDetailBusy]=useState(false),[explain,setExplain]=useState<Metric|null>(null);
 const [sort,setSort]=useState('date');const generation=useRef(0),detailGeneration=useRef(0),alive=useRef(true),dialog=useRef<HTMLDialogElement>(null);
 const query=new URLSearchParams({start,end,as_of:asof,old_stock_days:threshold,...(region?{region}:{}),...(customer?{customer_id:customer}:{})}).toString();
 const current=(n:number)=>alive.current&&n===generation.current&&crmRequests.isCurrent(context);
 const clear=()=>{setDetailBusy(false);setReport(null);setDetail(null);setExplain(null);detailGeneration.current++;};
 async function load(){const n=++generation.current;clear();setBusy(true);setError('');try{const r=await crmRequests.request<Report>(context,'/analytics/overview?'+query);if(current(n))setReport(r);}catch(e){if(current(n)){clear();setError(e instanceof ApiError&&e.status===403?'未授权访问经营分析。':errorMessage(e));if(isContextError(e)||(e instanceof ApiError&&e.status===401))onContextError(e);}}finally{if(current(n))setBusy(false);}}
 useEffect(()=>{alive.current=true;void load();const focus=()=>void load();const visible=()=>{if(document.visibilityState==='visible')void load();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',visible);return()=>{alive.current=false;generation.current++;detailGeneration.current++;window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',visible);};},[context.context_id,query]);
 useEffect(()=>{if(!detail&&!explain)return;const el=dialog.current;if(!el)return;const origin=document.activeElement as HTMLElement;el.showModal();return()=>{el.close();if(origin?.isConnected)origin.focus();};},[!!detail,!!explain]);
 async function drill(m:Metric,page=1,nextSort=sort){if(!report||!m.drillable)return;const n=generation.current,d=++detailGeneration.current;setDetailBusy(true);setExplain(null);setError('');try{const r=await crmRequests.request<Details>(context,'/analytics/details?'+query+'&'+new URLSearchParams({metric:m.id,snapshot:report.snapshot,page:String(page),sort:nextSort}));if(current(n)&&d===detailGeneration.current)setDetail(r);}catch(e){if(current(n)&&d===detailGeneration.current){setDetail(null);if(e instanceof ApiError&&(e.code==='REPORT_CHANGED'||e.status===403)){clear();setError(e.code==='REPORT_CHANGED'?'来源数据已变化，旧汇总和明细已清除，请刷新分析。':'权限已变化，旧分析已清除，请刷新分析。');}else if(!(e instanceof StaleResponse)){setError(errorMessage(e));if(isContextError(e)||(e instanceof ApiError&&e.status===401))onContextError(e);}}}finally{if(current(n)&&d===detailGeneration.current)setDetailBusy(false);}}
 const metric=(id:string)=>report?.metrics.find(m=>m.id===id);
 const close=()=>{detailGeneration.current++;setDetail(null);setExplain(null);setDetailBusy(false);};
 const card=(m:Metric)=><article className={'metric analytics-metric '+m.status+(m.id==='contracts'&&m.value!==null?' analytics-featured':'')} key={m.id}><small>{m.name}</small><button className="metric-value" disabled={!m.drillable||detailBusy} onClick={()=>void drill(m)}>{m.value??statuses[m.status]} <small>{m.value!==null?m.unit:''}</small></button><div><span>{statuses[m.status]}</span><button aria-label={m.name+'口径'} onClick={()=>{setDetail(null);setExplain(m);}}>口径 ↗</button></div></article>;
 const map=metric(mapMetric);
 return <section className="analytics" aria-label="经营驾驶舱"><div className="panel analytics-filters"><div className="toolbar"><div><span className="eyebrow">SILICON / OPERATIONS</span><h2>经营驾驶舱</h2></div><button onClick={()=>void load()} disabled={busy}>刷新分析</button></div><div className="analytics-filter-grid"><label>期间开始<input type="date" value={start} onInput={e=>setStart(e.currentTarget.value)} onChange={e=>setStart(e.target.value)}/></label><label>期间结束（不含）<input type="date" value={end} onInput={e=>setEnd(e.currentTarget.value)} onChange={e=>setEnd(e.target.value)}/></label><label>截止日（含）<input type="date" value={asof} onInput={e=>setAsof(e.currentTarget.value)} onChange={e=>setAsof(e.target.value)}/></label><label>地区<select value={region} onChange={e=>{setRegion(e.target.value);setCustomer('');}}><option value="">全部地区</option>{report?.regions.map(r=><option value={r.code} key={r.code}>{r.name}</option>)}{region&&!report&&<option value={region}>{region}</option>}</select></label><label>客户<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">全部可见客户</option>{report?.customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}{customer&&!report&&<option value={customer}>{customer}</option>}</select></label><label>长库龄阈值（天）<input type="number" min="1" max="3650" value={threshold} onInput={e=>setThreshold(e.currentTarget.value)} onChange={e=>setThreshold(e.target.value)}/></label></div><small>上海自然日 · 已知事实重建 · 待交付默认90天、到期应付未来7天、集中度前5名。客户/地区筛选不适用于应付和自有库存。</small></div>
 {busy&&<p role="status">正在读取经营事实，旧图表已清除…</p>}{error&&<p role="alert" className="error">{error}</p>}{detailBusy&&<p role="status">正在读取同口径明细…</p>}
 {report&&<><p className="analytics-stamp">{report.scope_note} · 统计时间 {new Date(report.calculated_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>{groups.map(([title,ids])=><section key={title} aria-label={title}><h2>{title}</h2><div className="analytics-cards">{ids.map(id=>metric(id)).filter((m):m is Metric=>!!m).map(card)}</div></section>)}
 <section className="panel analytics-map" aria-label="客户与销售地区分布"><div className="toolbar"><div><span className="eyebrow">REGIONAL DISTRIBUTION</span><h2>客户与销售地区</h2></div><label>地图指标<select value={mapMetric} onChange={e=>setMapMetric(e.target.value)}><option value="customer_distribution">客户数</option><option value="contracts">签约金额</option><option value="net_delivery">净交付数量</option></select></label></div><p>按当前客户明确地区。省级方格示意，不代表行政边界或客户坐标；海外及地区待完善单列。</p>{map?.value===null?<p>{statuses[map.status]} · {map.reason}</p>:<><div className="region-grid" role="group" aria-label="省级方格示意图">{report.regions.filter(r=>r.code!=='unknown'&&r.code!=='overseas').map(r=>{const value=map?.groups?.find(x=>x.key===r.code)?.value??'0';return <button key={r.code} style={{gridColumn:r.column+1,gridRow:r.row+1}} className={value!=='0'&&value!=='0.00'?'has-value':''} title={r.name+' '+value+' '+map?.unit} onClick={()=>{setRegion(r.code);setCustomer('');}} aria-label={r.name+' '+value+' '+map?.unit}>{r.short}<strong>{value}</strong></button>;})}</div><p className="map-legend">浅色：无贡献 · 深绿：有贡献（数值为准，包含负向更正）</p><div className="table-wrap"><table><caption>真实地区贡献表（地图不可用时仍可阅读）</caption><thead><tr><th>地区</th><th>{map?.name}</th><th>操作</th></tr></thead><tbody>{map?.groups?.map(g=><tr key={g.key}><td>{g.label}</td><td>{g.value} {map.unit}</td><td><button onClick={()=>{setRegion(g.key);setCustomer('');}}>筛选此地区</button></td></tr>)}{!map?.groups?.length&&<tr><td colSpan={3}>当前条件暂无贡献事实。</td></tr>}</tbody></table></div><button disabled={!map?.drillable||detailBusy} onClick={()=>map&&void drill(map)}>查看地区贡献明细</button></>}</section>
 <section className="panel" aria-label="客户与冻结销售结构"><h2>客户与冻结销售结构</h2><div className="analytics-cards">{['business_customers','new_customers','concentration'].map(id=>metric(id)).filter((m):m is Metric=>!!m).map(card)}</div>{['customer_rank','customer_receivable_rank','product_rank','brand_rank','manager_rank'].map(id=>metric(id)).filter((m):m is Metric=>!!m).map(m=><div className="analytics-breakdown" key={m.id}><h3>{m.name}</h3><p>{m.value??statuses[m.status]} {m.value!==null?m.unit:''}</p><button disabled={!m.drillable||detailBusy} onClick={()=>void drill(m)}>查看{m.name}明细</button><button onClick={()=>setExplain(m)}>口径</button>{m.groups?.map(g=><p key={g.key}>{g.label}<strong>{g.value} {m.unit}</strong></p>)}</div>)}</section>
 <section className="panel" aria-label="资金账龄与库存库龄"><h2>资金账龄与库存库龄</h2>{['receivable_age','payable_age','inventory_age_bands','inventory_structure','customer_custody'].map(id=>metric(id)).filter((m):m is Metric=>!!m).map(m=><div className="analytics-breakdown" key={m.id}><h3>{m.name}</h3>{m.value===null?<p>{statuses[m.status]} · {m.reason}</p>:<>{m.groups?.map(g=><p key={g.key}>{g.label}<strong>{g.value} {m.unit}</strong></p>)}{!m.groups?.length&&<p>暂无余额。</p>}<button disabled={!m.drillable||detailBusy} onClick={()=>void drill(m)}>查看{m.name}明细</button></>}<button onClick={()=>setExplain(m)}>口径</button></div>)}<div className="analytics-cards">{['advance_receipts','advance_payments','unallocated_receipts','unallocated_payments','completion_to_ship','unshipped_completions','DIO','DSO','DPO','CCC'].map(id=>metric(id)).filter((m):m is Metric=>!!m).map(card)}</div></section></>}
 {(detail||explain)&&<dialog ref={dialog} className="analytics-dialog" onCancel={close} aria-label={detail?'贡献明细':'指标说明'}><div className="modal-head"><h2>{(detail?.metric??explain)?.name}</h2><button aria-label="关闭分析弹窗" onClick={close}>✕</button></div><div className="modal-body"><p>{(detail?.metric??explain)?.basis}</p><p>{(detail?.metric??explain)?.reason}</p><p>期间 {start} 至 {end}（不含）；截止 {asof}（含）</p>{detail&&<><label>明细排序<select value={sort} onChange={e=>{setSort(e.target.value);void drill(detail.metric,1,e.target.value);}}><option value="date">日期倒序</option><option value="value">贡献值倒序</option><option value="label">名称倒序</option></select></label><div className="table-wrap"><table><thead><tr><th>业务事实</th><th>日期</th><th>贡献</th><th>来源</th></tr></thead><tbody>{detail.items.map(x=><tr key={x.id}><td>{x.label}<small>{x.note}</small></td><td>{x.date||'无到期日期'}</td><td>{x.value}</td><td>{x.target&&<button onClick={()=>{close();onOpen(x.target!);}}>打开原业务</button>}</td></tr>)}</tbody></table></div><div className="toolbar"><button disabled={detail.page<=1||detailBusy} onClick={()=>void drill(detail.metric,detail.page-1)}>上一页</button><span>第 {detail.page} 页 / 共 {detail.total} 条</span><button disabled={detail.page*detail.page_size>=detail.total||detailBusy} onClick={()=>void drill(detail.metric,detail.page+1)}>下一页</button></div></>}</div></dialog>}
 </section>;
}
