import {useEffect,useRef,useState} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket,Member} from './api';
type S=components['schemas'];type Work=S['WorkView'];type Device=S['DeviceView'];type Source=S['SalesSourceView'];type Location=S['LocationView'];type Sku=S['Sku'];type Recon=S['ReconciliationView'];
const labels:Record<string,string>={draft:'草稿',ready:'待领料',in_progress:'装配在制',completed:'已完工 · 待测试',cancelled:'已取消',pending:'待检 / 待测试',wip:'在制',qualified:'合格',quarantine:'隔离'};
const messages:Record<string,string>={ORDER_CAPACITY_EXCEEDED:'累计计划台数超过订单数量。',MAPPING_INCOMPLETE:'冻结配置映射不完整，请补齐明确的 SKU 追踪资料后重试。',INSUFFICIENT_AVAILABLE_STOCK:'可预留物料不足，请核对合格、自有库存与其他工单占用。',UNKNOWN_COST:'该成本来源未知，不能领入装配。',WORK_STATE:'当前工单状态不允许此操作，请刷新核对。',MATERIALS_INCOMPLETE:'所需物料尚未足量领用。',RESERVATION_EXPIRED:'预留已到期，不能领用，请刷新后重新预留。',VERSION_CONFLICT:'工单版本已变化，请刷新核对后重试。',MOVEMENT_DEPENDENCY:'存在后续依赖，不能逆向，请先核对所列记录。',ACTIVE_RESERVATION:'物料仍有有效预留，请先释放。',SERIAL_ALREADY_EXISTS:'整机 SN 已存在，请核对实物身份。',ASSEMBLY_CONSTRAINT:'编号或关联约束冲突，操作未完成。',ALREADY_REVERSED:'原记录已逆向，不能重复更正。'};
Object.assign(messages,{CORRECTION_SOURCE_REQUIRED:'请选择已逆向的原完工记录后更正。',CORRECTION_SOURCE_MISMATCH:'更正来源、工单或设备SN不一致，不能更换实物身份。',CORRECTION_SOURCE_NOT_LATEST:'只能更正最近一次已逆向完工，请刷新核对。',COMPLETION_NOT_REVERSED:'原完工尚未有效逆向。',CORRECTION_DEPENDENCY:'原设备仍有库存、预留或后续依赖，不能重新完工。'});
export function Assembly({context,members,onContextError,deviceOnly=false}:{context:ContextTicket;members:Member[];onContextError:(e:unknown)=>void;deviceOnly?:boolean}){
 const [works,setWorks]=useState<Work[]>([]),[sources,setSources]=useState<Source[]>([]),[skus,setSkus]=useState<Sku[]>([]),[locations,setLocations]=useState<Location[]>([]),[permissions,setPermissions]=useState<string[]>([]);
 const [work,setWork]=useState<Work|null>(null),[devices,setDevices]=useState<Device[]>([]),[device,setDevice]=useState<Device|null>(null),[query,setQuery]=useState('');
 const [order,setOrder]=useState(''),[product,setProduct]=useState(''),[manager,setManager]=useState(''),[planned,setPlanned]=useState(new Date().toISOString().slice(0,10)),[notes,setNotes]=useState('');
 const [delivery,setDelivery]=useState<S['DeliveryDeviceView']|null>(null),[deliveryNotice,setDeliveryNotice]=useState('');
 const [correction,setCorrection]=useState('');
 const [recon,setRecon]=useState<Recon|null>(null);
 const [trace,setTrace]=useState<{movement:S['MovementView'];receipt?:S['ReceiptView'];order?:S['OrderView']}|null>(null);
 async function traceMovement(id:string){const movement=await get<S['MovementView']>('/inventory/movements/'+id);let receipt:S['ReceiptView']|undefined,order:S['OrderView']|undefined;if(movement.receipt_id){receipt=(await get<S['ReceiptView'][]>('/inventory/receipts')).find(x=>x.id===movement.receipt_id);if(receipt){const orderId=receipt.order_id;order=(await get<S['OrderView'][]>('/inventory/orders')).find(x=>x.id===orderId);}}if(crmRequests.isCurrent(context))setTrace({movement,receipt,order});}
 const [quantity,setQuantity]=useState(1),[hours,setHours]=useState(24),[reason,setReason]=useState(''),[serial,setSerial]=useState(''),[location,setLocation]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmation,setConfirmation]=useState<{text:string;run:()=>Promise<void>}|null>(null);
 const keys=useRef(new Map<string,string>()),intent=useRef(crypto.randomUUID()),generation=useRef(0),lock=useRef(false),modal=useRef<HTMLDialogElement>(null);
 const can=(p:string)=>permissions.includes(p);
 const get=<T,>(path:string)=>crmRequests.request<T>(context,path);
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(e instanceof StaleResponse)return;if(isContextError(e)){setWork(null);setDevice(null);setDelivery(null);setDeliveryNotice('');setTrace(null);setWorks([]);setDevices([]);setConfirmation(null);onContextError(e);}else if(crmRequests.isCurrent(context))setError(e instanceof ApiError?(messages[e.code.split(':')[0]]??errorMessage(e))+' ['+e.code+']':errorMessage(e));}finally{lock.current=false;if(crmRequests.isCurrent(context))setBusy(false);}}
 // Base device authorization is independent of optional fulfillment history.
 async function openDevice(id:string){
  const n=++generation.current;setDevice(null);setDelivery(null);setDeliveryNotice('');
  const base=await get<Device>('/assembly/devices/'+id);
  if(n!==generation.current||!crmRequests.isCurrent(context))return;
  setDevice(base);
  if(!can('delivery.read')){setDeliveryNotice('未授权查看交付历史；基础设备资料仍可查询。');return;}
  setDeliveryNotice('正在加载交付历史…');
  try{const history=await get<S['DeliveryDeviceView']>('/delivery/devices/'+id);
   if(n!==generation.current||!crmRequests.isCurrent(context))return;
   setDelivery(history);setDeliveryNotice('');
  }catch(e){
   if(n!==generation.current||!crmRequests.isCurrent(context))return;
   setDelivery(null);
   if(e instanceof ApiError&&e.status===403){setDeliveryNotice('交付查询权限不足或已撤销；基础设备资料仍可查询。');return;}
   setDeliveryNotice('交付历史加载失败，请重新打开设备重试。');throw e;
  }
 }
 async function searchDevices(q=''){
  const n=++generation.current;setDevice(null);setDelivery(null);setDeliveryNotice('');
  const d=await get<Device[]>('/assembly/devices?q='+encodeURIComponent(q));
  if(n===generation.current&&crmRequests.isCurrent(context))setDevices(d);
 }
 async function load(){
  const n=++generation.current;setDevice(null);setDelivery(null);setDeliveryNotice('');
  const meta=await get<{permissions:string[]}>('/inventory/context');let w:Work[]=[],o:Source[]=[],l:Location[]=[],k:Sku[]=[];
  if(!deviceOnly&&meta.permissions.includes('assembly.read'))[w,o,l,k]=await Promise.all([get<Work[]>('/assembly/works'),get<Source[]>('/assembly/orders'),get<Location[]>('/inventory/locations'),get<Sku[]>('/catalog/skus')]);
  const d=meta.permissions.includes('device.read')?await get<Device[]>('/assembly/devices'):[];
  if(n!==generation.current||!crmRequests.isCurrent(context))return;
  setPermissions(meta.permissions);setWorks(w);setSources(o);setLocations(l);setSkus(k);setDevices(d);
 }
 useEffect(()=>{void run(load);},[context.context_id,deviceOnly]);
 useEffect(()=>{if(confirmation){modal.current?.showModal();return()=>modal.current?.close();}},[confirmation]);
 async function command(path:string,body:unknown){const signature=JSON.stringify([intent.current,path,body]);if(!keys.current.has(signature))keys.current.set(signature,crypto.randomUUID());const result=await crmRequests.request<Work>(context,'/assembly'+path,{method:'POST',headers:{'Idempotency-Key':keys.current.get(signature)!},body:JSON.stringify(body)});if(!crmRequests.isCurrent(context))return;setWork(result);setDevice(null);setCorrection('');setRecon(null);await load();if(crmRequests.isCurrent(context))setNotice('操作已保存。完工不代表测试、交付或收款。');}
 function ask(text:string,fn:()=>Promise<void>){setConfirmation({text,run:fn});}
 const input=(label:string,value:string|number,change:(s:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>change(e.target.value)} onInput={e=>change(e.currentTarget.value)}/></label>;
 const choose=(label:string,value:string,change:(s:string)=>void,options:{id:string;name:string}[])=><label>{label}<select value={value} onChange={e=>change(e.target.value)}><option value="">请选择</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 const v=()=>({expected_version:work!.version,confirmed:true,reason:reason||'明确确认'});
 const correctionHistory=work?.completions??[];
 return <section className="panel catalog-panel"><div className="toolbar"><h2>{deviceOnly?'设备与部件档案':'单台装配工单'}</h2><button disabled={busy} onClick={()=>void run(async()=>{await load();if(work){const w=await get<Work>('/assembly/works/'+work.id);if(crmRequests.isCurrent(context))setWork(w);}})}>刷新查询</button></div><p>库存预留 → 实际领料 → 完工待测试。仅实际领料成本，不含人工及其他费用。</p>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!deviceOnly&&<><button disabled={busy||!can('assembly.write')} onClick={()=>{intent.current=crypto.randomUUID();setWork(null);setCorrection('');setError('');setNotice('');}}>新建单台工单</button>
 {!work&&<fieldset disabled={busy||!can('assembly.write')}><h3>计划资料</h3>{choose('销售订单',order,setOrder,sources.map(x=>({id:x.id,name:x.number+' · '+x.quantity+' 台'})))}{choose('成品 SKU',product,setProduct,skus.filter(x=>x.category==='host').map(x=>({id:x.id,name:x.number+' · '+x.name})))}{choose('内部负责人',manager,setManager,members.map(x=>({id:x.id,name:x.name})))}{input('计划日期',planned,setPlanned,'date')}{input('工单备注',notes,setNotes)}<button onClick={()=>void run(()=>command('/works',{order_id:order,product_sku_id:product,manager_id:manager,planned_on:planned,notes}))}>创建工单</button></fieldset>}
 <div className="table-scroll"><table><thead><tr><th>订单 / 工单</th><th>进度</th><th>需求缺口</th><th>操作</th></tr></thead><tbody>{works.map(w=><tr key={w.id}><td>{sources.find(x=>x.id===w.order_id)?.number}<br/>{w.id.slice(0,8)}</td><td>{labels[w.state]}</td><td>{w.requirements.reduce((sum,r)=>sum+r.missing,0)} 件</td><td><button disabled={busy} onClick={()=>{intent.current=crypto.randomUUID();setWork(w);setCorrection('');setDevice(null);setRecon(null);setProduct(w.product_sku_id);setManager(w.manager_id);setPlanned(w.planned_on);setNotes(w.notes);setNotice('');}}>打开工单 {w.id.slice(0,8)}</button></td></tr>)}</tbody></table></div>
 {work&&<div className="nested-card"><h3>工单 {work.id.slice(0,8)} · {labels[work.state]}</h3><p>版本 {work.version} · 成品 SKU {skus.find(x=>x.id===work.product_sku_id)?.number} · {work.planned_on}</p>{work.checks.map(x=><p className="error" key={x}>{x}</p>)}{work.state==='draft'&&<button disabled={busy||!can('assembly.write')} onClick={()=>ask('确认冻结配置映射；included 展示件不另领料。',()=>command('/works/'+work.id+'/ready',v()))}>确认需求</button>}
 {work.state==='draft'&&<details><summary>修改计划资料</summary>{choose('修改成品 SKU',product,setProduct,skus.filter(x=>x.category==='host').map(x=>({id:x.id,name:x.number})))}{choose('修改负责人',manager,setManager,members.map(x=>({id:x.id,name:x.name})))}{input('修改计划日期',planned,setPlanned,'date')}{input('修改备注',notes,setNotes)}<button disabled={busy||!can('assembly.write')} onClick={()=>void run(()=>command('/works/'+work.id+'/save',{expected_version:work.version,product_sku_id:product,manager_id:manager,planned_on:planned,notes}))}>保存计划修改</button></details>}<h4>需求与准备情况</h4>{work.requirements.map(r=><div key={r.id}><p>{r.position} · 需求 {r.quantity} / 有效预留 {r.reserved} / 已领 {r.issued} / 缺口 {r.missing}</p>{['ready','in_progress'].includes(work.state)&&r.missing>0&&<button disabled={busy||!can('assembly.reserve')} onClick={()=>{ask(`为 ${r.position} 预留 ${quantity} 件，${hours} 小时后到期（服务端UTC计时）；按FIFO固定来源，不移动库存。`,()=>command('/works/'+work.id+'/reserve',{...v(),requirement_id:r.id,quantity,duration_hours:hours}));}}>预留 {r.position}</button>}</div>)}<details><summary>含于包件的技术展示（不重复领料）</summary>{work.included.map((x,n)=><p key={n}>{x.sku.number} × {x.quantity} · 含于准系统</p>)}</details>
 {input('本次数量',quantity,x=>setQuantity(Number(x)),'number')}{input('预留时长（小时）',hours,x=>setHours(Number(x)),'number')}{input('业务原因',reason,setReason)}
 <h4>已固定的库存来源</h4>{work.reservations.map(r=><div key={r.id} className="nested-card"><p>预留 {r.id.slice(0,8)} · 来源层 {r.layer_id} · 库位 {r.location_id}</p><p>原预留 {r.quantity} / 已消费 {r.consumed} / 已释放 {r.released} · 到期 {new Date(r.expires_at).toLocaleString()}</p>{r.quantity>r.consumed+r.released&&<button disabled={busy||!can('assembly.issue')||!['ready','in_progress'].includes(work.state)} onClick={()=>ask(`从该固定预留领用 ${quantity} 件到工单在制；未知成本将被拒绝。`,()=>command('/works/'+work.id+'/issue',{...v(),lines:[{reservation_id:r.id,quantity}]}))}>领料 {r.id.slice(0,8)}</button>}</div>)}
 <button disabled={busy||!can('assembly.release')||['completed','cancelled'].includes(work.state)} onClick={()=>ask('释放本工单剩余预留，已消费部分保持不变。',()=>command('/works/'+work.id+'/release',v()))}>释放剩余预留</button><button disabled={busy||!can('assembly.write')||!['draft','ready'].includes(work.state)} onClick={()=>ask('取消未领料工单并释放预留；不会删除历史。',()=>command('/works/'+work.id+'/cancel',v()))}>取消未领料工单</button>
 <h4>在制与完工</h4><button disabled={busy} onClick={()=>void run(async()=>{const r=await get<Recon>('/assembly/works/'+work.id+'/reconciliation');if(crmRequests.isCurrent(context))setRecon(r);})}>工单数量与成本对账</button>{recon&&<p role="status">{recon.matches?'工单台账与成本连续性一致':'存在差异：'+recon.differences.join('；')} · 已领零件 {recon.issued_quantity} / 在制零件 {recon.wip_quantity} / 成品 {recon.completed_quantity}{recon.issued_cost!==undefined&&<> · 已领成本 {recon.issued_cost} = 在制 {recon.wip_cost} + 成品 {recon.finished_cost} CNY</>}</p>}{work.wip_cost!==undefined&&<p>当前在制成本：{work.wip_cost} CNY · 仅实际领料成本</p>}{work.state==='in_progress'&&<fieldset disabled={busy||!can('assembly.complete')}>{input('整机 SN',serial,setSerial)}{choose('成品入库库位',location,setLocation,locations.filter(x=>x.warehouse!=='装配在制').map(x=>({id:x.id,name:x.warehouse+'/'+x.name})))}<button onClick={()=>ask(`完工 ${serial}，结转全部在制并形成一件待测试成品。不会记录已发货或收款。`,()=>command('/works/'+work.id+'/complete',{...v(),serial,location_id:location,correction_of:correction||null}))}>确认完工</button></fieldset>}
 {work.state==='in_progress'&&correctionHistory.length>0&&<p role="status">请选择最近已逆向的原完工记录，再用原SN与实物更正库位。{correction&&<> 已选来源：{correction}；请核对上方SN及库位后确认完工。</>}</p>}
 <h4>完工与逆向历史</h4>{correctionHistory.map(x=><div className="nested-card" key={x.id}><p>完工 {x.id.slice(0,8)} · {x.reversed_by?'已逆向（历史）':'当前有效'} · {new Date(x.completed_at).toLocaleString()}</p><p>成本层 {x.layer_id} · 移动 {x.movement_id}{x.correction_of&&<> · 更正来源 {x.correction_of}</>}</p><button disabled={busy||!can('assembly.reverse')||!reason||!!x.reversed_by} onClick={()=>ask('逆向这次完工并恢复在制；原设备、SN及安装历史保留。后续依赖存在将拒绝。',()=>command('/works/'+work.id+'/reverse',{...v(),movement_id:x.movement_id}))}>逆向完工 {x.id.slice(0,8)}</button>{x.reversed_by&&work.state==='in_progress'&&x.id===correctionHistory.at(-1)?.id&&<button disabled={busy||!can('assembly.complete')} onClick={()=>{setCorrection(x.id);setSerial(devices.find(d=>d.id===x.device_id)?.serial||'');setNotice('已选原设备更正，请选择正确库位并确认完工。');}}>更正原完工 {x.id.slice(0,8)}</button>}</div>)}
 {work.devices.map(d=><p key={d.id}><button disabled={busy||!can('device.read')} onClick={()=>void run(()=>openDevice(d.id))}>查看设备 {d.number}</button></p>)}
 <details><summary>移动与错误更正</summary>{work.issues.map(x=><p key={x.id}>移动 {x.movement_id} <button disabled={busy} onClick={()=>void run(()=>traceMovement(x.movement_id))}>查看移动</button> <button disabled={busy||!can('assembly.reverse')||!reason} onClick={()=>ask('整次错误逆向，恢复原成本位置；后续依赖存在将拒绝。必须填写原因。',()=>command('/works/'+work.id+'/reverse',{...v(),movement_id:x.movement_id}))}>整次逆向</button></p>)}</details><details><summary>操作历史</summary>{work.history.map(x=><p key={x.id}>{x.action} · {x.reason} · {new Date(x.created_at).toLocaleString()}</p>)}</details></div>}</>}
 <h3>设备查询</h3>{input('搜索整机 / 部件 SN、型号、客户、合同或订单',query,setQuery)}<button disabled={busy||!can('device.read')} onClick={()=>void run(()=>searchDevices(query))}>查询设备</button>{devices.map(d=><div className="nested-card" key={d.id}><strong>{d.serial} · {d.product.name}</strong><p>{d.customer_name} · {d.order_number} · {d.reversed?'错误完工已逆向，保留历史':'设备资料 · 测试与交付状态请打开详情查询'}</p><button disabled={busy} onClick={()=>void run(()=>openDevice(d.id))}>设备详情 {d.serial}</button></div>)}
 {device&&<div className="nested-card"><h3>{device.serial} · {device.product.number}</h3><p>{device.product.manufacturer} / {device.product.brand} / {device.product.brand_kind==='own'?'自主品牌':'第三方品牌'}</p><p>实物 {device.inventory_unit_id} · 设备档案引用同一库存实物</p><p>客户 {device.customer_name} · 合同 {device.contract_number} · 订单 {device.order_number}</p><p>报价版本 {device.quote_version_id} · 项目 {device.project_id}</p><p>{device.reversed?'本次完工已逆向，设备历史保留':device.inventory.map(x=>labels[x.state]+' · '+x.quantity+' 件').join('；')}；{!delivery?'交付状态未加载':delivery.delivery_state==='shipped'?'当前已发货':delivery.delivery_state==='returned'?'已退回':'尚未发货'}。收款尚未接入。</p>{device.cost!==undefined&&<p>成品成本 {device.cost} CNY · {device.cost_scope}</p>}<div className="table-scroll"><table><thead><tr><th>部件</th><th>位置</th><th>安装历史</th><th>库存来源</th></tr></thead><tbody>{device.installations.map(x=><tr key={x.id}><td>{x.sku_number}<br/>{x.serial||x.batch} × {x.quantity}</td><td>{x.position}</td><td>{x.installed_at}<br/>{x.removed_at?'拆卸 '+x.removed_at:'有效安装'}</td><td>{x.layer_id}<br/>入库 {x.source_movement}<br/><button disabled={busy} onClick={()=>void run(()=>traceMovement(x.source_movement))}>追溯来源 {x.sku_number}</button></td></tr>)}</tbody></table></div><h4>测试与交付履历</h4>{deliveryNotice&&<p role="status">{deliveryNotice}</p>}{delivery?.tests.map(t=><p key={t.id}>{t.result==='pass'?'测试通过':'测试失败'} · {t.performed_at} · 完工 {t.completion_id}</p>)}{delivery?.deliveries.map(x=><div key={x.id}><p>发货批次 {x.shipment_id} · {x.returns.length?'已退回':x.reversed?'已冲销':'已发货'}</p>{x.acceptances.map(a=><p key={a.id}>{a.accepted?'验收':'验收更正'} · {a.performed_at} · {a.confirmation}</p>)}{x.returns.map(r=><p key={r.id}>实收退货 · {r.performed_at} · {r.reason}</p>)}</div>)}<button onClick={()=>{++generation.current;setDevice(null);setDelivery(null);setDeliveryNotice('');}}>关闭设备详情</button></div>}
 {trace&&<div className="nested-card"><h3>库存来源追溯</h3><p>移动 {trace.movement.id} · {trace.movement.kind} · {trace.movement.effective_on}</p><p>{trace.movement.reason}</p>{trace.receipt?<p>收货 {trace.receipt.id} · {trace.receipt.received_on} · 采购订单 {trace.order?.number||trace.receipt.order_id} · 采购合同 {trace.order?.contract_id||'未找到'}</p>:<p>{trace.movement.kind==='opening'?'期初导入，无采购订单；不虚构采购来源。':'通过工单固定预留关联来源层；该移动不直接关联收货。'}</p>}{trace.movement.entries.map((x,n)=><p key={n}>来源层 {x.layer_id} · 库位 {x.location_id} · {labels[x.state]||x.state} · {x.quantity} 件</p>)}<button onClick={()=>setTrace(null)}>关闭来源追溯</button></div>}
 {device&&<details><summary>全部完工记录（同一设备档案）</summary>{device.completions.map(x=><p key={x.id}>{x.id} · {x.reversed_by?'已逆向历史':'当前有效'} · 成本层 {x.layer_id} · 移动 {x.movement_id}{x.correction_of&&<> · 更正来源 {x.correction_of}</>}</p>)}</details>}
 {confirmation&&<dialog ref={modal} onCancel={()=>setConfirmation(null)}><h3>确认业务操作</h3><p>{confirmation.text}{correction&&<> 更正来源：{correction}；保留原设备和历史。</>}</p><button onClick={()=>{const fn=confirmation.run;setConfirmation(null);void run(fn);}}>确认执行</button><button onClick={()=>setConfirmation(null)}>取消</button></dialog>}
 </section>;
}
