import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {utcInput,fromUtcInput} from './catalogTime';
import {crmRequests,StaleResponse,ApiError,errorMessage,isContextError} from './api';
import type {ContextTicket} from './api';

type S=components['schemas'];
type Sku=S['Sku'];type Bom=S['Bom'];type Price=S['PriceBook'];type Rule=S['Rule'];
type SKUInput=S['SkuInput'];type BOMInput=S['BomInput'];type PriceInput=S['PriceInput'];
export type CatalogPage='skus'|'boms'|'price-books';
const categories:Record<string,string>={host:'主机 / 准系统',cpu:'CPU',gpu:'GPU',memory:'内存',psu:'电源',system_disk:'系统盘',data_disk:'数据盘',nic:'网卡',ib:'IB 卡'};
const specLabels:Record<string,string>={socket:'CPU 插槽',memory_generation:'内存代际',capacity_gb:'容量 GB',power_w:'功率 / 电源额定 W',slot_width:'占用槽宽',interface:'接口',speed_gbps:'速率 Gbps',cpu_sockets:'CPU 插槽数量'};
const textSpecs=new Set(['socket','memory_generation','interface']);
const names={skus:'商品目录',boms:'包件 / BOM','price-books':'价格维护'};
const emptySpecs={socket:'',memory_generation:'',interface:''};
const emptySku:SKUInput={number:'',name:'',category:'host',manufacturer:'',brand:'',brand_kind:'third_party',enabled:true,specs:{...emptySpecs}};
const errors:Record<string,string>={CATALOG_DUPLICATE:'编号已存在，请使用当前企业内唯一编号。',BRAND_KIND_CONFLICT:'同名品牌的自有/第三方属性不一致，请核对品牌。',CYCLIC_PACKAGE:'包件不能包含自身，也不能形成循环引用。',DISABLED_SKU:'存在停用 SKU；草稿可保存，发布前请替换或移除。',PRICE_OVERLAP:'价格有效期与已发布价格重叠，请调整期间或适用范围。',PUBLISHED_IMMUTABLE:'已发布版本不可修改，请创建修订。',INVALID_PACKAGE_VERSION:'请选择该 SKU 对应的已发布准系统包件。',PACKAGE_REQUIRES_HOST:'准系统主体必须是主机类别。',INVALID_CATALOG_RELATION:'部件或版本关系无效，请核对当前企业。'};
function fields<T extends object>(value:T,keys:string[]){return Object.fromEntries(keys.map(k=>[k,(value as Record<string,unknown>)[k]]));}

export function Catalog({page,context,canWrite,disabled,onContextError}:{page:CatalogPage;context:ContextTicket;canWrite:boolean;disabled:boolean;onContextError:(e:unknown)=>void}) {
  const [skus,setSkus]=useState<Sku[]>([]),[boms,setBoms]=useState<Bom[]>([]),[prices,setPrices]=useState<Price[]>([]),[rules,setRules]=useState<Rule[]>([]);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
  const [selected,setSelected]=useState<Sku|Bom|Price|null>(null),[editing,setEditing]=useState(false);
  const [skuForm,setSkuForm]=useState<SKUInput>(emptySku),[bomForm,setBomForm]=useState<BOMInput|null>(null),[priceForm,setPriceForm]=useState<PriceInput|null>(null);
  const [ruleForm,setRuleForm]=useState<S['RuleInput']>({name:'',source:'',socket:'',memory_generation:''}),[ruleParent,setRuleParent]=useState('');
  const [lookupSku,setLookupSku]=useState(''),[lookupScope,setLookupScope]=useState('retail'),[lookupTax,setLookupTax]=useState(true),[current,setCurrent]=useState<S['CurrentPrice']|null>(null);
  const generation=useRef(0),alert=useRef<HTMLDivElement>(null),idempotency=useRef({signature:'',key:crypto.randomUUID()});
  function commandKey(operation:string,payload:unknown){const signature=operation+JSON.stringify(payload);if(idempotency.current.signature!==signature)idempotency.current={signature,key:crypto.randomUUID()};return idempotency.current.key;}
  const locked=busy||disabled;
  function fail(e:unknown){if(e instanceof StaleResponse)return;if(isContextError(e)||e instanceof ApiError&&e.status===401){onContextError(e);return;}setError(e instanceof ApiError?(errors[e.code]??(e.status===422?'输入格式不正确，请核对必填项、部件数量、金额与有效期。':e.message)):errorMessage(e));}
  useEffect(()=>{if(error)alert.current?.focus();},[error]);
  async function refresh(ticket:ContextTicket=context){
    const values=await Promise.all([crmRequests.request<Sku[]>(ticket,'/catalog/skus'),crmRequests.request<Bom[]>(ticket,'/catalog/boms'),crmRequests.request<Price[]>(ticket,'/catalog/price-books'),crmRequests.request<Rule[]>(ticket,'/catalog/rules')]);
    return values;
  }
  function install(values:[Sku[],Bom[],Price[],Rule[]]){setSkus(values[0]);setBoms(values[1]);setPrices(values[2]);setRules(values[3]);}
  useEffect(()=>{const n=++generation.current;setBusy(true);refresh().then(v=>{if(n===generation.current)install(v);}).catch(e=>{if(n===generation.current)fail(e);}).finally(()=>{if(n===generation.current)setBusy(false);});return()=>{generation.current++;};},[context.context_id,page]);
  function begin(item:Sku|Bom|Price|null){idempotency.current={signature:'',key:crypto.randomUUID()};setSelected(item);setEditing(true);setError('');setNotice('');
    if(page==='skus')setSkuForm(item?fields(item,['number','name','category','manufacturer','brand','brand_kind','enabled','specs']) as SKUInput:{...emptySku,specs:{...emptySpecs}});
    if(page==='boms')setBomForm(item?fields(item,['name','kind','subject_sku_id','rule_id','lines']) as BOMInput:{name:'',kind:'package',subject_sku_id:skus.find(s=>s.category==='host')?.id??'',rule_id:null,lines:[]});
    if(page==='price-books')setPriceForm(item?fields(item,['name','scope','currency','tax_included','valid_from','valid_to','source','lines']) as PriceInput:{name:'',scope:'retail',currency:'CNY',tax_included:true,valid_from:'2026-01-01T00:00:00Z',valid_to:'2027-01-01T00:00:00Z',source:'',lines:[]});
  }
  const published=selected&&'state' in selected&&selected.state==='published';
  async function save(event:FormEvent){event.preventDefault();if(locked||!canWrite||published)return;
    const form=page==='skus'?skuForm:page==='boms'?bomForm:priceForm;if(!form)return;
    const payload=selected?{...form,expected_version:selected.version}:form;const n=generation.current;setBusy(true);setError('');setNotice('');
    try{const result=await crmRequests.request<Sku|Bom|Price>(context,'/catalog/'+page+(selected?'/'+selected.id:''),{method:selected?'PUT':'POST',headers:{'Idempotency-Key':commandKey(page+(selected?.id??''),payload)},body:JSON.stringify(payload)});
      const values=await refresh();if(n!==generation.current)return;install(values);setSelected(result);setEditing(false);setNotice('已保存到当前企业，可刷新查询。');
    }catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}
  }
  async function versionAction(action:'publish'|'revise') {if(!selected||locked)return;const n=generation.current;setBusy(true);setError('');setNotice('');
    try{const result=await crmRequests.request<Bom|Price>(context,`/catalog/${page}/${selected.id}/${action}`,{method:'POST',headers:{'Idempotency-Key':commandKey(page+selected.id+action,{expected_version:selected.version})},body:JSON.stringify({expected_version:selected.version})});const values=await refresh();if(n!==generation.current)return;install(values);setSelected(result);setEditing(false);setNotice(action==='publish'?(page==='boms'?'版本已发布并冻结。平台 UNKNOWN/BLOCK 不代表兼容通过。':'价格版本已发布并冻结，可查询有效价格。'):'已创建独立修订草稿，旧版保持不变；请修复停用 SKU 或主体类别问题后再发布。');}catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}
  }
  async function saveRule(event:FormEvent){event.preventDefault();const n=generation.current;setBusy(true);setError('');setNotice('');try{
    const parent=rules.find(r=>r.id===ruleParent);await crmRequests.request(context,'/catalog/rules'+(parent?'/'+parent.id+'/revise':''),{method:'POST',headers:{'Idempotency-Key':commandKey('rule'+ruleParent,ruleForm)},body:JSON.stringify({...ruleForm,...(parent?{expected_version:parent.revision}:{})})});const values=await refresh();if(n===generation.current){install(values);setNotice('规则版本已保存；仅依据填写的来源，不代表供应商认证。');}
  }catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}}
  async function lookup(){const n=generation.current;setBusy(true);setError('');setNotice('');setCurrent(null);try{const result=await crmRequests.request<S['CurrentPrice']>(context,`/catalog/current-price/${lookupSku}?scope=${encodeURIComponent(lookupScope)}&tax_included=${lookupTax}`);if(n===generation.current)setCurrent(result);}catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}}
  const rows=page==='skus'?skus:page==='boms'?boms:prices;
  return <section className="panel catalog"><div className="panel-title"><div><div className="eyebrow">SILICON / CATALOG</div><h2>{names[page]}</h2><p>企业共享目录 · 真实版本与来源 · 报价按当前有效性另行校验</p></div><button className="primary" disabled={locked||!canWrite} onClick={()=>begin(null)}>新建{page==='skus'?'商品':page==='boms'?'包件 / BOM':'价格表'}</button></div>
    {!canWrite&&<p className="muted">只读权限：目录维护与发布仅对企业管理员开放。</p>}
    {error&&<div className="error" role="alert" tabIndex={-1} ref={alert}>{error}</div>}{notice&&<p className="success" role="status">{notice}</p>}
    <div className="toolbar"><input aria-label="筛选目录" placeholder="筛选已载入的名称 / 编号" value={query} onChange={e=>setQuery(e.target.value)}/><span className="muted">每类最多载入 100 项</span></div>
    <div className="table-wrap" role="region" aria-label="目录表格，可横向滚动" tabIndex={0}><table><thead><tr><th>名称 / 编号</th><th>类别 / 版本</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.filter(r=>(r.name+('number' in r?r.number:'')).includes(query)).map(r=><tr key={r.id}><td><strong>{r.name}</strong>{'number'in r&&<small>{r.number}</small>}</td><td>{'category'in r?categories[r.category]:`修订 ${r.revision} · 编辑版本 ${r.version}`}</td><td>{'enabled'in r?(r.enabled?'启用':'停用'):(r.state==='published'?'已发布 · 冻结':'草稿')}</td><td><button disabled={locked} onClick={()=>{setSelected(r);setEditing(false);setError('');}}>查看 {r.name}</button></td></tr>)}</tbody></table></div>
    {!rows.length&&<p className="empty">{busy?'正在加载…':'当前企业尚无记录。'}</p>}
    {selected&&!editing&&<section className="modal-section"><div className="panel-title"><h3>{selected.name}</h3><button onClick={()=>setSelected(null)}>关闭详情</button></div>
      {'category'in selected?<><p>{selected.number} · {categories[selected.category]} · {selected.enabled?'启用':'停用'} · 版本 {selected.version}</p><p>制造商：{selected.manufacturer} / 销售品牌：{selected.brand}（{selected.brand_kind==='own'?'自有':'第三方'}）</p><div className="catalog-specs">{Object.entries(selected.specs??{}).filter(([,v])=>v!==null&&v!=='').map(([k,v])=><p key={k}>{specLabels[k]}：{String(v)}</p>)}</div></>:
      'snapshot'in selected?<><p>{selected.kind==='package'?'准系统包件':'BOM'} · 修订 {selected.revision} · {selected.state==='published'?'冻结快照':'草稿预览'}</p><p>主体：{selected.snapshot.subject.name} / {selected.snapshot.subject.number}</p><p>规则来源：{selected.snapshot.rule?`${selected.snapshot.rule.source} / v${selected.snapshot.rule.revision}`:'未知'}</p><div className="table-wrap"><table><thead><tr><th>技术部件</th><th>数量</th><th>必选性</th><th>商业归属</th></tr></thead><tbody>{selected.snapshot.technical_lines.map((l,n)=><tr key={n}><td>{l.sku.name}</td><td>{l.quantity}</td><td>{l.required?'必选':'可选'}</td><td>{l.charge_mode==='included'?'含于包件，不另收费':'另行定价（未计价）'}</td></tr>)}</tbody></table></div>{selected.snapshot.checks.map(check=><p key={check.code} className={check.status==='BLOCK'?'error':'muted'}><strong>{check.status}</strong> · {check.message}</p>)}<p className="muted">替换包含件没有自动抵扣；本页不计算报价、成本或利润。</p></>:
      <><p>修订 {selected.revision} · {selected.currency} · {selected.tax_included?'含税':'不含税'} · 范围 {selected.scope}</p><p>有效期 [{selected.valid_from}, {selected.valid_to})</p><p>来源：{selected.source}</p>{selected.lines.map(l=><p key={l.sku_id}>{skus.find(s=>s.id===l.sku_id)?.number??l.sku_id}：{l.amount} CNY</p>)}{selected.checks?.map((check,n)=><p key={n} className="error"><strong>{check.status}</strong> · {check.message}</p>)}</>}
      <div className="modal-actions"><button disabled={!canWrite||locked||!!published} onClick={()=>begin(selected)}>编辑草稿{page==='skus'?' / 商品':''}</button>{page!=='skus'&&<button className="primary" disabled={!canWrite||locked} onClick={()=>void versionAction(published?'revise':'publish')}>{published?'创建修订':'发布版本'}</button>}</div>
    </section>}
    {editing&&<form className="modal-section" onSubmit={save}><div className="panel-title"><h3>{selected?'编辑':'新建'}{names[page]}</h3><button type="button" onClick={()=>setEditing(false)}>取消编辑</button></div><fieldset disabled={locked||!canWrite||!!published}>
      {page==='skus'?<><div className="form-grid">{(['number','name','manufacturer','brand'] as const).map(k=><label key={k}>{({number:'SKU 编号',name:'商品名称',manufacturer:'制造商',brand:'销售品牌'})[k]}<input required maxLength={k==='number'?40:160} value={skuForm[k]} onChange={e=>{idempotency.current={signature:'',key:crypto.randomUUID()};setSkuForm({...skuForm,[k]:e.target.value});}}/></label>)}<label>类别<select value={skuForm.category} onChange={e=>setSkuForm({...skuForm,category:e.target.value as SKUInput['category']})}>{Object.entries(categories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>品牌属性<select value={skuForm.brand_kind} onChange={e=>setSkuForm({...skuForm,brand_kind:e.target.value as SKUInput['brand_kind']})}><option value="third_party">第三方品牌</option><option value="own">自有品牌</option></select></label><label>状态<select value={String(skuForm.enabled)} onChange={e=>setSkuForm({...skuForm,enabled:e.target.value==='true'})}><option value="true">启用</option><option value="false">停用</option></select></label></div><h4>结构化规格 · 不确定的属性留空</h4><div className="form-grid">{Object.entries(specLabels).map(([key,label])=><label key={key}>{label}<input type={textSpecs.has(key)?'text':'number'} min="1" step="1" value={(skuForm.specs as Record<string,string|number|null>)?.[key]??''} onChange={e=>setSkuForm({...skuForm,specs:{...emptySpecs,...skuForm.specs,[key]:textSpecs.has(key)?e.target.value:e.target.value===''?null:Number(e.target.value)}})}/></label>)}</div></>:
      page==='boms'&&bomForm?<><div className="form-grid"><label>包件 / BOM 名称<input required value={bomForm.name} onChange={e=>setBomForm({...bomForm,name:e.target.value})}/></label><label>类型<select value={bomForm.kind} onChange={e=>setBomForm({...bomForm,kind:e.target.value as BOMInput['kind']})}><option value="package">准系统包件（包含行）</option><option value="bom">BOM（允许另计价行）</option></select></label><label>主体 SKU<select required value={bomForm.subject_sku_id} onChange={e=>setBomForm({...bomForm,subject_sku_id:e.target.value})}><option value="">请选择</option>{skus.map(s=><option key={s.id} value={s.id}>{s.number} · {s.name}</option>)}</select></label><label>规则版本<select value={bomForm.rule_id??''} onChange={e=>setBomForm({...bomForm,rule_id:e.target.value||null})}><option value="">无资料 · UNKNOWN</option>{rules.map(r=><option key={r.id} value={r.id}>{r.name} v{r.revision}</option>)}</select></label></div>
      {(bomForm.lines??[]).map((l,n)=><div className="nested-card form-grid" key={n}><label>部件 {n+1}<select required value={l.sku_id} onChange={e=>setBomForm({...bomForm,lines:bomForm.lines?.map((x,i)=>i===n?{...x,sku_id:e.target.value,package_version_id:null}:x)})}><option value="">请选择</option>{skus.map(s=><option key={s.id} value={s.id}>{s.number} · {s.name}</option>)}</select></label><label>数量 {n+1}<input required type="number" min="1" max="10000" step="1" value={l.quantity} onChange={e=>setBomForm({...bomForm,lines:bomForm.lines?.map((x,i)=>i===n?{...x,quantity:Number(e.target.value)}:x)})}/></label><label>包含包件版本 {n+1}<select value={l.package_version_id??''} onChange={e=>setBomForm({...bomForm,lines:bomForm.lines?.map((x,i)=>i===n?{...x,package_version_id:e.target.value||null}:x)})}><option value="">单个 SKU</option>{boms.filter(b=>b.kind==='package'&&b.state==='published'&&b.subject_sku_id===l.sku_id).map(b=><option key={b.id} value={b.id}>{b.name} v{b.revision}</option>)}</select></label><label>商业归属 {n+1}<select value={l.charge_mode} onChange={e=>setBomForm({...bomForm,lines:bomForm.lines?.map((x,i)=>i===n?{...x,charge_mode:e.target.value as 'included'|'separate'}:x)})}><option value="included">包含，不重复收费</option>{bomForm.kind==='bom'&&<option value="separate">另行定价</option>}</select></label><label>必选性 {n+1}<select value={String(l.required)} onChange={e=>setBomForm({...bomForm,lines:bomForm.lines?.map((x,i)=>i===n?{...x,required:e.target.value==='true'}:x)})}><option value="true">必选</option><option value="false">可选</option></select></label><button type="button" onClick={()=>setBomForm({...bomForm,lines:bomForm.lines?.filter((_,i)=>i!==n)})}>移除部件 {n+1}</button></div>)}<button type="button" onClick={()=>setBomForm({...bomForm,lines:[...(bomForm.lines??[]),{sku_id:'',quantity:1,required:true,charge_mode:'included'}]})}>添加部件</button></>:
      priceForm?<><div className="form-grid">{(['name','scope','source'] as const).map(k=><label key={k}>{({name:'价格表名称',scope:'适用范围',source:'价格来源'})[k]}<input required value={priceForm[k]} onChange={e=>setPriceForm({...priceForm,[k]:e.target.value})}/></label>)}<label>税口径<select value={String(priceForm.tax_included)} onChange={e=>setPriceForm({...priceForm,tax_included:e.target.value==='true'})}><option value="true">含税 CNY</option><option value="false">不含税 CNY</option></select></label>{(['valid_from','valid_to'] as const).map(k=><label key={k}>{k==='valid_from'?'生效时间 UTC（包含）':'截止时间 UTC（不包含）'}<input required type="datetime-local" value={utcInput(priceForm[k])} onInput={e=>setPriceForm({...priceForm,[k]:fromUtcInput(e.currentTarget.value)})}/></label>)}</div>{priceForm.lines.map((l,n)=><div className="nested-card form-grid" key={n}><label>定价 SKU {n+1}<select required value={l.sku_id} onChange={e=>setPriceForm({...priceForm,lines:priceForm.lines.map((x,i)=>i===n?{...x,sku_id:e.target.value}:x)})}><option value="">请选择</option>{skus.map(s=><option key={s.id} value={s.id}>{s.number} · {s.name}</option>)}</select></label><label>金额 CNY {n+1}<input required type="text" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" value={l.amount} onChange={e=>setPriceForm({...priceForm,lines:priceForm.lines.map((x,i)=>i===n?{...x,amount:e.target.value}:x)})}/></label><button type="button" onClick={()=>setPriceForm({...priceForm,lines:priceForm.lines.filter((_,i)=>i!==n)})}>移除价格 {n+1}</button></div>)}<button type="button" onClick={()=>setPriceForm({...priceForm,lines:[...priceForm.lines,{sku_id:'',amount:''}]})}>添加价格</button><p className="muted">不换算税额；金额最多两位小数。零价须明确填写 0.00；未定价不是零价。</p></>:null}
      <div className="modal-actions"><button className="primary" type="submit">{busy?'保存中…':'保存目录记录'}</button></div></fieldset></form>}
    {page==='boms'&&<details className="modal-section"><summary>平台规则与来源维护</summary><p>有限示例规则；缺少资料的维度始终 UNKNOWN。</p><form onSubmit={saveRule}><fieldset disabled={locked||!canWrite}><div className="form-grid"><label>修订来源<select value={ruleParent} onChange={e=>setRuleParent(e.target.value)}><option value="">新规则系列</option>{rules.map(r=><option key={r.id} value={r.id}>{r.name} v{r.revision}</option>)}</select></label>{(['name','source','socket','memory_generation'] as const).map(k=><label key={k}>{({name:'规则名称',source:'规则资料来源',socket:'规则 CPU 插槽',memory_generation:'规则内存代际'})[k]}<input required={k==='name'||k==='source'} value={ruleForm[k]??''} onChange={e=>setRuleForm({...ruleForm,[k]:e.target.value})}/></label>)}<label>示例功率预算 W<input type="number" min="1" value={ruleForm.power_budget_w??''} onChange={e=>setRuleForm({...ruleForm,power_budget_w:e.target.value?Number(e.target.value):null})}/></label></div><button type="submit">保存规则版本</button></fieldset></form></details>}
    {page==='price-books'&&<section className="modal-section"><h3>查询当前有效价格</h3><div className="form-grid"><label>查询 SKU<select disabled={locked} value={lookupSku} onChange={e=>{setLookupSku(e.target.value);setCurrent(null);}}><option value="">请选择</option>{skus.map(s=><option key={s.id} value={s.id}>{s.number} · {s.name}</option>)}</select></label><label>查询范围<input disabled={locked} value={lookupScope} onChange={e=>{setLookupScope(e.target.value);setCurrent(null);}}/></label><label>查询税口径<select disabled={locked} value={String(lookupTax)} onChange={e=>{setLookupTax(e.target.value==='true');setCurrent(null);}}><option value="true">含税</option><option value="false">不含税</option></select></label></div><button disabled={locked||!lookupSku||!lookupScope} onClick={()=>void lookup()}>查询当前价格</button>{current&&<div className="nested-card"><strong>{current.status==='KNOWN'?`${current.amount} CNY`:({UNKNOWN:'价格未知',EXPIRED:'价格已过期',NOT_YET_VALID:'价格尚未生效'})[current.status]}</strong><p>来源：{current.source??'未配置'} · 修订 {current.revision??'—'}</p><p>{current.valid_from??'—'} → {current.valid_to??'—'}（截止不包含）</p></div>}</section>}
  </section>;
}
