import {useEffect,useRef,useState} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket,Member} from './api';
type S=components['schemas'];type Work=S['Workspace'];type Fields=Work['fields'];type Order=S['Order'];
const messages:Record<string,string>={PARTIES_INCOMPLETE:'请补齐甲乙方主体、签约代表、项目负责人及关键联系人。',RESPONSIBILITY_REQUIRED:'请选择销售和售后负责人。',RESPONSIBILITY_INACTIVE:'责任人已停用，请重新分配。',SIGNING_DATE_INVALID:'请填写不晚于今天的线下签约日期。',DELIVERY_REQUIRED:'请填写交付日期或约定说明。',PAYMENTS_UNBALANCED:'付款节点合计必须等于合同金额。',PROOF_REQUIRED:'请上传并关联至少一份签约证明。',SOURCE_NOT_ACTIVE:'来源报价已过期或撤回，不能登记签约；请返回报价流程处理。',ZERO_CONTRACT_POLICY_UNCONFIGURED:'零金额签约政策未配置。',FORMAL_POLICY_REQUIRED:'正式签约政策未配置。',VERSION_CONFLICT:'合同版本已变化，请重新载入并合并修改。',CONTRACT_ALREADY_SIGNED:'合同已签，只能查看冻结内容；本期不支持变更。',CONFIRMATION_STALE:'确认内容已变化，请重新查看签约预览。',FILE_TYPE_REJECTED:'文件内容与允许的 PDF/JPEG/PNG 类型不符。',FILE_SIZE_LIMIT:'文件为空或超出配置大小上限。',FILE_NOT_READY:'文件未就绪或完整性校验失败。',INVALID_FILENAME:'文件名无效，请使用不含路径的文件名。',INVALID_CONTRACT_RELATION:'合同编号重复或关联资料无效。',FILE_STORAGE_UNCONFIGURED:'私有文件存储尚未配置。'};
function message(e:unknown){return e instanceof ApiError?(messages[e.code]??errorMessage(e)):errorMessage(e);}
export function Contracts({context,members,canWrite,canSign,ordersOnly=false,onOpenQuotes,onContextError}:{context:ContextTicket;members:Member[];canWrite:boolean;canSign:boolean;ordersOnly?:boolean;onOpenQuotes?:()=>void;onContextError:(e:unknown)=>void}){
 const [rows,setRows]=useState<Work[]>([]),[orders,setOrders]=useState<Order[]>([]),[work,setWork]=useState<Work|null>(null),[order,setOrder]=useState<Order|null>(null),[form,setForm]=useState<Fields|null>(null);
 const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(false),[category,setCategory]=useState('proof'),[file,setFile]=useState<File|null>(null);
 const generation=useRef(0),keys=useRef(new Map<string,string>());
 useEffect(()=>()=>{generation.current++;},[context.context_id]);
 async function run<T>(job:()=>Promise<T>,done:(v:T)=>void,text=''){
  const n=++generation.current;setBusy(true);setError('');setNotice('');
  try{const v=await job();if(n===generation.current&&crmRequests.isCurrent(context)){done(v);setNotice(text);}}
  catch(e){if(n!==generation.current||e instanceof StaleResponse)return;if(isContextError(e)||e instanceof ApiError&&e.status===401)onContextError(e);else setError(message(e));}
  finally{if(n===generation.current)setBusy(false);}
 }
 const get=<T,>(path:string)=>crmRequests.request<T>(context,'/contracts'+path);
 function post<T>(path:string,body:unknown){const signature=JSON.stringify([path,body]);if(!keys.current.has(signature))keys.current.set(signature,crypto.randomUUID());return crmRequests.request<T>(context,'/contracts'+path,{method:'POST',headers:{'Idempotency-Key':keys.current.get(signature)!},body:JSON.stringify(body)});}
 const load=()=>Promise.all([get<Work[]>(''),get<Order[]>('/orders')]);
 function refresh(){void run(load,([r,o])=>{setRows(r);setOrders(o);});}
 useEffect(refresh,[context.context_id]);
 function apply(w:Work){setWork(w);setForm(structuredClone(w.fields));setDirty(false);setConfirm(false);setOrder(null);setFile(null);setRows(r=>r.map(x=>x.id===w.id?w:x));}
 function open(id:string){void run(()=>get<Work>('/'+id),apply);}
 function change(value:Fields){setForm(value);setDirty(true);setConfirm(false);setNotice('');}
 const fileLocked=busy||!canWrite;
 const locked=busy||!canWrite||work?.state==='signed';
 async function upload(){if(!file||!work)return;const selected=file;
  void run(async()=>{const bytes=await selected.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');const signature=JSON.stringify([work.id,work.version,selected.name,category,digest]);if(!keys.current.has(signature))keys.current.set(signature,crypto.randomUUID());
   await crmRequests.request(context,'/contracts/'+work.id+'/uploads?'+new URLSearchParams({name:selected.name,category,expected_version:String(work.version)}),{method:'POST',headers:{'Content-Type':'application/octet-stream','Idempotency-Key':keys.current.get(signature)!},body:bytes});return get<Work>('/'+work.id);},apply,'上传已就绪，请点击关联；上传不代表签约。');
 }
 function download(id:string,name:string){void run(async()=>{
  const response=await fetch('/api/v1/contracts/files/'+id+'/download',{headers:{'X-Expected-Tenant':context.tenant_id,'X-Session-Context':context.context_id},signal:AbortSignal.any([context.signal,AbortSignal.timeout(10000)])});
  if(!response.ok){const e=await response.json();throw new ApiError(response.status,e.code,e.message);}
  const blob=await response.blob();if(!crmRequests.isCurrent(context))throw new StaleResponse();return blob;
 },blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'已通过权限检查，文件下载已开始。');}
 const input=(label:string,value:string,onChange:(v:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>;
 return <section className="panel publication-panel contracts-panel"><div className="panel-title"><div><h2>{ordersOnly?'销售订单':'合同完善与签约登记'}</h2><p>线下签约事实登记；付款节点是约定，不是已收款。订单不代表发货。</p></div><button disabled={busy} onClick={refresh}>刷新列表</button></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="publication-layout"><nav aria-label="合同与订单列表">{!ordersOnly&&rows.map(x=><button disabled={busy} key={x.id} onClick={()=>open(x.id)}>{x.fields.number||'待编号'} · {x.fields.name||x.source.content.config.name} · {x.state==='signed'?'已签':'草稿'}<small>{x.fields.buyer?.name} · {x.source.content.calculation.total} CNY · {x.fields.sales?.name||'销售待分配'} / {x.fields.support?.name||'售后待分配'}</small></button>)}<h3>待履行订单</h3>{orders.map(x=><button disabled={busy} key={x.id} onClick={()=>void run(()=>get<Order>('/orders/'+x.id),v=>{setOrder(v);setWork(null);setForm(null);setDirty(false);})}>{x.number} · {x.amount} CNY</button>)}{!rows.length&&!orders.length&&<p>暂无记录；请先从有效发布报价生成合同草稿。</p>}</nav>
 <article>{order?<><h2>{order.number} · 待履行</h2><p>{String(order.content.development?'演示数据 / 开发政策，不用于真实商务':'正式政策')}</p><strong>{order.amount} CNY</strong><p>实际收款、开票、发货、验收：未接入。没有库存、SN 或已交付设备档案。</p><button onClick={()=>void run(()=>get<S['Signed']>('/signed/'+order.contract_version_id),v=>open(v.contract_id))}>返回合同</button><p>来源报价版本 {order.quote_version_id}</p>{onOpenQuotes&&<button onClick={onOpenQuotes}>查看报价版本历史</button>}<OrderContent content={order.content}/></>:work&&form?<>
 <h2>{work.state==='signed'?'已签合同 · 冻结内容':'合同草稿'} · v{work.version}</h2><p className="eyebrow">{work.source.content.development?'演示数据 / 开发政策，不用于真实商务':'正式政策'}</p>
 <p>来源 {work.source.source_number} · {work.source.source_hash}</p>{work.source.source_state!=='issued'&&<p role="alert" className="error">来源报价已失效；已签内容保留，新的登记被阻断。</p>}
 <button disabled={busy} onClick={()=>open(work.id)}>重新载入合同</button>{onOpenQuotes&&<button onClick={onOpenQuotes}>查看报价版本历史</button>}{dirty&&<p>存在未保存修改；请先保存再处理附件或确认签约。</p>}
 <fieldset disabled={locked} className="contract-fields">
 {input('合同编号',form.number??'',v=>change({...form,number:v}))}{input('合同名称',form.name??'',v=>change({...form,name:v}))}
 {(['buyer','seller'] as const).map(side=><section className="nested-card" key={side}><h3>{side==='buyer'?'甲方':'乙方'}主体</h3>{(['name','address','identifier','representative'] as const).map((key,n)=>input((side==='buyer'?'甲方':'乙方')+['名称','地址','主体标识（选填）','签约代表'][n],form[side]?.[key]??'',v=>change({...form,[side]:{...form[side],[key]:v}})))}</section>)}
 <h3>客户联系人与内部责任人</h3>{input('项目负责人',form.project_lead?.name??'',v=>change({...form,project_lead:{contact:form.project_lead?.contact??'',name:v}}))}{input('项目负责人联系方式',form.project_lead?.contact??'',v=>change({...form,project_lead:{name:form.project_lead?.name??'',contact:v}}))}
 {(form.key_contacts??[]).map((x,n)=><div className="nested-card" key={n}>{input('关键联系人 '+(n+1),x.name??'',v=>change({...form,key_contacts:form.key_contacts!.map((p,i)=>i===n?{...p,name:v}:p)}))}{input('联系方式 '+(n+1),x.contact??'',v=>change({...form,key_contacts:form.key_contacts!.map((p,i)=>i===n?{...p,contact:v}:p)}))}<button onClick={()=>change({...form,key_contacts:form.key_contacts!.filter((_,i)=>i!==n)})}>移除联系人 {n+1}</button></div>)}
 <button onClick={()=>change({...form,key_contacts:[...(form.key_contacts??[]),{name:'',contact:''}]})}>添加关键联系人</button>
 {(['sales','support'] as const).map(role=><label key={role}>{role==='sales'?'销售负责人':'售后负责人'}<select value={form[role]?.user_id??''} onChange={e=>change({...form,[role]:{user_id:e.target.value||null,name:''}})}><option value="">请选择</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><small>历史姓名：{form[role]?.name||'保存时由服务端记录'}</small></label>)}
 {input('线下签约日期',form.signing_date??'',v=>change({...form,signing_date:v||null}),'date')}{input('约定交付日期',form.delivery_date??'',v=>change({...form,delivery_date:v||null}),'date')}{input('交付说明',form.delivery_note??'',v=>change({...form,delivery_note:v}))}{input('商务备注',form.notes??'',v=>change({...form,notes:v}))}
 <h3>付款约定 · 合同金额 {work.source.content.calculation.total} CNY</h3>
 {(form.payments??[]).map((x,n)=><div className="nested-card" key={x.id}>{input('节点名称 '+(n+1),x.name,v=>change({...form,payments:form.payments!.map((p,i)=>i===n?{...p,name:v}:p)}))}{input('节点金额 '+(n+1),String(x.amount),v=>change({...form,payments:form.payments!.map((p,i)=>i===n?{...p,amount:v}:p)}))}<label>到期方式 {n+1}<select value={x.trigger} onChange={e=>change({...form,payments:form.payments!.map((p,i)=>i===n?{...p,trigger:e.target.value as typeof x.trigger,due_date:null,offset_days:0}:p)})}><option value="date">固定日期</option><option value="signing">签约日期起</option><option value="delivery">交付后（待触发）</option><option value="acceptance">验收后（待触发）</option></select></label>{x.trigger==='date'?input('到期日期 '+(n+1),x.due_date??'',v=>change({...form,payments:form.payments!.map((p,i)=>i===n?{...p,due_date:v||null}:p)}),'date'):input('偏移日历天 '+(n+1),String(x.offset_days??0),v=>change({...form,payments:form.payments!.map((p,i)=>i===n?{...p,offset_days:Number(v)}:p)}),'number')}<button onClick={()=>change({...form,payments:form.payments!.filter((_,i)=>i!==n)})}>移除节点 {n+1}</button></div>)}
 <button onClick={()=>change({...form,payments:[...(form.payments??[]),{id:crypto.randomUUID(),name:'付款节点',amount:'',currency:'CNY',trigger:'signing',offset_days:0,note:''}]})}>添加付款节点</button>
 <button className="primary" onClick={()=>void run(()=>post<Work>('/'+work.id+'/save',{expected_version:work.version,fields:form}),apply,'合同资料已保存；不代表签约。')}>保存合同资料</button></fieldset>
 <h3>来源商业内容 · 不可在合同改价</h3><strong>{work.source.content.calculation.total} CNY · {work.source.content.calculation.tax_included?'含税':'不含税'}</strong><p>变更配置或金额请返回报价修订、审批和发布流程。</p>
 {work.source.content.calculation.technical_lines.map((x,n)=><p key={n}>{x.sku.number} · {x.sku.name} · {x.sku.manufacturer} · {x.sku.brand} / {x.sku.brand_kind==='own'?'自主品牌':'第三方'} ×{x.quantity} · {x.charge_mode==='included'?'含于包件，不重复收费':'独立商业行'}</p>)}
 {work.source.content.calculation.priced_lines.map(x=><p key={x.sku_id}>{x.name} ×{x.quantity} · {x.line_amount} CNY</p>)}
 <h3>私有附件</h3><p>PDF/JPEG/PNG，默认最大10 MiB；类型检查不等于恶意软件扫描。上传后需显式关联。</p>
 <fieldset disabled={fileLocked||dirty||work.version===0}><label>附件用途<select value={category} onChange={e=>setCategory(e.target.value)}><option value="proof">签约证明</option><option value="contract">合同文件</option><option value="technical">技术配置</option><option value="other">其他</option></select></label><label>选择附件<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button disabled={!file} onClick={()=>void upload()}>上传附件</button></fieldset>
 {work.files.map(x=><div className="nested-card" key={x.id}><p>{x.name} · {x.size} bytes · {x.state==='linked'?'已关联':'待关联'} · {x.category} · {x.supplemental?'签约后补充，不属于原冻结集':'原合同材料'}</p><small>SHA-256 {x.sha256}</small>{x.state==='linked'&&<button disabled={busy} onClick={()=>download(x.id,x.name)}>下载 {x.name}</button>}{x.state==='pending'&&<button disabled={fileLocked||dirty||(work.state==='signed'&&!x.supplemental)} onClick={()=>void run(()=>post<Work>('/'+work.id+'/files/'+x.id+'/attach',{expected_version:work.version}),apply,'附件已关联。')}>关联 {x.name}</button>}<button disabled={fileLocked||dirty||(work.state==='signed'&&!x.supplemental)} onClick={()=>void run(()=>post<Work>('/'+work.id+'/files/'+x.id+'/delete',{expected_version:work.version}),apply,'附件关联已删除。')}>删除 {x.name}</button></div>)}
 {work.state==='signed'?<><p>已签内容及原附件只读；本期不支持变更或解除；后续上传仅为独立补充材料，不改变原冻结集。</p><button disabled={busy} onClick={()=>void run(()=>get<Order>('/orders/'+work.order_id),v=>{setOrder(v);setWork(null);setForm(null);})}>查看关联订单</button></>:<section className="nested-card"><h3>签约前确认</h3>{work.checks.map(x=><p className="error" key={x}>{messages[x]??x}</p>)}<p>确认版本 v{work.version}、上述主体/金额/付款计划及已关联附件；签约后不可原位修改。</p><p>本次内容 hash：{work.content_hash}</p><label><input type="checkbox" disabled={!canSign||busy||dirty||!work.ready} checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>我确认已在线下完成签约，登记的是以上版本</label><button className="primary" disabled={!confirm||!canSign||busy||dirty||!work.ready} onClick={()=>void run(async()=>{await post<S['Signed']>('/'+work.id+'/sign',{expected_version:work.version,content_hash:work.content_hash,confirmed:true});return get<Work>('/'+work.id);},apply,'签约事实已登记，销售订单已生成；未标记收款或交付。')}>登记签约并生成订单</button></section>}
 <h3>责任人与资料历史</h3>{(work.history??[]).map((x,n)=><p key={n}>版本 {String(x.version)} · {String(x.created_at)} · 销售：{(x.fields as Fields)?.sales?.name||'未分配'} / 售后：{(x.fields as Fields)?.support?.name||'未分配'}</p>)}
 </>:<p>请选择合同或订单。</p>}</article></div></section>;
}

function OrderContent({content}:{content:Order['content']}){
 const commercial=content.commercial as Work['source']['content'];const fields=content.fields as Fields;
 const payments=content.payments as (NonNullable<Fields['payments']>[number] & {resolved_due_date?:string|null})[];
 return <><h3>冻结主体与销售配置</h3><p>{fields.buyer?.name} → {fields.seller?.name} · 合同 {fields.number}</p><p>销售：{fields.sales?.name} / 售后：{fields.support?.name}</p><p>{commercial.calculation.tax_included?'含税':'不含税'}；金额来自签约快照。</p>{commercial.calculation.technical_lines.map((x,n)=><p key={n}>{x.sku.number} · {x.sku.name} · {x.sku.manufacturer} · {x.sku.brand} / {x.sku.brand_kind==='own'?'自主品牌':'第三方'} ×{x.quantity} · {x.charge_mode==='included'?'含于包件，不重复收费':'独立商业行'}</p>)}{commercial.calculation.priced_lines.map((x,n)=><p key={n}>{x.name} ×{x.quantity} · {x.line_amount} CNY</p>)}<h3>冻结付款约定 · 未接入实际收款</h3>{payments.map(x=><p key={x.id}>{x.name} · {x.amount} CNY · {x.resolved_due_date||'待触发'} · {x.trigger==='delivery'?'交付后':x.trigger==='acceptance'?'验收后':x.trigger==='signing'?'签约日起':'固定日期'}{x.trigger!=='date'&&` ${x.offset_days} 日历天`}</p>)}</>;
}
