import {useEffect,useRef,useState} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket} from './api';
type S=components['schemas'];type Device=S['DeliveryDeviceView'];type Ship=S['ShipmentView'];type Progress=S['DeliveryProgress'];type Location=S['LocationView'];
const label:Record<string,string>={pending:'待测试',pass:'测试通过',fail:'测试不通过',invalid:'原完工已失效',shipped:'已发货',draft:'发货草稿',confirmed:'已确认发货',cancelled:'已取消'};
const messages:Record<string,string>={DEVICE_TEST_REQUIRED:'设备未取得当前有效测试通过结果，不能发货。',COMPLETION_CHANGED:'设备完工或配置已变化，请重新测试并新建发货草稿。',VERSION_CONFLICT:'记录已变化，请刷新核对后重新操作。',DELIVERY_DOWNSTREAM_DEPENDENCY:'已有验收或退货记录，不能直接冲销。',ALREADY_RETURNED:'此设备已实际退回，不能重复办理。',ALREADY_ACCEPTED:'此设备已验收，不能重复登记。',ACTIVE_RESERVATION:'设备存在有效预留，请先核对并释放。',SHIPMENT_NOT_ACTIVE:'此发货批次尚未确认或已冲销。',ORDER_DEVICE_MISMATCH:'设备不属于所选订单。',ORDER_CAPACITY_EXCEEDED:'本次发货超过订单剩余待履约数量。'};
export function Delivery({context,onContextError,preferredShipment=''}:{preferredShipment?:string;context:ContextTicket;onContextError:(e:unknown)=>void}){
 const [devices,setDevices]=useState<Device[]>([]),[ships,setShips]=useState<Ship[]>([]),[orders,setOrders]=useState<Progress[]>([]),[locations,setLocations]=useState<Location[]>([]),[permissions,setPermissions]=useState<string[]>([]);
 const [device,setDevice]=useState(''),[ship,setShip]=useState(preferredShipment),[order,setOrder]=useState(''),[selected,setSelected]=useState<string[]>([]),[lines,setLines]=useState<string[]>([]);
 const [recipient,setRecipient]=useState(''),[address,setAddress]=useState(''),[contact,setContact]=useState(''),[location,setLocation]=useState(''),[reason,setReason]=useState(''),[proof,setProof]=useState('');
 const [testName,setTestName]=useState('启动与配置核对'),[result,setResult]=useState<'pass'|'fail'>('pass');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lock=useRef(false),generation=useRef(0),intent=useRef(crypto.randomUUID()),keys=useRef(new Map<string,string>());
 const get=<T,>(p:string)=>crmRequests.request<T>(context,p);
 const can=(p:string)=>permissions.includes(p);
 async function load(){const n=++generation.current;const [d,s,o,m]=await Promise.all([get<Device[]>('/delivery/devices'),get<Ship[]>('/delivery/shipments'),get<Progress[]>('/delivery/orders'),get<{permissions:string[]}>('/inventory/context')]);const l=m.permissions.includes('inventory.read')?await get<Location[]>('/inventory/locations'):[];if(n!==generation.current||!crmRequests.isCurrent(context))return;setDevices(d);setShips(s);setOrders(o);setPermissions(m.permissions);setLocations(l);}
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(e instanceof StaleResponse||isContextError(e)){setDevices([]);setShips([]);setSelected([]);setLines([]);onContextError(e);}else if(crmRequests.isCurrent(context))setError(e instanceof ApiError?(messages[e.code]??errorMessage(e))+' ['+e.code+']':errorMessage(e));}finally{lock.current=false;if(crmRequests.isCurrent(context))setBusy(false);}}
 useEffect(()=>{void run(load);},[context.context_id]);
 async function command<T>(path:string,body:unknown):Promise<T>{const sig=JSON.stringify([intent.current,path,body]);if(!keys.current.has(sig))keys.current.set(sig,crypto.randomUUID());return crmRequests.request<T>(context,'/delivery'+path,{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':keys.current.get(sig)!}});}
 const [at,setAt]=useState(new Date().toISOString().slice(0,16));
 const performed=()=>new Date(at+'Z').toISOString();
 const d=devices.find(x=>x.id===device),s=ships.find(x=>x.id===ship);
 function fresh(){intent.current=crypto.randomUUID();setShip('');setSelected([]);setLines([]);setError('');setNotice('');}
 const input=(name:string,value:string,set:(v:string)=>void,type='text')=><label>{name}<input type={type} value={value} onChange={e=>set(e.target.value)} onInput={e=>set(e.currentTarget.value)}/></label>;
 async function action(action:string,extra:object={}){if(!s)return;await command('/shipments/'+s.id+'/'+action,{expected_version:s.version,confirmed:true,reason:reason||'操作人员明确确认',...extra});await load();if(crmRequests.isCurrent(context)){setLines([]);setNotice('已保存并刷新。此操作不登记收付款。');}}
 return <section className="panel delivery-panel"><div className="toolbar"><h2>测试、发货与交付验收</h2><button disabled={busy} onClick={()=>void run(load)}>刷新查询</button></div><p>逐台测试 · 分批履约 · 实收退货。收款与发票在资金工作台独立登记。</p>{busy&&<p role="status">正在读取或保存…</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="metrics">{orders.map(o=><article className="metric" key={o.order_id}><strong>{o.number}</strong><p>{o.customer_name}</p><p>订单 {o.quantity} · 累计发出 {o.shipped} · 已退回 {o.returned}</p><p>净交付 {o.net_delivered} · 净验收 {o.net_accepted} · 待履约 {o.remaining}</p>{o.cost!==undefined&&<small>净出库成本 {o.cost} CNY</small>}</article>)}</div>
 <h3>设备测试与履历</h3>{!devices.length&&!busy&&<p>暂无设备，请先完成装配或选择有设备数据的企业。</p>}<label>选择设备<select value={device} onChange={e=>setDevice(e.target.value)}><option value="">请选择</option>{devices.map(x=><option key={x.id} value={x.id}>{x.serial} · {label[x.eligibility]}</option>)}</select></label>
 {d&&<article className="panel"><h3>{d.serial} · {label[d.eligibility]}</h3><p>{d.customer_name} · {d.order_number} · {d.product.name}</p><p>稳定设备 {d.id} · 有效完工 {d.completion_id}</p><p>测试必须适用于当前完工及库存版本。退货后重新测试；不代表客户验收。</p><fieldset disabled={busy||!can('delivery.test')||d.eligibility==='shipped'||d.reversed}>{input('测试项',testName,setTestName)}<label>测试结果<select value={result} onChange={e=>setResult(e.target.value as 'pass'|'fail')}><option value="pass">通过</option><option value="fail">不通过</option></select></label>{input('执行时间（UTC）',at,setAt,'datetime-local')}{input('报告登记编号（非公开下载链接）',proof,setProof)}{input('操作备注 / 原因',reason,setReason)}<button onClick={()=>void run(async()=>{await command('/devices/'+d.id+'/tests',{expected_version:d.version,completion_id:d.completion_id,performed_at:performed(),items:[{name:testName,result}],notes:reason,report_ref:proof});await load();if(crmRequests.isCurrent(context))setNotice('测试历史已追加。以当前有效结果判断发货资格。');})}>保存测试记录</button></fieldset>
 <details open><summary>测试与履约历史</summary>{d.tests.map(t=><p key={t.id}>{label[t.result]} · {t.performed_at} · {t.items.map(x=>x.name).join('、')} · 执行者 {t.actor_id} · {t.report_ref||'未登记报告编号'}</p>)}{d.deliveries.map(x=><div key={x.id}><p>发货批次 {x.shipment_id} · {x.reversed?'已冲销':x.returns.length?'已退回待检':'已发货'}</p>{x.acceptances.map(a=><p key={a.id}>{a.accepted?'验收':'验收更正'} · {a.performed_at} · {a.confirmation}</p>)}{x.returns.map(r=><p key={r.id}>实收退货 · {r.performed_at} · {r.reason}</p>)}</div>)}</details></article>}
 <div className="toolbar"><h3>发货批次</h3><button disabled={busy||!can('delivery.ship')} onClick={fresh}>新建发货草稿</button></div><div className="toolbar">{ships.map(x=><button key={x.id} onClick={()=>{setShip(x.id);setLines([]);setError('');}}>{x.id.slice(0,8)} · {x.reversals.length?'已冲销':label[x.state]}</button>)}</div>
 {!s?<fieldset disabled={busy||!can('delivery.ship')}><label>销售订单<select value={order} onChange={e=>{setOrder(e.target.value);setSelected([]);}}><option value="">请选择</option>{orders.map(x=><option key={x.order_id} value={x.order_id}>{x.number} · 待履约{x.remaining}</option>)}</select></label>{devices.filter(x=>x.order_id===order&&!x.reversed).map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/>{x.serial} · {label[x.eligibility]}</label>)}{input('收货单位',recipient,setRecipient)}{input('收货地址',address,setAddress)}{input('收货联系人',contact,setContact)}<p>选择 {selected.length} 台。保存草稿不出库、不占用库存；确认时重新校验。</p><button onClick={()=>void run(async()=>{const v=await command<Ship>('/shipments',{order_id:order,device_ids:selected,recipient,address,contact});await load();if(crmRequests.isCurrent(context)){setShip(v.id);setNotice('发货草稿已保存，尚未出库。');}})}>保存发货草稿</button></fieldset>:<article className="panel"><h3>批次 {s.id.slice(0,8)} · {s.reversals.length?'已冲销':label[s.state]}</h3><p>{s.recipient} · {s.address} · {s.contact}</p><p>本批 {s.lines.length} 台 · 订单剩余待履约 {s.progress.remaining}</p>{s.lines.map(x=><label key={x.id}><input type="checkbox" checked={lines.includes(x.id)} disabled={!!x.returns.length||busy} onChange={e=>setLines(e.target.checked?[...lines,x.id]:lines.filter(id=>id!==x.id))}/>{x.serial} · {x.returns.length?'已退回':x.accepted?'已验收':s.state==='confirmed'?'待验收':'草稿'}{x.cost!==undefined&&` · 原成本 ${x.cost} CNY`}</label>)}
 {s.state==='draft'?<><button disabled={busy||!can('delivery.ship')} onClick={()=>void run(()=>action('confirm'))}>确认实际发货</button><button disabled={busy||!can('delivery.ship')} onClick={()=>void run(()=>action('cancel'))}>取消草稿</button></>:s.state==='confirmed'&&!s.reversals.length&&<>{input('客户验收确认信息',contact,setContact)}{input('业务时间（UTC）',at,setAt,'datetime-local')}{input('证据登记编号',proof,setProof)}{input('业务原因',reason,setReason)}<button disabled={busy||!can('delivery.accept')||!lines.length} onClick={()=>void run(()=>action('accept',{line_ids:lines,performed_at:performed(),confirmation:contact,notes:reason,evidence_ref:proof}))}>登记所选设备验收</button><label>退回待检库位<select value={location} onChange={e=>setLocation(e.target.value)}><option value="">请选择</option>{locations.map(x=><option key={x.id} value={x.id}>{x.warehouse} / {x.name}</option>)}</select></label><p>仅在实际收到设备后确认退货。恢复待履约数量，不表示退款或测试合格。</p><button disabled={busy||!can('delivery.return')||!lines.length||!location} onClick={()=>void run(()=>action('return',{line_ids:lines,performed_at:performed(),location_id:location}))}>确认所选设备已实际退回</button><button disabled={busy||!can('delivery.correct')} onClick={()=>void run(()=>action('reverse'))}>冲销误操作发货（无下游时）</button>{s.lines.filter(x=>x.accepted&&!x.returns.length).map(x=><button key={x.id} disabled={busy||!can('delivery.correct')} onClick={()=>void run(()=>action('correct-acceptance',{acceptance_id:x.acceptances.at(-1)!.id,performed_at:performed(),confirmation:contact||'纠正误登记'}))}>更正 {x.serial} 验收登记</button>)}</>}
 </article>}
 {!can('delivery.ship')&&!busy&&<p>当前身份仅具备已授权的查询能力；服务端同样检查每项操作权限。</p>}
 </section>;
}
