import {useEffect,useRef,useState} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket} from './api';
type S=components['schemas'];type Source=S['SourceView'];type Plan=S['PlanView'];type Cash=S['CashView'];type Refund=S['RefundView'];type Invoice=S['InvoiceView'];type Summary=S['SummaryView'];type Party=S['PartyView'];
const state:Record<string,string>={draft:'草稿',confirmed:'已确认',cancelled:'已取消'};
const messages:Record<string,string>={FIN_CONSTRAINT:'编号、节点或流水已存在，或关联不符合约束，请核对原记录。',FIN_SOURCE_CAP_EXCEEDED:'计划超过合同可登记额度；如商业金额已变更，请先登记有依据的来源调整。',FIN_DEALLOCATE_FIRST:'有效金额不能低于已核销额，请先撤销相应核销。',FIN_AVAILABLE_EXCEEDED:'本次分配超过资金可用余额。',FIN_REMAINING_EXCEEDED:'本次分配超过项目未结余额。',FIN_REFUND_EXCEEDED:'可退款金额不足，请先解除必要的核销。',FIN_PLAN_NOT_SETTLEABLE:'项目未确认或尚未释放，不能核销。',FIN_INVOICE_CAP_EXCEEDED:'发票登记或红字金额超过来源可用额度。',FIN_DOWNSTREAM_DEPENDENCY:'存在有效下游记录，须先处理相关核销、退款或红字登记。',VERSION_CONFLICT:'记录已变化，请刷新核对后重新操作。',FIN_DUE_OR_CONDITION_REQUIRED:'请填写明确到期日或释放条件。',FIN_PARTY_DIRECTION_MISMATCH:'往来单位或收付方向不一致。'};
// Display only: integer cents avoid introducing floating point into money previews.
export function difference(a:string,b:string){try{const cents=(s:string)=>{if(!/^-?\d+(\.\d{1,2})?$/.test(s))throw Error();const [x,y='']=s.replace('-','').split('.');return (BigInt(x)*100n+BigInt(y.padEnd(2,'0')))*(s.startsWith('-')?-1n:1n);};const n=cents(a)-cents(b),v=n<0n?-n:n;return `${n<0n?'-':''}${v/100n}.${String(v%100n).padStart(2,'0')}`;}catch{return '待输入有效金额';}}

/** Independent optional enhancement. A 403 clears old finance data, never base content. */
export function FinanceSummary({context,direction,sourceId}:{context:ContextTicket;direction:'receivable'|'payable';sourceId:string}){
 const [value,setValue]=useState<S['SourceSummary']|null>(null),[error,setError]=useState('');const generation=useRef(0);
 useEffect(()=>{let alive=true;async function load(){const n=++generation.current;setValue(null);setError('');try{const v=await crmRequests.request<S['SourceSummary']>(context,`/finance/sources/${direction}/${sourceId}`);if(alive&&n===generation.current&&crmRequests.isCurrent(context))setValue(v);}catch(e){if(alive&&n===generation.current){setValue(null);setError(e instanceof ApiError&&e.status===403?'未授权查询资金摘要；合同与订单内容仍可用。':e instanceof StaleResponse?'企业已变化，资金摘要已清除。':'资金摘要暂不可用，可重新查询。');}}}void load();window.addEventListener('focus',load);const visibility=()=>{if(document.visibilityState==='visible')void load();};document.addEventListener('visibilitychange',visibility);return()=>{alive=false;generation.current++;window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',visibility);};},[context.context_id,direction,sourceId]);
 return <section className="nested-card" aria-label="资金摘要"><h3>经营资金摘要</h3>{error?<p>{error}</p>:value?<><p>来源约定 {value.source.amount} CNY · 有效发票登记 {value.invoiced} CNY</p>{value.plans.map(p=><p key={p.id}>{p.node} · {state[p.state]} · 未结 {p.remaining} CNY · {p.due_date||'待释放'}</p>)}{!value.plans.length&&<p>尚未显式建立应收/应付。</p>}</>:<p>正在独立读取资金摘要…</p>}</section>;
}

export function Finance({context,onContextError}:{context:ContextTicket;onContextError:(e:unknown)=>void}){
 const [tab,setTab]=useState<'plans'|'cash'|'refunds'|'invoices'>('plans');
 const [sources,setSources]=useState<Source[]>([]),[parties,setParties]=useState<Party[]>([]),[plans,setPlans]=useState<Plan[]>([]),[cash,setCash]=useState<Cash[]>([]),[refunds,setRefunds]=useState<Refund[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[summary,setSummary]=useState<Summary|null>(null),[permissions,setPermissions]=useState<string[]>([]);
 const [selected,setSelected]=useState(''),[direction,setDirection]=useState<'receivable'|'payable'>('receivable'),[party,setParty]=useState(''),[source,setSource]=useState('');
 const [amount,setAmount]=useState(''),[node,setNode]=useState(''),[due,setDue]=useState(''),[retention,setRetention]=useState(false),[condition,setCondition]=useState(''),[notes,setNotes]=useState('');
 const [account,setAccount]=useState(''),[method,setMethod]=useState('人工登记'),[external,setExternal]=useState(''),[purpose,setPurpose]=useState<'unallocated'|'advance'>('unallocated'),[at,setAt]=useState(new Date().toISOString().slice(0,16));
 const [reason,setReason]=useState(''),[basis,setBasis]=useState(''),[returnId,setReturnId]=useState(''),[adjust,setAdjust]=useState(''),[allocation,setAllocation]=useState<Record<string,string>>({}),[cashSource,setCashSource]=useState('');
 const [number,setNumber]=useState(''),[buyer,setBuyer]=useState(''),[seller,setSeller]=useState(''),[kind,setKind]=useState('人工发票登记'),[issued,setIssued]=useState(new Date().toISOString().slice(0,10)),[net,setNet]=useState(''),[tax,setTax]=useState(''),[archive,setArchive]=useState(''),[original,setOriginal]=useState(''),[invoiceLines,setInvoiceLines]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const alive=useRef(true),lock=useRef(false),generation=useRef(0),intent=useRef(crypto.randomUUID()),keys=useRef(new Map<string,string>());
 const current=()=>alive.current&&crmRequests.isCurrent(context);const can=(p:string)=>permissions.includes(p);
 const get=<T,>(path:string)=>crmRequests.request<T>(context,'/finance'+path);
 function clear(){setSources([]);setParties([]);setPlans([]);setCash([]);setRefunds([]);setInvoices([]);setSummary(null);setPermissions([]);setSelected('');setAllocation({});setInvoiceLines({});}
 async function load(){const n=++generation.current;const [ctx,src,pts,ps,cs,rs,vs,sum]=await Promise.all([get<S['FinanceContext']>('/context'),get<Source[]>('/sources'),get<Party[]>('/parties'),get<Plan[]>('/plans'),get<Cash[]>('/cash'),get<Refund[]>('/refunds'),get<Invoice[]>('/invoices'),get<Summary>('/summary')]);if(!current()||n!==generation.current)return;setPermissions(ctx.permissions);setSources(src);setParties(pts);setPlans(ps);setCash(cs);setRefunds(rs);setInvoices(vs);setSummary(sum);}
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(e instanceof StaleResponse||isContextError(e)||(e instanceof ApiError&&e.status===401)){clear();onContextError(e);}else if(current()){if(e instanceof ApiError&&e.status===403)clear();setError(e instanceof ApiError?(messages[e.code]??errorMessage(e))+' ['+e.code+']':errorMessage(e));}}finally{lock.current=false;if(current())setBusy(false);}}
 // StrictMode replays setup/cleanup: the first valid load must remain eligible.
 // Actual unmount/context replacement is fenced by alive + ContextTicket.
 useEffect(()=>{alive.current=true;void run(load);const focus=()=>void run(load);window.addEventListener('focus',focus);return()=>{alive.current=false;window.removeEventListener('focus',focus);};},[context.context_id]);
 async function command<T>(path:string,body:unknown):Promise<T>{const signature=JSON.stringify([intent.current,path,body]);if(!keys.current.has(signature))keys.current.set(signature,crypto.randomUUID());return crmRequests.request<T>(context,'/finance'+path,{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':keys.current.get(signature)!}});}
 function fresh(next=tab){intent.current=crypto.randomUUID();setTab(next);setSelected('');setAllocation({});setInvoiceLines({});setError('');setNotice('');}
 function open(id:string){setSelected(id);setAllocation({});setError('');setNotice('');}
 async function saved(path:string,body:unknown,select=true){const v=await command<{id:string}>(path,body);await load();if(current()){if(select)setSelected(v.id);setAllocation({});setNotice('已登记并刷新台账；没有执行外部转账或税务平台操作。');}}
 const b=(v:{version:number})=>({expected_version:v.version,confirmed:true,reason:reason||'经办人明确确认登记'});
 const p=plans.find(x=>x.id===selected),c=cash.find(x=>x.id===selected),r=refunds.find(x=>x.id===selected),v=invoices.find(x=>x.id===selected),src=sources.find(x=>x.id===source),originalCash=cash.find(x=>x.id===cashSource);
 const input=(label:string,value:string,set:(s:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)} onInput={e=>set(e.currentTarget.value)}/></label>;
 const button=(label:string,permission:string,fn:()=>Promise<void>,disabled=false)=><button disabled={busy||!can(permission)||disabled} onClick={()=>void run(fn)}>{label}</button>;
 const sourceSelect=<label>业务来源（合同 / 服务）<select value={source} onChange={e=>{setSource(e.target.value);const s=sources.find(x=>x.id===e.target.value);if(s){setParty(s.party_id);setDirection(s.direction);}}}><option value="">请选择有效业务来源</option>{sources.map(s=><option key={s.id} value={s.id}>{s.kind==='customer_service'?'客户服务':s.kind==='supplier_repair'?'供应商维修':s.direction==='receivable'?'销售':'采购'} · {s.number} · {s.party_name} · {s.amount} CNY</option>)}</select></label>;
 const partySelect=<><label>资金方向<select value={direction} onChange={e=>{setDirection(e.target.value as typeof direction);setParty('');setInvoiceLines({});}}><option value="receivable">客户收款 / 销项</option><option value="payable">供应商付款 / 进项</option></select></label><label>往来单位<select value={party} onChange={e=>{setParty(e.target.value);setInvoiceLines({});}}><option value="">请选择</option>{parties.filter(x=>x.direction===direction).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></>;
 return <section className="panel finance-panel"><div className="toolbar"><div><span className="eyebrow">SILICON / FINANCE</span><h2>资金工作台</h2></div><button disabled={busy} onClick={()=>void run(load)}>刷新台账</button></div><p>经营资金子台账 · CNY · 人工事实登记。合同额、应收和净现金流均不代表收入或利润。</p>{busy&&<p role="status">正在读取或登记…</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {summary&&<><div className="metrics">{([['未结应收','receivable'],['未结应付','payable'],['逾期应收','overdue_receivable'],['逾期应付','overdue_payable'],['实际收款','received'],['实际付款','paid'],['预收可用','advance_received'],['预付可用','advance_paid'],['收款待分配','unallocated_received'],['付款待分配','unallocated_paid'],['客户退款','customer_refunds'],['供应商退款','supplier_refunds'],['净现金流','net_cash_flow']] as const).map(([label,key])=><article className="metric" key={key}><small>{label}</small><strong>{summary[key]} <small>CNY</small></strong></article>)}</div><small>统计时间 {summary.as_of} · {summary.basis}</small></>}
 <div className="toolbar" aria-label="资金模块">{([['plans','应收应付'],['cash','实收实付与核销'],['refunds','退款登记'],['invoices','发票登记']] as const).map(([key,label])=><button key={key} disabled={busy} aria-pressed={tab===key} onClick={()=>fresh(key)}>{label}</button>)}</div>
 <div className="finance-layout"><nav aria-label="资金记录列表"><button disabled={busy} onClick={()=>fresh()}>新建{tab==='plans'?'计划':tab==='cash'?'资金':tab==='refunds'?'退款':'发票'}草稿</button>{(tab==='plans'?plans:tab==='cash'?cash:tab==='refunds'?refunds:invoices).map(x=><button key={x.id} disabled={busy} onClick={()=>open(x.id)} aria-pressed={selected===x.id}><strong>{'node' in x?x.node:'number' in x?x.number:'party_name' in x?x.party_name:x.reason}</strong><small>{x.amount} CNY · {state[x.state]} · {x.id.slice(0,8)}</small></button>)}{!(tab==='plans'?plans:tab==='cash'?cash:tab==='refunds'?refunds:invoices).length&&<p>暂无登记记录。</p>}</nav><article>
 {tab==='plans'&&(p?<><h3>{p.node} · {state[p.state]}</h3><p>{p.party_name} · 来源 {sources.find(x=>x.id===p.source_id)?.number} · v{p.version}</p><p>原金额 {p.amount} · 调整 {p.adjustment} · 有效金额 {p.effective} CNY</p><p>已核销 {p.allocated} · 未结 {p.remaining} CNY · {p.overdue?'已逾期':p.due_date||'待释放'}</p><p>{p.notes}</p><p>{p.retention?'质保金，包含在原价款内。':''}{p.release_condition}</p>{input('确认 / 更正原因',reason,setReason)}{p.state==='draft'?<>{button('确认应收应付','finance.confirm',()=>saved('/plans/'+p.id+'/confirm',b(p)))}{button('取消计划草稿','finance.plan',()=>saved('/plans/'+p.id+'/cancel',b(p)))}</>:p.state==='confirmed'&&<><h4>追加金额调整</h4>{input('调整金额（减少填负数）',adjust,setAdjust)}{input('商业依据编号',basis,setBasis)}{input('实收销售退货 ID（可选）',returnId,setReturnId)}{button('确认追加调整','finance.correct',()=>saved('/plans/'+p.id+'/adjust',{...b(p),amount:adjust,basis_ref:basis,return_id:returnId||null}))}{!p.released&&<><h4>确认释放条件已满足</h4>{input('释放后到期日',due,setDue,'date')}{button('确认释放（不新增金额）','finance.confirm',()=>saved('/plans/'+p.id+'/release',{...b(p),due_date:due}))}</>}</>}
 <h4>历史调整与核销</h4>{p.adjustments.map(x=><div className="nested-card" key={x.id}><p>原调整 {x.id.slice(0,8)} · {x.amount} · {x.reason} · {x.basis_ref} · {x.created_at}</p>{(p.corrections??[]).filter(c=>c.adjustment_id===x.id).map(c=><p key={c.id}>误减更正 {c.amount} CNY · 关联原调整 {x.id.slice(0,8)} · {c.reason} · {c.basis_ref} · {c.created_at}</p>)}{x.amount?.startsWith('-')&&!(p.corrections??[]).some(c=>c.adjustment_id===x.id)&&<><p>完整恢复本条误减，不增加合同额度；不会撤销退款或实物退货，已退款部分恢复为待结余额。</p>{button('撤销误减额 '+x.id.slice(0,8),'finance.correct',()=>saved('/plans/'+p.id+'/correct-adjustment',{...b(p),reason,adjustment_id:x.id,basis_ref:basis}),!reason.trim()||!basis.trim())}</>}</div>)}{p.releases.map(x=><p key={x.id}>释放 · {x.due_date} · {x.reason}</p>)}{p.allocations.map(x=><p key={x.id}>{x.reversed?'已撤销核销':'有效核销'} {x.amount} · 资金 {x.cash_id.slice(0,8)}</p>)}</>:<fieldset disabled={busy||!can('finance.plan')}><h3>建立应收 / 应付计划草稿</h3>{sourceSelect}{input('业务节点',node,setNode)}{input('计划金额 CNY',amount,setAmount)}{input('到期日',due,setDue,'date')}<label><input type="checkbox" checked={retention} onChange={e=>setRetention(e.target.checked)}/>质保金（原合同金额内拆分）</label>{input('释放条件（无到期日时必填）',condition,setCondition)}{input('计划说明',notes,setNotes)}{button('保存计划草稿','finance.plan',()=>saved('/plans',{direction:src?.direction,source_id:source,node,amount,due_date:due||null,retention,release_condition:condition,notes}),!src)}{src?.direction==='receivable'&&button('导入冻结付款节点为草稿','finance.plan',async()=>{await command('/plans/import',{source_id:src.id});await load();if(current())setNotice('已导入草稿；需要逐项明确确认。');})}<p>草稿不进入债权债务或现金汇总。修改内容请取消草稿后重新建立。</p></fieldset>)}
 {tab==='cash'&&(c?<><h3>{c.party_name} · {c.direction==='receivable'?'收款':'付款'} · {c.reversed?'已冲销':state[c.state]}</h3><p>原资金 {c.amount} · 已核销 {c.allocated} · 已退款 {c.refunded} · 可分配 {c.available} CNY</p><p>{c.account} / {c.method} · 流水 {c.external_ref||'未提供，人工登记不能保证线下绝不重复'} · {c.occurred_at}</p><p>{c.purpose==='advance'?'预收 / 预付':'普通待分配资金'} · {c.notes}</p><p>经办人 {c.actor_id}</p>{input('确认 / 撤销原因',reason,setReason)}{c.state==='draft'?<>{button('确认已实际收付','finance.cash',()=>saved('/cash/'+c.id+'/confirm',b(c)))}{button('取消资金草稿','finance.cash',()=>saved('/cash/'+c.id+'/cancel',b(c)))}</>:c.state==='confirmed'&&!c.reversed&&<><h4>多行核销 · 仅分配已有资金</h4>{plans.filter(p=>p.party_id===c.party_id&&p.direction===c.direction&&p.state==='confirmed').map(p=><div className="nested-card" key={p.id}><p>{p.node} · 未结 {p.remaining} · {p.released?'可结算':'待释放'}</p>{input('本次分配 '+p.node,allocation[p.id]||'',v=>setAllocation({...allocation,[p.id]:v}))}<small>核销后项目余额 {difference(p.remaining,allocation[p.id]||'0')} CNY（预览，后端重新核验）</small></div>)}{button('确认本次多行核销','finance.allocate',()=>saved('/cash/'+c.id+'/allocate',{...b(c),lines:Object.entries(allocation).filter(([,amount])=>amount!=='').map(([id,amount])=>({plan_id:id,expected_version:plans.find(p=>p.id===id)!.version,amount}))}))}{button('冲销原资金（须无有效下游）','finance.correct',()=>saved('/cash/'+c.id+'/reverse',b(c)))}{button('为此资金建立退款草稿','finance.correct',async()=>{fresh('refunds');setCashSource(c.id);})}</>}
 <h4>核销历史</h4>{c.allocations.map(x=><div className="nested-card" key={x.id}><p>{plans.find(p=>p.id===x.plan_id)?.node} · {x.amount} CNY · {x.reversed?'已撤销':'有效'} · {x.created_at}</p>{!x.reversed&&button('撤销核销 '+x.id.slice(0,8),'finance.correct',()=>saved('/allocations/'+x.id+'/reverse',b(c)))}</div>)}</>:<fieldset disabled={busy||!can('finance.cash')}><h3>登记资金草稿</h3>{partySelect}{input('资金金额 CNY',amount,setAmount)}<label>资金用途<select value={purpose} onChange={e=>setPurpose(e.target.value as typeof purpose)}><option value="unallocated">普通待分配</option><option value="advance">预收 / 预付</option></select></label>{input('实际发生时间（UTC）',at,setAt,'datetime-local')}{input('收付方式',method,setMethod)}{input('内部账户标识（未连接银行）',account,setAccount)}{input('外部流水参考号（可空）',external,setExternal)}{input('资金备注（必填）',notes,setNotes)}{button('保存资金草稿','finance.cash',()=>saved('/cash',{direction,party_id:party,amount,purpose,occurred_at:new Date(at+'Z').toISOString(),method,account,external_ref:external,notes}))}<p>保存草稿不表示转账；明确确认后登记已发生事实。网络重试保留同一操作身份。</p></fieldset>)}
 {tab==='refunds'&&(r?<><h3>退款 {r.id.slice(0,8)} · {r.reversed?'已冲销':state[r.state]}</h3><p>{r.amount} CNY · 原资金 {r.cash_id.slice(0,8)} · {r.reason} · {r.occurred_at}</p><p>当前原资金可退 {cash.find(c=>c.id===r.cash_id)?.available} CNY</p>{input('退款确认 / 更正原因',reason,setReason)}{r.state==='draft'?<>{button('确认退款已实际发生','finance.correct',()=>saved('/refunds/'+r.id+'/confirm',{...b(r),cash_version:cash.find(c=>c.id===r.cash_id)!.version}))}{button('取消退款草稿','finance.correct',()=>saved('/refunds/'+r.id+'/cancel',b(r)))}</>:!r.reversed&&r.state==='confirmed'&&button('冲销误登记退款','finance.correct',()=>saved('/refunds/'+r.id+'/reverse',b(r)))}</>:<fieldset disabled={busy||!can('finance.correct')}><h3>退款草稿 · 每条关联一个原资金来源</h3><label>原资金<select value={cashSource} onChange={e=>setCashSource(e.target.value)}><option value="">请选择</option>{cash.filter(c=>c.state==='confirmed'&&!c.reversed).map(c=><option key={c.id} value={c.id}>{c.party_name} · {c.direction==='receivable'?'客户退款':'供应商退款'} · {c.id.slice(0,8)} · 可退 {c.available}</option>)}</select></label><p>原资金可退 {originalCash?.available??'—'} CNY；核销款须先解除。</p>{input('退款金额 CNY',amount,setAmount)}{input('退款发生时间（UTC）',at,setAt,'datetime-local')}{input('退款账户',account,setAccount)}{input('退款流水参考号',external,setExternal)}{input('退款原因',reason,setReason)}{button('保存退款草稿','finance.correct',()=>saved('/refunds',{cash_id:cashSource,amount,occurred_at:new Date(at+'Z').toISOString(),account,external_ref:external,reason}))}</fieldset>)}
 {tab==='invoices'&&(v?<><h3>{v.number} · {v.original_id?'红字关联':'正向登记'} · {v.reversed?'已作废登记':state[v.state]}</h3><p>{v.buyer} → {v.seller} · {v.issued_on} · {v.kind}</p><p>含税金额 {v.amount} · 不含税 {v.net_amount??'未确认'} · 税额 {v.tax_amount??'未确认'} CNY</p><p>档案编号 {v.archive_ref||'未登记'}（不是上传、公开下载或验真）</p>{v.lines.map(l=><p key={l.id}>{sources.find(s=>s.id===l.source_id)?.number} · {l.amount} CNY</p>)}{input('发票确认 / 作废原因',reason,setReason)}{v.state==='draft'?<>{button('确认人工发票登记','finance.invoice',()=>saved('/invoices/'+v.id+'/confirm',b(v)))}{button('取消发票草稿','finance.invoice',()=>saved('/invoices/'+v.id+'/cancel',b(v)))}</>:!v.reversed&&v.state==='confirmed'&&button('追加作废登记','finance.invoice',()=>saved('/invoices/'+v.id+'/reverse',b(v)))}</>:<fieldset disabled={busy||!can('finance.invoice')}><h3>发票人工登记</h3>{partySelect}{input('发票标识',number,setNumber)}{input('发票类型',kind,setKind)}{input('开票日期',issued,setIssued,'date')}{input('购方名称',buyer,setBuyer)}{input('销方名称',seller,setSeller)}{input('含税金额 CNY',amount,setAmount)}{input('不含税金额（可选，需与税额同时提供）',net,setNet)}{input('税额（不默认税率）',tax,setTax)}<label>红字原发票（正向登记留空）<select value={original} onChange={e=>setOriginal(e.target.value)}><option value="">正向发票</option>{invoices.filter(v=>v.party_id===party&&v.direction===direction&&!v.original_id&&v.state==='confirmed'&&!v.reversed).map(v=><option key={v.id} value={v.id}>{v.number}</option>)}</select></label><h4>分配到业务来源 · 总和须等于票面金额</h4>{sources.filter(s=>s.party_id===party&&s.direction===direction).map(s=><div key={s.id}>{input('开票分配 '+s.number,invoiceLines[s.id]||'',amount=>setInvoiceLines({...invoiceLines,[s.id]:amount}))}</div>)}{input('发票档案登记编号',archive,setArchive)}{input('发票备注',notes,setNotes)}{button('保存发票草稿','finance.invoice',()=>saved('/invoices',{direction,party_id:party,number,kind,issued_on:issued,buyer,seller,amount,net_amount:net||null,tax_amount:tax||null,original_id:original||null,lines:Object.entries(invoiceLines).filter(([,amount])=>amount!=='').map(([source_id,amount])=>({source_id,amount})),archive_ref:archive,notes}))}<p>仅内部登记，不等于税务开票、验真或收款。</p></fieldset>)}
 </article></div>
 <details><summary>往来单位明细与经营对账</summary>{parties.map(p=><article className="nested-card" key={p.direction+p.id}><h4>{p.name} · {p.direction==='receivable'?'客户':'供应商'}</h4>{plans.filter(x=>x.party_id===p.id&&x.direction===p.direction).map(x=><p key={x.id}>{x.node} · 未结 {x.remaining} · {x.due_date||'待释放'}</p>)}{cash.filter(x=>x.party_id===p.id&&x.direction===p.direction).map(x=><p key={x.id}>资金 {x.amount} · 已核销 {x.allocated} · 已退 {x.refunded} · 可用 {x.available} · {x.reversed?'已冲销':state[x.state]}</p>)}</article>)}{button('核对明细守恒','finance.read',async()=>{const v=await get<S['FinanceReconciliation']>('/reconciliation');if(current())setNotice(v.matches?'明细与余额守恒检查一致。':'发现差异：'+v.differences.join('、'));})}</details>
 <details><summary>有商业依据的来源额度调整</summary>{sourceSelect}{input('来源调整金额（有符号）',adjust,setAdjust)}{input('来源调整依据编号',basis,setBasis)}{input('来源调整原因',reason,setReason)}{button('确认来源额度调整','finance.correct',async()=>{if(!src)return;await saved('/source-adjustments',{direction:src.direction,source_id:src.id,expected_version:src.version,amount:adjust,basis_ref:basis,reason,confirmed:true},false);},!src)}<p>追加依据，不覆盖原合同/报价金额；不能把已有债权债务或开票额度降到事实以下。</p></details>
 </section>;
}
