import {FinanceSummary} from './Finance';
import {useEffect,useRef,useState} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket,Member} from './api';
type S=components['schemas'];type Supplier=S['SupplierView'];type Contract=S['ContractView'];type Order=S['OrderView'];type Receipt=S['ReceiptView'];type Stock=S['StockView'];type Item=S['StockItem'];type Movement=S['MovementView'];type Location=S['LocationView'];type Sku=S['Sku'];
const labels:Record<string,string>={wip:'工单在制',assembly_issue:'装配领料',assembly_complete:'装配完工',pending:'待检',qualified:'合格',quarantine:'隔离',draft:'草稿',confirmed:'已确认',active:'已生效',posted:'已过账',unknown:'未知',provisional:'暂估',own:'自有',customer:'客户代管',receipt:'采购收货',opening:'期初入库',inspection:'质检',transfer:'移库',reverse:'冲销'};
const errors:Record<string,string>={CONTRACT_CAPACITY_EXCEEDED:'订单数量超过合同剩余额度，请先登记明确的合同增量变更。',RECEIPT_EXCEEDS_REMAINING:'到货超过订单净剩余量，请刷新后检查其他收货或取消。',SERIAL_ALREADY_IN_STOCK:'该 SN 已在库存中，不能重复入库。',SERIALS_REQUIRED_UNIQUE:'请提供与数量一致、合法且不重复的 SN。',INVENTORY_CONSTRAINT:'编号、SN 或关联约束冲突，请检查输入。',MOVEMENT_DEPENDENCY:'存在尚未冲销的后续移动，请先按逆序处理。',INSUFFICIENT_STOCK:'源库位数量不足。',VERSION_CONFLICT:'版本已变化，当前编辑未保存。请刷新并核对。',OPENING_CLOSED:'普通期初导入已关闭。',OPENING_BOUNDARY:'期初尚未关闭或到货日期不晚于截止日。',IMPORT_ROWS_INVALID:'导入存在错误，整批未入账。',COST_BASIS_REQUIRED:'请填写成本及明确依据。',TRACKING_FROZEN:'已发生库存交易，追踪方式不可更改。',FROZEN_ATTACHMENTS:'单据已冻结，不能改变来源附件。',FILE_TYPE_REJECTED:'附件不是可读的 PDF/JPEG/PNG。',BUSINESS_ALREADY_POSTED:'已有业务过账，不能重新开放普通期初导入。'};
const today=()=>new Date().toISOString().slice(0,10);
export function Inventory({context,members,onContextError,preferredLayer=''}:{preferredLayer?:string;context:ContextTicket;members:Member[];onContextError:(e:unknown)=>void}){
 const [tab,setTab]=useState(preferredLayer?'库存与移动':'采购'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [permissions,setPermissions]=useState<string[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[contracts,setContracts]=useState<Contract[]>([]),[orders,setOrders]=useState<Order[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[locations,setLocations]=useState<Location[]>([]),[stock,setStock]=useState<Stock|null>(null),[moves,setMoves]=useState<Movement[]>([]),[skus,setSkus]=useState<Sku[]>([]);
 const [summary,setSummary]=useState<{pending_quantity:number;quarantine_quantity:number;remaining_quantity:number;amounts?:{tax_basis:string;purchase_amount:string;received_amount:string}[]}|null>(null);
 const [amendLine,setAmendLine]=useState(''),[attachments,setAttachments]=useState<{id:string;name:string;contract_id?:string;receipt_id?:string}[]>([]);
 const [supplier,setSupplier]=useState({name:'',address:'',contact:'',phone:''}),[warehouse,setWarehouse]=useState(''),[locName,setLocName]=useState('');
 const [contract,setContract]=useState<Contract|null>(null),[pc,setPC]=useState({number:'',supplier_id:'',buyer:'',manager_id:'',signing_date:today(),notes:''}),[lines,setLines]=useState([{sku_id:'',quantity:1,unit_price:'',tax_basis:'unconfirmed',due_date:today()}]);
 const [orderContract,setOrderContract]=useState(''),[poNumber,setPONumber]=useState(''),[poLines,setPOLines]=useState<Record<string,number>>({});
 const [receiptOrder,setReceiptOrder]=useState(''),[receiptLoc,setReceiptLoc]=useState(''),[receiptDate,setReceiptDate]=useState(today()),[receiptLines,setReceiptLines]=useState<Record<string,{quantity:number;serials:string;batch:string;cost_status:string;unit_cost:string;cost_basis:string}>>({});
 const [selected,setSelected]=useState<Item|null>(null),[target,setTarget]=useState(''),[targetState,setTargetState]=useState('qualified'),[qty,setQty]=useState(1),[reason,setReason]=useState(''),[search,setSearch]=useState('');
 const [confirmation,setConfirmation]=useState<{text:string;run:()=>void}|null>(null),[csv,setCSV]=useState(''),[preview,setPreview]=useState<{id:string;valid:boolean;errors:{row:number;code:string}[];state?:string}|null>(null),[cutoff,setCutoff]=useState(today()),[policy,setPolicy]=useState<{cutoff:string;opened:boolean;version:number}|null>(null),[recon,setRecon]=useState<{projection_matches:boolean;differences:unknown[]}|null>(null);
 const generation=useRef(0),keys=useRef(new Map<string,string>()),intent=useRef(crypto.randomUUID());
 useEffect(()=>()=>{generation.current++;},[context.context_id]);
 const can=(p:string)=>permissions.includes(p);
 const get=<T,>(path:string)=>crmRequests.request<T>(context,'/inventory'+path);
 const post=<T,>(path:string,body:unknown)=>{const k=JSON.stringify([intent.current,path,body]);if(!keys.current.has(k))keys.current.set(k,crypto.randomUUID());return crmRequests.request<T>(context,'/inventory'+path,{method:'POST',headers:{'Idempotency-Key':keys.current.get(k)!},body:JSON.stringify(body)});};
 async function run(job:()=>Promise<void>){const n=++generation.current;setBusy(true);setError('');setNotice('');try{await job();}catch(e){if(n===generation.current&&!(e instanceof StaleResponse)){if(isContextError(e)||e instanceof ApiError&&e.status===401)onContextError(e);else setError(e instanceof ApiError?(errors[e.code]??errorMessage(e)):errorMessage(e));}}finally{if(n===generation.current)setBusy(false);}}
 async function load(){const n=generation.current;const meta=await get<{permissions:string[]}>('/context');const [l,o,r,s,m,k]=await Promise.all([get<Location[]>('/locations'),get<Order[]>('/orders'),get<Receipt[]>('/receipts'),get<Stock>('/stock'),get<Movement[]>('/movements'),crmRequests.request<Sku[]>(context,'/catalog/skus')]);const [v,c,p]=await Promise.all([meta.permissions.includes('purchase.read')?get<Supplier[]>('/suppliers'):[],meta.permissions.includes('purchase.read')?get<Contract[]>('/contracts'):[],meta.permissions.includes('inventory.opening')?get<typeof policy>('/opening/configure'):null]);if(n!==generation.current||!crmRequests.isCurrent(context))return;setPermissions(meta.permissions);setLocations(l);setOrders(o);setReceipts(r);setStock(s);if(preferredLayer)setSelected(s.items.find(x=>x.layer_id===preferredLayer)??null);setMoves(m);setSkus(k);setSuppliers(v);setContracts(c);setPolicy(p);const summaryResult=await get<typeof summary>('/summary');if(n===generation.current&&crmRequests.isCurrent(context))setSummary(summaryResult);if(p)setCutoff(p.cutoff);}
 useEffect(()=>{void run(load);},[context.context_id]);
 async function command(path:string,body:unknown,text:string){await post(path,body);await load();if(crmRequests.isCurrent(context)){setNotice(text);if(path.endsWith('/activate')&&contract){const current=await get<Contract>('/contracts/'+contract.id);if(crmRequests.isCurrent(context))openContract(current);}}}
 const input=(label:string,value:string|number,change:(v:string)=>void,type='text')=><label>{label}<input type={type} value={value} onInput={e=>change(e.currentTarget.value)} onChange={e=>change(e.target.value)}/></label>;
 const choose=(label:string,value:string,change:(v:string)=>void,options:{id:string;name:string}[])=><label>{label}<select value={value} onChange={e=>change(e.target.value)}><option value="">请选择</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 const confirm=(text:string,action:()=>Promise<void>)=>setConfirmation({text,run:()=>{setConfirmation(null);void run(action);}});
 const openContract=(x:Contract)=>{intent.current=crypto.randomUUID();setContract(x);setPC({number:x.number,supplier_id:x.supplier_id,buyer:x.buyer,manager_id:x.manager_id,signing_date:x.signing_date,notes:x.notes});setLines(x.lines.map(l=>({sku_id:l.sku_id,quantity:l.quantity,unit_price:l.unit_price??'',tax_basis:l.tax_basis,due_date:l.due_date})));};
 async function saveContract(){const result=await post<Contract>('/contracts'+(contract?'/'+contract.id:''),{...pc,lines,expected_version:contract?.version??0,currency:'CNY'});await load();if(crmRequests.isCurrent(context)){openContract(result);setNotice('采购草稿已保存，尚未生效。');}}
 async function uploadFile(kind:string,id:string,version:number,file:File){void run(async()=>{const bytes=await file.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');const sig=JSON.stringify([kind,id,version,file.name,hash]);if(!keys.current.has(sig))keys.current.set(sig,crypto.randomUUID());await crmRequests.request(context,'/inventory/attachments/'+kind+'/'+id+'?'+new URLSearchParams({name:file.name,expected_version:String(version)}),{method:'POST',headers:{'Content-Type':'application/octet-stream','Idempotency-Key':keys.current.get(sig)!},body:bytes});if(crmRequests.isCurrent(context))setNotice('附件已关联，单据未因此生效或过账。');});}
 async function downloadFile(id:string,name:string){void run(async()=>{const r=await fetch('/api/v1/inventory/attachments/'+id+'/download',{headers:{'X-Expected-Tenant':context.tenant_id,'X-Session-Context':context.context_id},signal:context.signal});if(!r.ok)throw new Error('附件下载失败');const b=await r.blob();if(!crmRequests.isCurrent(context))return;const url=URL.createObjectURL(b);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);});}
 const relatedOrders=orders.filter(o=>o.contract_id===contract?.id);
 const relatedReceipts=receipts.filter(r=>relatedOrders.some(o=>o.id===r.order_id));
 const relatedLayers=new Set(moves.filter(m=>relatedReceipts.some(r=>r.id===m.receipt_id)).flatMap(m=>m.entries.map(e=>e.layer_id)));
 const relatedMoves=moves.filter(m=>m.entries.some(e=>relatedLayers.has(e.layer_id))).sort((a,b)=>a.created_at.localeCompare(b.created_at));
 const options=skus.map(s=>({id:s.id,name:s.number+' · '+s.name}));
 const tabs=['采购','到货与质检','库存与移动','期初导入','基础资料'];
 return <section className="panel contracts-panel inventory-panel"><div className="panel-head"><div><h2>采购与库存</h2><p>采购金额、库存成本和付款分别记录；预留与出库尚未启用。</p></div><button disabled={busy} onClick={()=>void run(load)}>刷新</button></div>
 <nav className="inventory-tabs">{tabs.map(x=><button key={x} aria-pressed={tab===x} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {busy&&<p role="status">正在处理…</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="stats"><button onClick={()=>setTab('采购')}>未到 {summary?.remaining_quantity??'—'} 件</button><button onClick={()=>{setTab('库存与移动');setSearch('');}}>待检 {summary?.pending_quantity??'—'} 件 / 隔离 {summary?.quarantine_quantity??'—'} 件</button></div>{summary?.amounts?.map(x=><p key={x.tax_basis}>CNY · {x.tax_basis==='included'?'含税':x.tax_basis==='excluded'?'不含税':'税口径待确认'} · 采购签约 {x.purchase_amount} / 净到货 {x.received_amount}（不是付款或库存成本）</p>)}
 {confirmation&&<section className="nested-card" role="alertdialog" aria-label="业务确认"><h3>确认业务影响</h3><p>{confirmation.text}</p><button disabled={busy} onClick={confirmation.run}>确认执行</button><button onClick={()=>setConfirmation(null)}>取消</button></section>}
 {tab==='基础资料'&&<><h3>供应商</h3>{suppliers.map(s=><p key={s.id}>{s.name} · {s.contact} · {s.enabled?'启用':'停用'}</p>)}<fieldset disabled={busy||!can('purchase.write')}>{input('供应商名称',supplier.name,v=>setSupplier({...supplier,name:v}))}{input('供应商地址',supplier.address,v=>setSupplier({...supplier,address:v}))}{input('供应商联系人',supplier.contact,v=>setSupplier({...supplier,contact:v}))}{input('供应商联系方式',supplier.phone,v=>setSupplier({...supplier,phone:v}))}<button onClick={()=>void run(()=>command('/suppliers',supplier,'供应商已保存。'))}>新增供应商</button></fieldset>
 <h3>仓库与库位</h3>{locations.map(l=><p key={l.id}>{l.warehouse} / {l.name}</p>)}<fieldset disabled={busy||!can('inventory.configure')}>{input('仓库名称',warehouse,setWarehouse)}{input('库位名称',locName,setLocName)}<button onClick={()=>void run(()=>command('/locations',{warehouse,name:locName},'库位已保存。'))}>新增库位</button></fieldset>
 <h3>商品追踪方式</h3><p>逐件数量为整数；SN 个别计价，批次保留 FIFO 成本层。发生交易后不能切换。</p>{skus.map(s=><div className="nested-card" key={s.id}><span>{s.number} · {s.name}</span><button disabled={busy||!can('inventory.configure')} onClick={()=>void run(()=>command('/tracking/'+s.id,{mode:'sn',unit:'piece',expected_version:0},'SN 追踪已配置。'))}>设为 SN</button><button disabled={busy||!can('inventory.configure')} onClick={()=>void run(()=>command('/tracking/'+s.id,{mode:'batch',unit:'piece',expected_version:0},'批次追踪已配置。'))}>设为批次</button></div>)}</>}
 {tab==='采购'&&<><div className="catalog-layout"><nav>{contracts.map(c=><button key={c.id} onClick={()=>openContract(c)}>{c.number} · {labels[c.state]}</button>)}<button onClick={()=>{intent.current=crypto.randomUUID();setContract(null);setPC({number:'',supplier_id:'',buyer:'',manager_id:'',signing_date:today(),notes:''});setLines([{sku_id:'',quantity:1,unit_price:'',tax_basis:'unconfirmed',due_date:today()}]);}}>新建采购合同</button></nav><article>{contract?.state==='active'&&<FinanceSummary context={context} direction="payable" sourceId={contract.id}/>}<h3>采购合同 {contract?.number} · {labels[contract?.state??'draft']}</h3><fieldset disabled={busy||!can('purchase.write')||contract?.state==='active'}>{input('采购合同编号',pc.number,v=>setPC({...pc,number:v}))}{choose('供应商',pc.supplier_id,v=>setPC({...pc,supplier_id:v}),suppliers)}{input('我方主体',pc.buyer,v=>setPC({...pc,buyer:v}))}{choose('采购负责人',pc.manager_id,v=>setPC({...pc,manager_id:v}),members)}{input('签订日期',pc.signing_date,v=>setPC({...pc,signing_date:v}),'date')}{input('采购备注',pc.notes,v=>setPC({...pc,notes:v}))}
 {lines.map((l,n)=><div className="nested-card" key={n}>{choose('商品 '+(n+1),l.sku_id,v=>setLines(lines.map((x,i)=>i===n?{...x,sku_id:v}:x)),options)}{input('合同数量 '+(n+1),l.quantity,v=>setLines(lines.map((x,i)=>i===n?{...x,quantity:Number(v)}:x)),'number')}{input('采购单价 '+(n+1),l.unit_price,v=>setLines(lines.map((x,i)=>i===n?{...x,unit_price:v}:x)))}{choose('税口径 '+(n+1),l.tax_basis,v=>setLines(lines.map((x,i)=>i===n?{...x,tax_basis:v}:x)),[{id:'included',name:'含税'},{id:'excluded',name:'不含税'},{id:'unconfirmed',name:'待确认'}])}{input('交期 '+(n+1),l.due_date,v=>setLines(lines.map((x,i)=>i===n?{...x,due_date:v}:x)),'date')}<button onClick={()=>setLines(lines.filter((_,i)=>i!==n))}>移除商业行 {n+1}</button></div>)}<button onClick={()=>setLines([...lines,{sku_id:'',quantity:1,unit_price:'',tax_basis:'unconfirmed',due_date:today()}])}>添加商业行</button><button onClick={()=>void run(saveContract)}>保存采购合同</button></fieldset>
 {contract?.state==='draft'&&<button disabled={busy||!can('purchase.activate')} onClick={()=>confirm('冻结当前采购合同双方及商业行；此操作不代表付款。',()=>command('/contracts/'+contract.id+'/activate',{expected_version:contract.version,confirmed:true},'采购合同已生效。'))}>确认生效</button>}{contract?.state==='active'&&<section className="nested-card"><p>商业快照已冻结；下列增量独立留痕，不覆盖原合同。</p>{choose('追加商业行',amendLine,setAmendLine,contract.lines.map(x=>({id:x.id,name:skus.find(s=>s.id===x.sku_id)?.number??x.sku_id})))}{input('明确追加数量',qty,v=>setQty(Number(v)),'number')}{input('增量变更依据',reason,setReason)}<button disabled={busy||!can('purchase.activate')} onClick={()=>confirm(`明确增加 ${qty} 件合同额度，原单价和历史快照保持不变。`,()=>command('/contracts/'+contract.id+'/amend',{line_id:amendLine,extra_quantity:qty,reason,confirmed:true,expected_version:contract.version},'增量变更已记录，请重新打开合同查看新版本。'))}>登记合同增量</button></section>}
 {contract&&<section className="nested-card"><h4>来源附件</h4><label>采购合同附件<input type="file" accept=".pdf,.png,.jpg,.jpeg" disabled={busy||contract.state!=='draft'} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadFile('contract',contract.id,contract.version,f);}}/></label><button onClick={()=>void run(async()=>{const f=await get<typeof attachments>('/attachments');if(crmRequests.isCurrent(context))setAttachments(f);})}>查询附件</button>{attachments.filter(x=>x.contract_id===contract.id).map(x=><button key={x.id} onClick={()=>void downloadFile(x.id,x.name)}>{x.name} · 下载</button>)}</section>}
 {contract&&<section className="nested-card"><h4>采购来源时间线</h4><p>{contract.signing_date} · 合同 {contract.number} · {labels[contract.state]}</p>{relatedOrders.map(o=><p key={o.id}>订单 {o.number} · {labels[o.state]}</p>)}{relatedReceipts.map(r=><p key={r.id}>{r.received_on} · 收货 {r.id} · {labels[r.state]} · {r.lines.reduce((n,l)=>n+l.quantity,0)} 件</p>)}{relatedMoves.map(m=><p key={m.id}>{m.created_at} · {labels[m.kind]} · {m.reason} · {m.id}{m.reverse_of&&<> · 逆向来源 {m.reverse_of}</>}</p>)}{!relatedOrders.length&&<p>尚无关联采购订单。</p>}</section>}
 </article></div><h3>采购订单</h3><fieldset disabled={busy||!can('purchase.write')}>{choose('来源采购合同',orderContract,v=>{setOrderContract(v);setPOLines({});},contracts.filter(x=>x.state==='active').map(x=>({id:x.id,name:x.number})))}{input('采购订单编号',poNumber,setPONumber)}{contracts.find(c=>c.id===orderContract)?.lines.map(l=><div key={l.id}>{input('订购 '+(skus.find(s=>s.id===l.sku_id)?.number??l.sku_id),poLines[l.id]??0,v=>setPOLines({...poLines,[l.id]:Number(v)}),'number')}</div>)}<button onClick={()=>void run(()=>command('/orders',{number:poNumber,contract_id:orderContract,lines:Object.entries(poLines).filter(([,q])=>q>0).map(([id,quantity])=>({contract_line_id:id,quantity}))},'采购订单草稿已保存。'))}>创建采购订单</button></fieldset>{orders.map(o=><div className="nested-card" key={o.id}><h3>{o.number} · {labels[o.state]}</h3>{o.lines.map(l=><p key={l.id}>{skus.find(s=>s.id===l.sku_id)?.number} · 订购 {l.quantity} / 净到货 {l.received} / 取消 {l.cancelled} / 未到 {l.quantity-l.received-l.cancelled}</p>)}{o.lines.map(l=><div key={l.id}>{input('取消未到数量 '+o.number,qty,v=>setQty(Number(v)),'number')}{input('取消原因 '+o.number,reason,setReason)}<button disabled={busy||!can('purchase.write')} onClick={()=>confirm(`取消 ${qty} 件未到部分；已到货保持。`,()=>command('/orders/'+o.id+'/cancel',{expected_version:o.version,line_id:l.id,quantity:qty,reason,confirmed:true},'未到部分已取消。'))}>取消未到 {o.number}</button></div>)}{o.state==='draft'&&<button disabled={busy||!can('purchase.activate')} onClick={()=>confirm('确认订单商业内容，此后只允许取消未到部分。',()=>command('/orders/'+o.id+'/confirm',{expected_version:o.version,confirmed:true},'订单已确认。'))}>确认订单 {o.number}</button>}</div>)}</>}
 {tab==='到货与质检'&&<><h3>分批收货</h3><fieldset disabled={busy||!can('inventory.receive')}>{choose('收货采购订单',receiptOrder,v=>{setReceiptOrder(v);setReceiptLines({});},orders.filter(x=>x.state==='confirmed').map(x=>({id:x.id,name:x.number})))}{choose('到货库位',receiptLoc,setReceiptLoc,locations.map(x=>({id:x.id,name:x.warehouse+'/'+x.name})))}{input('实际到货日期',receiptDate,setReceiptDate,'date')}{orders.find(o=>o.id===receiptOrder)?.lines.map(l=>{const v=receiptLines[l.id]??{quantity:0,serials:'',batch:'',cost_status:'unknown',unit_cost:'',cost_basis:''};const change=(x:Partial<typeof v>)=>setReceiptLines({...receiptLines,[l.id]:{...v,...x}});return <div className="nested-card" key={l.id}><h4>{skus.find(s=>s.id===l.sku_id)?.number} · 未到 {l.quantity-l.received-l.cancelled}</h4>{input('本批数量',v.quantity,x=>change({quantity:Number(x)}),'number')}<label>SN（每行一个；批次件留空）<textarea value={v.serials} onChange={e=>change({serials:e.target.value})}/></label>{input('批号',v.batch,x=>change({batch:x}))}{can('inventory.cost')&&<>{choose('成本状态',v.cost_status,x=>change({cost_status:x}),[{id:'unknown',name:'未知'},{id:'provisional',name:'暂估'},{id:'confirmed',name:'已确认'}])}{input('单位库存成本',v.unit_cost,x=>change({unit_cost:x}))}{input('成本确认依据',v.cost_basis,x=>change({cost_basis:x}))}<p>不推定税率或可抵扣资格；采购单价不自动当作库存成本。</p></>}</div>;})}<button onClick={()=>void run(()=>command('/receipts',{order_id:receiptOrder,location_id:receiptLoc,received_on:receiptDate,lines:Object.entries(receiptLines).filter(([,l])=>l.quantity>0).map(([order_line_id,l])=>({...l,order_line_id,serials:l.serials.split('\n').filter(x=>x.trim()),unit_cost:l.cost_status==='unknown'?null:l.unit_cost}))},'收货草稿已保存，尚未影响库存。'))}>保存收货草稿</button></fieldset>{receipts.map(r=><div key={r.id} className="nested-card"><p>{orders.find(o=>o.id===r.order_id)?.number} · {r.received_on} · {labels[r.state]} · {r.lines.map(l=>l.quantity).join(' + ')} 件</p>{r.state==='draft'&&<label>送货凭证<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadFile('receipt',r.id,r.version,f);}}/></label>}{r.state==='draft'&&<button disabled={busy||!can('inventory.receive')} onClick={()=>confirm('本批收货过账后进入待检，不计可用；SN 与成本层将留下不可变记录。',()=>command('/receipts/'+r.id+'/post',{expected_version:r.version,confirmed:true},'收货已过账，等待质检。'))}>过账本批收货</button>}</div>)}<button onClick={()=>setTab('库存与移动')}>前往库存质检</button></>}
 {tab==='库存与移动'&&<><h3>库存台账</h3><p>当前可用数量：{stock?.available_quantity??'—'} 件；已扣除有效预留；在制和待检不计可用。{can('inventory.cost')&&<>已知成本 {stock?.known_cost??'—'} CNY；未知成本 {stock?.unknown_quantity??'—'} 件；{stock?.cost_complete?'成本完整':'总成本不完整'}</>}</p>{input('搜索 SN / SKU / 批号',search,setSearch)}<div className="table-scroll"><table><thead><tr><th>商品 / SN或批号</th><th>库位</th><th>状态 / 所有权</th><th>数量</th>{can('inventory.cost')&&<th>单位成本</th>}<th>操作</th></tr></thead><tbody>{stock?.items.filter(x=>[x.serial_raw,x.batch,x.number].some(v=>v?.includes(search))).map(x=><tr key={x.layer_id+x.location_id+x.state}><td>{x.number}<br/>{x.serial_raw||x.batch}</td><td>{x.warehouse}/{x.location_name}</td><td>{labels[x.state]} / {labels[x.ownership]}</td><td>{x.balance}</td>{can('inventory.cost')&&<td>{x.unit_cost??'未知'} · {labels[x.cost_status??'unknown']??'已确认'}</td>}<td><button onClick={()=>{setSelected(x);setTarget(x.location_id);setTargetState(x.state==='pending'?'qualified':x.state);setQty(1);setReason('');}}>质检 / 移库</button></td></tr>)}</tbody></table></div>
 {selected&&<fieldset disabled={busy}><h3>{selected.number} · {selected.serial_raw||selected.batch}</h3><p>源：{selected.location_name} / {labels[selected.state]}，当前 {selected.balance} 件，版本 {selected.version}</p>{choose('目标库位',target,setTarget,locations.map(x=>({id:x.id,name:x.warehouse+'/'+x.name})))}{choose('目标状态',targetState,setTargetState,[{id:'pending',name:'待检'},{id:'qualified',name:'合格'},{id:'quarantine',name:'隔离'}])}{input('移动数量',qty,v=>setQty(Number(v)),'number')}{input('质检结论 / 移动原因',reason,setReason)}<button onClick={()=>confirm(`将 ${qty} 件从 ${selected.location_name}/${labels[selected.state]} 转到所选库位/${labels[targetState]}；数量和成本成对结转。`,async()=>{await command('/transfers',{layer_id:selected.layer_id,source_location_id:selected.location_id,source_state:selected.state,target_location_id:target,target_state:targetState,quantity:qty,reason,confirmed:true,expected_version:selected.version},'移动已过账。');if(crmRequests.isCurrent(context))setSelected(null);})}>确认质检 / 移库</button><button onClick={()=>setSelected(null)}>关闭</button></fieldset>}
 <button disabled={busy} onClick={()=>void run(async()=>{const x=await get<typeof recon>('/reconciliation');if(crmRequests.isCurrent(context))setRecon(x);})}>库存对账</button>{recon&&<p role="status">{recon.projection_matches?'台账与当前余额投影一致':'存在投影差异，请核对移动记录'} · 差异 {recon.differences.length}</p>}
 <h3>移动详情与逆向</h3><p>仅整张错误单据冲销；有后续移动时必须先逆序恢复。不用于采购退货或报损。</p>{moves.map(m=><details key={m.id}><summary>{labels[m.kind]} · {m.effective_on} · {m.reason}</summary><p>记录 {m.id} · 操作人 {m.actor_id} · 请求 {m.request_id}</p>{m.entries.map((e,n)=><p key={n}>{e.layer_id} · {labels[e.state]} · {e.quantity>0?'+':''}{e.quantity}</p>)}{m.kind!=='reverse'&&can('inventory.reverse')&&<><label>冲销原因<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason} onClick={()=>confirm('整张逆向恢复该移动，后续依赖未撤销时会明确拒绝。',()=>command('/movements/'+m.id+'/reverse',{expected_version:1,confirmed:true,reason},'逆向记录已保存，原记录不变。'))}>整张错误冲销</button></>}</details>)}</>}
 {tab==='期初导入'&&<><h3>基本期初导入</h3><p>整批原子提交；CSV 行序变化不产生重复入账。已开展采购过账后不开放普通历史补录。</p><fieldset disabled={busy||!can('inventory.opening')}>{input('期初截止日',cutoff,setCutoff,'date')}{input('开启 / 关闭原因',reason,setReason)}<button onClick={()=>confirm('设置期初边界，后续采购收货日期必须晚于该日。',()=>command('/opening/configure',{cutoff,open:true,reason,expected_version:policy?.version??0},'期初入口已开启。'))}>开启期初导入</button><button disabled={!policy?.opened} onClick={()=>confirm('关闭普通期初导入，此后可开始采购过账。',()=>command('/opening/configure',{cutoff,open:false,reason,expected_version:policy?.version??0},'期初入口已关闭。'))}>关闭期初导入</button><p>当前：{policy?.opened?'开放':'关闭或未配置'}</p><button onClick={()=>void run(async()=>{const r=await fetch('/api/v1/inventory/opening/template',{headers:{'X-Expected-Tenant':context.tenant_id,'X-Session-Context':context.context_id},signal:context.signal});if(!r.ok)throw new Error('模板下载失败');const text=await r.text();if(!crmRequests.isCurrent(context))return;const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='opening-template.csv';a.click();URL.revokeObjectURL(url);})}>下载 CSV 模板</button><label>上传期初 CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const text=await f.text();if(crmRequests.isCurrent(context)){setCSV(text);setPreview(null);}});}}/></label><label>CSV 内容预览<textarea rows={8} value={csv} onChange={e=>{setCSV(e.target.value);setPreview(null);}}/></label><button disabled={!policy?.opened} onClick={()=>void run(async()=>{const p=await post<typeof preview>('/opening/preview',{csv});if(crmRequests.isCurrent(context))setPreview(p);})}>预校验 CSV</button>{preview&&<><p role="status">{preview.valid?'预校验通过，尚未产生库存':'预校验失败，未产生库存'}</p>{preview.errors.map((x,n)=><p className="error" key={n}>第 {x.row} 行：{x.code}</p>)}<button disabled={!preview.valid} onClick={()=>confirm('确认按预览内容整批入账；任何错误都回滚整个批次。',()=>command('/opening/'+preview.id+'/commit',{expected_version:1,confirmed:true},'期初导入已提交，可到库存查询。'))}>确认提交期初</button></>}</fieldset></>}
 </section>;
}
