import {useEffect,useRef,useState} from 'react';
import type {components} from '../../../packages/api-client/schema';
import {crmRequests,StaleResponse,ApiError,isContextError,errorMessage} from './api';
import type {ContextTicket} from './api';
import {ServerDiagram,quoteCategories} from './ServerDiagram';
import type {PartCategory} from './ServerDiagram';
import './quote.css';
import {DraftSubmission} from './Publication';
type S=components['schemas'];type Input=S['QuoteInput'];type Detail=S['QuoteDetail'];type Calc=S['Calculation'];type SKU=S['Sku'];type BOM=S['Bom'];
const blank:Input={name:'配置报价草稿',customer_id:'',project_id:'',bom_id:'',quantity:1,scope:'retail',tax_included:true,additions:[],excluded_sku_ids:[],discount_id:null};
const errors:Record<string,string>={DISCOUNT_UNAVAILABLE:'折扣未配置、停用或不在适用期间，请核对企业政策。',INVALID_PROJECT:'项目不属于所选客户，请重新选择。',VERSION_CONFLICT:'草稿已被其他窗口修改。请重新打开最新版本后编辑。',DUPLICATE_COMPONENT:'该 SKU 已在配置中，请先移除原技术行再替换。',PUBLISHED_BOM_REQUIRED:'请选择已发布的包件或 BOM 版本。',AMOUNT_OUT_OF_RANGE:'金额超出支持范围，请减少数量。',IDEMPOTENCY_CONFLICT:'本次保存内容已改变，请重试当前内容。',INVALID_EXCLUSION:'移除的部件不属于该 BOM，请重新选择。'};
export function QuoteStudio({context,canWrite,canDiscount,disabled,onContextError,publicationEnabled=false}:{publicationEnabled?:boolean;context:ContextTicket;canWrite:boolean;canDiscount:boolean;disabled:boolean;onContextError:(e:unknown)=>void}){
 const [skus,setSkus]=useState<SKU[]>([]),[boms,setBoms]=useState<BOM[]>([]),[customers,setCustomers]=useState<S['CustomerSummary'][]>([]),[customer,setCustomer]=useState<S['CustomerDetail']|null>(null),[quotes,setQuotes]=useState<S['QuoteSummary'][]>([]);
 const [form,setForm]=useState<Input>(blank),[saved,setSaved]=useState<Detail|null>(null),[calculation,setCalculation]=useState<Calc|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[calculating,setCalculating]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[code,setCode]=useState('');
 const generation=useRef(0),alert=useRef<HTMLDivElement>(null),key=useRef({signature:'',value:crypto.randomUUID()});
 const locked=busy||disabled;
 useEffect(()=>{const stale=()=>{setCalculation(null);setNotice('窗口重新激活：价格可能变化，请重新计价；未保存配置仍保留。');};const visible=()=>{if(document.visibilityState==='visible')stale();};window.addEventListener('focus',stale);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('focus',stale);document.removeEventListener('visibilitychange',visible);};},[]);
 function fail(e:unknown){if(e instanceof StaleResponse)return;if(isContextError(e)||e instanceof ApiError&&e.status===401){onContextError(e);return;}setError(e instanceof ApiError?(errors[e.code]??(e.status===403?'当前身份无权限执行此操作。':e.status===422?'请核对客户、项目、版本、数量及输入格式。':e.message)):errorMessage(e));}
 useEffect(()=>{if(error)alert.current?.focus();},[error]);
 useEffect(()=>{const n=++generation.current;setBusy(true);Promise.all([crmRequests.request<SKU[]>(context,'/catalog/skus'),crmRequests.request<BOM[]>(context,'/catalog/boms'),crmRequests.request<S['CustomerPage']>(context,'/crm/customers?page_size=100'),crmRequests.request<S['QuoteSummary'][]>(context,'/quotes')]).then(([s,b,c,q])=>{if(n===generation.current){setSkus(s);setBoms(b.filter(x=>x.state==='published'));setCustomers(c.items);setQuotes(q);}}).catch(e=>{if(n===generation.current)fail(e);}).finally(()=>{if(n===generation.current)setBusy(false);});return()=>{generation.current++;};},[context.context_id]);
 // A new/opened local draft starts a new command lifecycle; failed saves keep it.
 function resetSaveCommand(){key.current={signature:'',value:crypto.randomUUID()};}
 function change(next:Input){setForm(next);setDirty(true);setCalculation(null);setError('');setNotice('配置已修改，旧金额已失效，请重新计价。');}
 async function chooseCustomer(id:string){const n=++generation.current;change({...form,customer_id:id,project_id:''});setCustomer(null);setBusy(true);try{const c=await crmRequests.request<S['CustomerDetail']>(context,'/crm/customers/'+id);if(n===generation.current)setCustomer(c);}catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}}
 async function open(id:string){const n=++generation.current;setBusy(true);setError('');try{const d=await crmRequests.request<Detail>(context,'/quotes/'+id);const c=await crmRequests.request<S['CustomerDetail']>(context,'/crm/customers/'+d.config.customer_id);if(n!==generation.current)return;resetSaveCommand();setSaved(d);setForm(d.config);setCustomer(c);setCalculation(d.current_calculation);setDirty(false);setCode('');setNotice(d.needs_reprice?'价格或商品状态已变化：以下为当前重新计价，旧保存金额仅供对照。请检查后保存。':'已重新打开保存的草稿。');}catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}}
 async function calculate(next=form){const n=generation.current;setBusy(true);setCalculating(true);setCalculation(null);setError('');setNotice('正在重新计价…');try{const value=await crmRequests.request<Calc>(context,'/quotes/evaluate',{method:'POST',body:JSON.stringify(next)});if(n===generation.current){setCalculation(value);setNotice('已完成后端试算，尚未保存；不预占或核销折扣。');}}catch(e){if(n===generation.current){setNotice('重新计价失败，待重新计价；未保存配置仍保留。');fail(e);}}finally{if(n===generation.current){setBusy(false);setCalculating(false);}}}
 async function apply(){const n=generation.current;setBusy(true);setError('');try{const discount=await crmRequests.request<S['DiscountRef']>(context,'/quotes/discount',{method:'POST',body:JSON.stringify({code})});if(n!==generation.current)return;const next={...form,discount_id:discount.id};change(next);setCode('');await calculate(next);}catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}}
 async function save(){const n=generation.current;setBusy(true);setError('');const payload=saved?{...form,expected_version:saved.version}:form;const signature=JSON.stringify({operation:saved?'update:'+saved.id:'create',payload});if(key.current.signature!==signature)key.current={signature,value:crypto.randomUUID()};try{const d=await crmRequests.request<Detail>(context,'/quotes'+(saved?'/'+saved.id:''),{method:saved?'PUT':'POST',headers:{'Idempotency-Key':key.current.value},body:JSON.stringify(payload)});const q=await crmRequests.request<S['QuoteSummary'][]>(context,'/quotes');if(n!==generation.current)return;setSaved(d);setForm(d.config);setCalculation(d.current_calculation);setQuotes(q);setDirty(false);setNotice('草稿已保存，可刷新重新打开；没有正式发布或折扣核销。');}catch(e){if(n===generation.current)fail(e);}finally{if(n===generation.current)setBusy(false);}}
 const base=boms.find(b=>b.id===form.bom_id);const included=(base?.snapshot.technical_lines??[]).filter(x=>!form.excluded_sku_ids?.includes(x.sku.id));
 const counts:Record<string,number>={};const invalid=new Set<string>();
 for(const x of [...(base?[{sku:skus.find(s=>s.id===base.subject_sku_id)??base.snapshot.subject,quantity:1}]:[]),...included.map(x=>({sku:skus.find(s=>s.id===x.sku.id)??x.sku,quantity:x.quantity})),...(form.additions??[]).map(x=>({sku:skus.find(s=>s.id===x.sku_id),quantity:x.quantity}))]){if(x.sku){counts[x.sku.category]=(counts[x.sku.category]??0)+x.quantity;if(!x.sku.enabled)invalid.add(x.sku.category);}}
 for(const check of calculation?.checks??[]){if(check.status==='BLOCK'||check.status==='WARN'){const category=({socket:'cpu',memory_generation:'memory',POWER:'psu'} as Record<string,string>)[check.code];if(category)invalid.add(category);}}
 function focusCategory(category:PartCategory){document.getElementById('quote-field-'+category)?.focus();}
 return <div className="quote-studio"><div className="quote-toolbar"><div><h2>配置报价草稿</h2><p>草稿、试算与正式报价分开；已保存后可提交审批；发布使用独立冻结版本。</p></div><button disabled={locked} onClick={()=>{generation.current++;resetSaveCommand();setForm(blank);setSaved(null);setCustomer(null);setCalculation(null);setDirty(false);setNotice('新草稿');setError('');setCode('');}}>新建草稿</button><label>已保存草稿<select aria-label="已保存草稿" disabled={locked} value={saved?.id??''} onChange={e=>void open(e.target.value)}><option value="" disabled>选择重新打开（最多100项）</option>{quotes.map(q=><option key={q.id} value={q.id}>{q.name} · v{q.version}</option>)}</select></label></div>
 {error&&<div role="alert" tabIndex={-1} ref={alert} className="error">{error}</div>}{notice&&<p role="status">{notice}</p>}
 {!canWrite&&<p>只读身份：可打开已有草稿，不可试算或保存。</p>}
 <div className="quote-context"><label>草稿名称<input disabled={locked||!canWrite} value={form.name} onChange={e=>change({...form,name:e.target.value})}/></label><label>客户<select disabled={locked||!canWrite} value={form.customer_id} onChange={e=>void chooseCustomer(e.target.value)}><option value="">请选择客户（最多100项）</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>项目<select disabled={locked||!canWrite} value={form.project_id} onChange={e=>change({...form,project_id:e.target.value})}><option value="">请选择项目</option>{customer?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
 <div className="quote-workspace"><ServerDiagram counts={counts} invalid={invalid} onSelect={focusCategory}/><section className="config"><div className="section-title"><h2>配置清单</h2><span>{dirty?'未保存编辑':saved?'已保存草稿':'新草稿'}</span></div>
 <fieldset disabled={locked||!canWrite}><div className="component"><label>准系统 / BOM 版本<select id="quote-field-host" value={form.bom_id} onChange={e=>change({...form,bom_id:e.target.value,excluded_sku_ids:[]})}><option value="">请选择已发布版本</option>{boms.map(b=><option key={b.id} value={b.id}>{b.name} · v{b.revision}</option>)}</select></label><label>整机数量<input type="number" min="1" max="10000" value={form.quantity} onChange={e=>change({...form,quantity:Number(e.target.value)})}/></label></div>
 {base&&<div className="component"><h3>版本包含的技术部件</h3>{base.snapshot.technical_lines.map((l,n)=><label className="included-row" key={n}><input type="checkbox" checked={!form.excluded_sku_ids?.includes(l.sku.id)} onChange={e=>change({...form,excluded_sku_ids:e.target.checked?form.excluded_sku_ids?.filter(id=>id!==l.sku.id):[...new Set([...(form.excluded_sku_ids??[]),l.sku.id])]})}/>{l.sku.name} ×{l.quantity} · {l.charge_mode==='included'?'含于包件，不另收费':'另计价'}</label>)}<small>移除包含件不会降低根包件基价；替换件在下方新增计价。</small></div>}
 {Object.entries(quoteCategories).filter(([k])=>k!=='host').map(([category,label])=>{const chosen=(form.additions??[]).find(x=>skus.find(s=>s.id===x.sku_id)?.category===category);const other=(form.additions??[]).filter(x=>skus.find(s=>s.id===x.sku_id)?.category!==category);return <div className="component" key={category}><label>{label}追加型号<select id={'quote-field-'+category} value={chosen?.sku_id??''} onChange={e=>change({...form,additions:e.target.value?[...other,{sku_id:e.target.value,quantity:chosen?.quantity??1}]:other})}><option value="">不追加 / 使用包含件</option>{skus.filter(s=>s.category===category).map(s=><option key={s.id} value={s.id}>{s.name}{!s.enabled?'（停用）':''}</option>)}</select></label>{chosen&&<label>{label}追加数量<input type="number" min="1" max="10000" value={chosen.quantity} onChange={e=>change({...form,additions:[...other,{...chosen,quantity:Number(e.target.value)}]})}/></label>}</div>;})}
 <div className="component"><label>价格范围<input value={form.scope} onChange={e=>change({...form,scope:e.target.value})}/></label><label>价格口径<select value={String(form.tax_included)} onChange={e=>change({...form,tax_included:e.target.value==='true'})}><option value="true">CNY 含税</option><option value="false">CNY 不含税</option></select></label><small>按价格表原口径，不自行换算税率或运费。</small></div></fieldset></section>
 <aside className="quote"><div className="eyebrow">YOUR QUOTE / DRAFT</div><h2>每一份算力，明码标价。</h2><button disabled={locked||!canWrite} onClick={()=>void calculate()}>重新计价</button>{saved&&<p>历史保存结果 v{saved.version}：{saved.saved_calculation.total??'未完整计价'} CNY<br/>仅为当时结果；当前配置以下方重新计价为准。</p>}
 {!calculation?<p>{calculating?'正在重新计价，旧试算已隐藏。':'待重新计价，旧试算已隐藏。'}</p>:<>{calculation.priced_lines.map(l=><div className="line" key={l.sku_id}><span>{l.name} ×{l.quantity}<small>{l.source.source??'未配置'} · 价格版本 {l.source.revision??'—'}<br/>{l.source.valid_from??'—'} → {l.source.valid_to??'—'}</small></span><b>{l.line_amount??'未知'} CNY</b></div>)}<div className="subtotal"><span>{form.quantity} 台小计</span><b>{calculation.subtotal??'待补全'} CNY</b></div></>}
 <label>折扣码（仅已配置政策）<input disabled={locked||!canDiscount} value={code} autoComplete="off" onChange={e=>setCode(e.target.value)}/></label><div className="coupon-actions"><button disabled={locked||!canDiscount||!code} onClick={()=>void apply()}>应用折扣</button><button disabled={locked||!canWrite||!form.discount_id} onClick={()=>{const next={...form,discount_id:null};change(next);void calculate(next);}}>移除折扣</button></div>
 <p>{calculation?.discount?.name??(form.discount_id?'已选择折扣，待重新计价':'未使用折扣')} · 单码不叠加，不占用或核销次数。</p>
 <div className="total"><span>后端试算 · 非最终报价</span><small>计价时刻：{calculation?.calculated_at??'未计价'}；保存时重新核验。</small><strong>{calculation?.total??(calculating?'计算中':calculation?'待补全':'待重新计价')}{calculation?.total?' CNY':''}</strong><small>优惠 {calculation?.discount_amount??'—'} CNY · {calculation?.amount_complete?'金额可计算':'金额不完整'} · 未获得销售/发布授权</small></div>
 {calculation?.checks.map((c,n)=><p key={n} className={'quote-check check-'+c.status.toLowerCase()}><b>{c.status}</b> · {c.message}</p>)}
 <button className="primary" disabled={locked||!canWrite} onClick={()=>void save()}>保存草稿</button><p className="quote-note">允许保存待补全草稿。提交审批另行检查发布政策；UNKNOWN 不是兼容通过。</p></aside></div>{publicationEnabled&&saved&&<DraftSubmission key={saved.id} context={context} draft={saved} dirty={dirty} disabled={locked||!canWrite} onContextError={onContextError}/>}</div>;
}
