import {useEffect,useRef,useState} from 'react';
import {crmRequests,ApiError,StaleResponse,isContextError,errorMessage} from './api';
import type {ContextTicket} from './api';
import type {components} from '../../../packages/api-client/schema';
type S=components['schemas'];
type Fact={id:string;quantity:number;consumed:number;released:number;unused:number;sku_id:string;serial:string|null;name:string;position:string;removed_at:string|null;service_work_id:string|null;reversed:boolean;destination:string;current_custody:string;disposition:{disposition:string}|null;result:string;action:string;reason:string;created_at:string;receipt_id:string;inspections:Fact[];returns:Fact[];remaining:number;number:string;layer_id:string};
type Work=Omit<S['ServiceWorkView'],'receipts'|'returns'|'tests'|'history'|'reservations'|'issues'|'changes'|'old_parts'|'rmas'|'installations'|'original_configuration'>&{receipts:Fact[];returns:Fact[];tests:Fact[];history:Fact[];reservations:Fact[];issues:Fact[];changes:Fact[];old_parts:Fact[];rmas:Rma[];installations:Fact[];original_configuration:Fact[]};
type Rma=Omit<S['RmaView'],'lines'>&{lines:Fact[]};
type Option={id:string;name:string};type Stock={sku_id:string;number:string;name:string;balance:number;reserved_quantity:number;serial_raw:string|null};
const states:Record<string,string>={new:'新建',working:'处理中',waiting:'等待',verify:'待验证',resolved:'已解决',closed:'已关闭',cancelled:'已取消',draft:'草稿',sent:'在供应商',returned:'全部返回',completed:'处置完成'};
const errors:Record<string,string>={SERVICE_PHYSICAL_DEPENDENCY:'仍有客户设备或未用备件在手，请先归还。',SERVICE_VERIFICATION_REQUIRED:'请完成诊断、有效复测及客户确认。',SERVICE_OLD_PART_RESPONSIBILITY_REQUIRED:'请为旧件登记明确的 RMA 或处置责任。',SERVICE_RETURN_NOT_READY:'请完成复测并确认已解决，再归还客户。',SERVICE_SPARE_UNAVAILABLE:'可用备件不足，或已被其他工单预留。',VERSION_CONFLICT:'记录已变化，请刷新核对后重试。',SERVICE_CONSTRAINT:'编号或对象关系不符合约束，请核对现有记录。',SERVICE_CHANGE_DEPENDENCY:'已有后续事实，不能直接撤销换件。'};
export function Service({context,onContextError,preferredDeviceId=''}:{context:ContextTicket;onContextError:(e:unknown)=>void;preferredDeviceId?:string}){
 const [works,setWorks]=useState<Work[]>([]),[devices,setDevices]=useState<S['ServiceDevice'][]>([]),[permissions,setPermissions]=useState<string[]>([]),[people,setPeople]=useState<Option[]>([]),[locations,setLocations]=useState<Option[]>([]),[suppliers,setSuppliers]=useState<Option[]>([]),[stock,setStock]=useState<Stock[]>([]);
 const [selected,setSelected]=useState(''),[device,setDevice]=useState(preferredDeviceId),[number,setNumber]=useState(''),[fault,setFault]=useState(''),[contact,setContact]=useState(''),[mode,setMode]=useState('return'),[manager,setManager]=useState(''),[planned,setPlanned]=useState(''),[reason,setReason]=useState('');
 const [diagnosis,setDiagnosis]=useState(''),[solution,setSolution]=useState(''),[warranty,setWarranty]=useState('pending'),[basis,setBasis]=useState(''),[location,setLocation]=useState(''),[appearance,setAppearance]=useState(''),[accessories,setAccessories]=useState(''),[confirmation,setConfirmation]=useState(''),[testName,setTestName]=useState(''),[testResult,setTestResult]=useState('pass'),[report,setReport]=useState('');
 const [sku,setSku]=useState(''),[quantity,setQuantity]=useState('1'),[reservation,setReservation]=useState(''),[issue,setIssue]=useState(''),[installation,setInstallation]=useState(''),[compat,setCompat]=useState(''),[destination,setDestination]=useState('quarantine');
 const [supplier,setSupplier]=useState(''),[rmaNumber,setRmaNumber]=useState(''),[supplierNumber,setSupplierNumber]=useState(''),[parts,setParts]=useState<string[]>([]),[rmaId,setRmaId]=useState(''),[line,setLine]=useState(''),[returnId,setReturnId]=useState(''),[returnKind,setReturnKind]=useState('repair'),[serial,setSerial]=useState(''),[result,setResult]=useState(''),[disposition,setDisposition]=useState('customer'),[unitCost,setUnitCost]=useState('');
 const [amount,setAmount]=useState(''),[feeNumber,setFeeNumber]=useState(''),[feeKind,setFeeKind]=useState('customer_service'),[costKind,setCostKind]=useState('labor'),[hours,setHours]=useState(''),[charges,setCharges]=useState<S['ServiceChargeView'][]>([]);
 const [occurredAt,setOccurredAt]=useState(new Date().toISOString().slice(0,16));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const alive=useRef(true),lock=useRef(false),generation=useRef(0),intent=useRef(crypto.randomUUID()),keys=useRef(new Map<string,string>());
 const current=()=>alive.current&&crmRequests.isCurrent(context),can=(p:string)=>permissions.includes(p),get=<T,>(p:string)=>crmRequests.request<T>(context,'/service'+p);
 function clear(){setWorks([]);setDevices([]);setPermissions([]);setSelected('');setCharges([]);setStock([]);setPeople([]);setLocations([]);setSuppliers([]);setFault('');setContact('');setDiagnosis('');setSolution('');setParts([]);setIssue('');setReservation('');setInstallation('');}
 async function load(){const n=++generation.current;const [ctx,ds,ws,opt]=await Promise.all([get<{permissions:string[];people:Option[]}>('/context'),get<S['ServiceDevice'][]>('/devices'),get<Work[]>('/works'),get<{locations:Option[];suppliers:Option[];stock:Stock[]}>('/options')]);if(!current()||n!==generation.current)return;setPermissions(ctx.permissions);setPeople(ctx.people);setDevices(ds);setWorks(ws);setLocations(opt.locations);setSuppliers(opt.suppliers);setStock(opt.stock);}
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(e instanceof StaleResponse||isContextError(e)||(e instanceof ApiError&&e.status===401)){clear();onContextError(e);}else if(current()){if(e instanceof ApiError&&e.status===403)clear();setError(e instanceof ApiError?(errors[e.code]||errorMessage(e))+' ['+e.code+']':errorMessage(e));}}finally{lock.current=false;if(current())setBusy(false);}}
 useEffect(()=>{alive.current=true;void run(load);const focus=()=>void run(load);window.addEventListener('focus',focus);return()=>{alive.current=false;window.removeEventListener('focus',focus);};},[context.context_id]);
 async function command<T>(path:string,body:unknown){const signature=JSON.stringify([intent.current,path,body]);if(!keys.current.has(signature))keys.current.set(signature,crypto.randomUUID());return crmRequests.request<T>(context,'/service'+path,{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':keys.current.get(signature)!}});}
 async function saved(path:string,body:unknown,isRma=false){const v=await command<{id:string}>(path,body);await load();if(current()){if(isRma)setRmaId(v.id);else setSelected(v.id);setNotice('已登记并刷新历史；没有执行外部发送或收付款。');}}
 const w=works.find(x=>x.id===selected),r=w?.rmas.find(x=>x.id===rmaId),b=(v:{version:number})=>({expected_version:v.version,confirmed:true,reason}),now=()=>new Date(occurredAt+'Z').toISOString();
 const act=(name:string,extra:object={})=>w?saved('/works/'+w.id+'/'+name,{...b(w),...extra}):Promise.resolve();
 const ra=(name:string,extra:object={})=>r?saved('/rmas/'+r.id+'/'+name,{...b(r),...extra},true):Promise.resolve();
 const input=(label:string,value:string,set:(v:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>set(e.target.value)} onInput={e=>set(e.currentTarget.value)}/></label>;
 const select=(label:string,value:string,set:(v:string)=>void,options:{id:string;name:string}[])=><label>{label}<select value={value} onChange={e=>set(e.target.value)}><option value="">请选择</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 const btn=(label:string,p:string,fn:()=>Promise<void>,disabled=false)=><button disabled={busy||!can(p)||disabled} onClick={()=>void run(fn)}>{label}</button>;
 function open(id:string){setSelected(id);setRmaId('');setParts([]);setIssue('');setReservation('');setInstallation('');setCharges([]);setNotice('');setError('');}
 return <section className="panel finance-panel service-panel" aria-label="售后与部件"><div className="toolbar"><div><h2>售后与部件</h2><p>客户设备代管 · 备件履历 · 服务费用</p></div><button disabled={busy} onClick={()=>{intent.current=crypto.randomUUID();open('');}}>新建售后工单</button><button disabled={busy} onClick={()=>void run(load)}>刷新售后</button></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p>正在核对并登记…</p>}
 {input('本次登记时间（UTC）',occurredAt,setOccurredAt,'datetime-local')}
 <div className="metrics">{[['待处理',works.filter(x=>x.state==='new'||x.state==='working').length],['等待',works.filter(x=>x.state==='waiting').length],['待验证',works.filter(x=>x.state==='verify').length],['设备待归还',works.filter(x=>x.custody==='company').length],['供应商逾期',works.flatMap(x=>x.rmas).filter(x=>x.overdue).length]].map(([label,n])=><article className="metric" key={label}>{label}<strong>{n}</strong></article>)}</div>
 <div className="finance-layout"><nav aria-label="售后工单列表"><h3>售后工单</h3>{works.map(x=><button key={x.id} disabled={busy} onClick={()=>open(x.id)}>{x.number} · {x.serial} · {states[x.state]}</button>)}{!works.length&&<p>暂无可见工单。</p>}</nav><article className="customer-detail">
 {!w?<fieldset disabled={busy||!can('service.manage')}><legend>从实际交付设备报修</legend>{select('设备 / SN',device,setDevice,devices.map(d=>({id:d.id,name:d.serial+' · '+d.customer_name+' · '+d.order_number})))}{input('工单编号',number,setNumber)}{input('故障描述',fault,setFault)}{input('报修联系人',contact,setContact)}{select('处理方式',mode,setMode,[{id:'return',name:'返修代管'},{id:'onsite',name:'现场服务'},{id:'remote',name:'远程支持'}])}{select('售后负责人',manager,setManager,people)}{input('计划日期',planned,setPlanned,'date')}{btn('登记售后工单','service.manage',()=>saved('/works',{device_id:device,number,fault,contact,mode,manager_id:manager,planned_on:planned,reported_at:now()}))}<p>报修不等于销售退货，不改变所有权、净交付或收款。</p></fieldset>:<>
 <h3>{w.number} · {w.serial}</h3><p>{w.customer_name} · 订单 {w.order_number} · {states[w.state]} · v{w.version}</p><p>设备所在：{w.custody==='company'?'本方代管，客户所有':'客户处'} · 验证：{w.test_valid?'本次配置人工复测通过':'待有效复测'} · 保修：{w.warranty==='pending'?'待核实':w.warranty==='inside'?'保内':w.warranty==='outside'?'保外':'特批'}</p>{input('本次操作原因',reason,setReason)}
 <section className="nested-card"><h4>诊断与责任</h4><p>已保存：{w.diagnosis||'待诊断'} / {w.solution||'待方案'}</p>{select('诊断负责人',manager,setManager,people)}{input('诊断结果',diagnosis,setDiagnosis)}{input('处理方案',solution,setSolution)}{select('保修判定',warranty,setWarranty,[{id:'pending',name:'待核实'},{id:'inside',name:'保内'},{id:'outside',name:'保外'},{id:'special',name:'特批'}])}{input('判定 / 授权依据',basis,setBasis)}{btn('保存诊断','service.diagnose',()=>act('diagnose',{manager_id:manager,diagnosis,solution,warranty,warranty_basis:basis}))}</section>
 <section className="nested-card"><h4>客户设备交接</h4>{select('交接 / 旧件库位',location,setLocation,locations)}{input('收件外观',appearance,setAppearance)}{input('随件清单',accessories,setAccessories)}{btn('确认返修收件','service.custody',()=>act('receive',{location_id:location,performed_at:now(),appearance,accessories}),w.mode!=='return'||w.custody==='company')}{input('客户确认说明',confirmation,setConfirmation)}{btn('确认归还客户','service.custody',()=>act('return',{receipt_id:w.receipts.find(x=>!w.returns.some(y=>y.receipt_id===x.id))?.id,performed_at:now(),customer_confirmation:confirmation}),w.custody!=='company')}<p>交接只登记代管事实，不计为自有库存或销售退回。</p></section>
 <section className="nested-card"><h4>备件预留与领用</h4>{select('备件 SKU',sku,setSku,[...new Map(stock.map(x=>[x.sku_id,{id:x.sku_id,name:x.number+' · '+x.name}])).values()])}{input('本次数量',quantity,setQuantity,'number')}{btn('预留备件','service.spares',()=>act('reserve',{sku_id:sku,quantity:Number(quantity)}))}{btn('释放未领预留','service.spares',()=>act('release'))}{select('待领预留',reservation,setReservation,w.reservations.filter(x=>x.quantity>x.consumed+x.released).map(x=>({id:x.id,name:'余量 '+(x.quantity-x.consumed-x.released)+' · '+x.id.slice(0,8)})))}{btn('确认领用','service.spares',()=>act('issue',{reservation_id:reservation,quantity:Number(quantity)}))}{select('已领备件',issue,setIssue,w.issues.map(x=>({id:x.id,name:(stock.find(y=>y.sku_id===x.sku_id)?.name||'备件')+' · '+(x.serial||'批次')+' · 未用 '+x.unused})))}{btn('未用备件退回待检','service.spares',()=>act('spare-return',{issue_id:issue,quantity:Number(quantity)}))}<p>领用仍计库存；安装消耗时才计材料费用。已安装件不能按未使用退料。</p></section>
 <section className="nested-card"><h4>设备配置与换件</h4><p>原完工配置（历史）：{w.original_configuration.map(x=>(x.position||x.name)+' × '+x.quantity).join('；')}</p><p>当前安装：{w.installations.filter(x=>!x.removed_at).map(x=>(x.position||x.name)+' '+(x.serial||'批次')+' × '+x.quantity+(x.service_work_id?'（售后安装）':'（原装）')).join('；')}</p>{select('待替换安装位置',installation,setInstallation,w.installations.filter(x=>!x.removed_at).map(x=>({id:x.id,name:x.position+' · '+(x.serial||x.name||'部件')+' × '+x.quantity})))}{input('人工兼容核验依据',compat,setCompat)}{select('拆下旧件去向',destination,setDestination,[{id:'quarantine',name:'客户所有，隔离待处理'},{id:'customer',name:'直接留交客户'},{id:'dispose',name:'隔离待批准处置'}])}{btn('确认人工核验并换件','service.replace',()=>act('replace',{old_installation_id:installation,issue_id:issue,old_destination:destination,location_id:location,compatibility_basis:compat,manual_compatibility_confirmed:true}))}<p>有限校验，资料状态 UNKNOWN；需人工核验依据，不显示自动兼容通过。</p>{w.changes.filter(x=>!x.reversed).map(x=><div key={x.id}>{btn('更正换件 '+x.id.slice(0,8),'service.correct',()=>act('reverse-change',{change_id:x.id}))}</div>)}</section>
 <section className="nested-card"><h4>复测与关闭</h4>{input('人工测试项',testName,setTestName)}{select('测试结果',testResult,setTestResult,[{id:'pass',name:'通过'},{id:'fail',name:'不通过'}])}{input('测试报告档案编号',report,setReport)}{btn('记录人工复测','service.diagnose',()=>act('test',{performed_at:now(),items:[{name:testName,result:testResult}],report_ref:report}))}{['working','waiting','verify','resolved','closed','cancelled'].map(state=><span key={state}>{btn('登记'+states[state],'service.manage',()=>act('state',{state,customer_confirmation:confirmation,reopen:w.state==='closed'}))}</span>)}<p>关闭前须处理设备、未用件和旧件责任；重开需更正权限，历史保留。</p></section>
 <section className="nested-card"><h4>旧件与供应商 RMA</h4>{w.old_parts.filter(x=>!x.reversed).map(x=><label key={x.id}><input type="checkbox" checked={parts.includes(x.id)} onChange={e=>setParts(e.target.checked?[...parts,x.id]:parts.filter(y=>y!==x.id))}/>客户旧件 {x.serial||'批次'} × {x.quantity} · {{customer:'客户持有',quarantine:'隔离',supplier:'供应商处',pending:'返回待检',hold:'继续隔离',scrap:'已处置',own_spare:'转自有备件',mixed:'分批不同处置',restored:'更正恢复'}[x.current_custody]||'待查'}</label>)}{btn('确认所选旧件归还客户','service.rma',async()=>{if(parts.length!==1)throw new Error('请仅选择一条旧件处置');await act('dispose',{old_part_id:parts[0],return_id:null,disposition:'customer',basis});})}{select('维修供应商',supplier,setSupplier,suppliers)}{input('RMA 编号',rmaNumber,setRmaNumber)}{input('供应商受理编号',supplierNumber,setSupplierNumber)}{input('预计返回日期',planned,setPlanned,'date')}{btn('建立旧件 RMA','service.rma',()=>saved('/rmas',{work_id:w.id,expected_version:w.version,number:rmaNumber,supplier_id:supplier,manager_id:manager,supplier_number:supplierNumber,fault:w.fault,expected_on:planned,authorization_basis:basis,old_part_ids:parts},true))}{select('当前 RMA',rmaId,setRmaId,w.rmas.map(x=>({id:x.id,name:x.number+' · '+states[x.state]})))}
 {r&&<><p>{r.number} · 在外 {r.outside_quantity} · 待检 {r.pending_quantity} · {r.overdue?'已逾期':'未逾期'}</p>{btn('确认 RMA 发出','service.rma',()=>ra('send'))}{btn('取消未发 RMA','service.rma',()=>ra('cancel'))}{btn('重开已取消 RMA','service.correct',()=>ra('reopen'),r.state!=='cancelled')}{select('本次返回旧件行',line,setLine,r.lines.map(x=>({id:x.id,name:'数量 '+x.quantity+' · 尚未返回 '+x.remaining})))}{select('返回方式',returnKind,setReturnKind,[{id:'repair',name:'原件修复 / 原 SN'},{id:'replacement',name:'供应商换新 / 新 SN'}])}{input('换新 SN（原件留空）',serial,setSerial)}{input('供应商处理结果',result,setResult)}{btn('确认实际返回待检','service.rma',()=>ra('return',{line_id:line,quantity:Number(quantity),kind:returnKind,serial,location_id:location,performed_at:now(),result}))}{select('待检查返回记录',returnId,setReturnId,r.lines.flatMap(x=>x.returns.filter(y=>!y.inspections.length).map(y=>({id:y.id,name:y.result+' × '+y.quantity}))))}{select('检查后去向',disposition,setDisposition,[{id:'customer',name:'归还客户'},{id:'hold',name:'继续隔离'},{id:'scrap',name:'有依据报废'},{id:'own_spare',name:'有所有权与成本依据转自有备件'}])}{input('所有权 / 处置依据',basis,setBasis)}{can('inventory.cost')&&input('转自有单件成本',unitCost,setUnitCost)}{btn('确认返回检查与处置','service.rma',()=>ra('inspect',{return_id:returnId,passed:testResult==='pass',disposition,ownership_basis:basis,unit_cost:disposition==='own_spare'?unitCost:null}))}{r.lines.flatMap(x=>x.returns.filter(y=>y.inspections.some(z=>(z as unknown as {disposition:string}).disposition==='hold')&&!y.disposition).map(y=><div key={y.id}>隔离件 {y.result}{btn('确认隔离件归还客户','service.rma',()=>act('dispose',{return_id:y.id,old_part_id:null,disposition:'customer',basis}))}{btn('确认隔离件有据报废','service.correct',()=>act('dispose',{return_id:y.id,old_part_id:null,disposition:'scrap',basis}))}</div>))}</>}
 </section>
 <section className="nested-card"><h4>服务费用</h4>{w.material_cost!==undefined&&<p>材料消耗 {w.material_cost} CNY</p>}{w.labor_cost!==undefined&&<p>人工 {w.labor_cost} · 其他 {w.other_cost} CNY</p>}{input('费用金额',amount,setAmount)}{select('费用类别',costKind,setCostKind,[{id:'labor',name:'人工'},{id:'other',name:'其他'}])}{input('人工工时',hours,setHours)}{input('费用 / 收费依据',basis,setBasis)}{btn('登记实际服务费用','service.fee',()=>act('cost',{kind:costKind,person_id:costKind==='labor'?manager:null,hours:costKind==='labor'?hours:null,amount,basis,occurred_on:now().slice(0,10)}))}{select('收费来源类型',feeKind,setFeeKind,[{id:'customer_service',name:'客户服务收费'},{id:'supplier_repair',name:'供应商维修收费'}])}{input('收费确认编号',feeNumber,setFeeNumber)}{btn('确认收费来源','service.fee',async()=>{await command('/works/'+w.id+'/charge',{...b(w),kind:feeKind,rma_id:feeKind==='supplier_repair'?rmaId:null,amount,basis_ref:basis,number:feeNumber});await load();if(current())setNotice('已建立独立收费来源，请到资金工作台显式登记应收/应付。');})}{btn('查询收费来源','finance.read',async()=>{const v=await get<S['ServiceChargeView'][]>('/works/'+w.id+'/charges');if(current())setCharges(v);})}{charges.map(x=><p key={x.id}>{x.number} · {x.kind==='customer_service'?'服务应收来源':'维修应付来源'} · {x.amount} CNY</p>)}<p>费用、收费来源、应收应付及实际核销分别登记，不自动收费。</p></section>
 <details><summary>完整处理历史</summary>{w.history.map(x=><p key={x.id}>{x.created_at} · {x.action} · {x.reason}</p>)}</details>
 </>}
 </article></div></section>;
}

/** Optional enhancement: denial never clears the parent device, contract or order. */
export function ServiceSummary({context,deviceId,onOpen}:{context:ContextTicket;deviceId:string;onOpen:()=>void}){
 const [works,setWorks]=useState<{id:string;number:string;state:string}[]>([]),[error,setError]=useState(''),[allowed,setAllowed]=useState(false);const generation=useRef(0);
 useEffect(()=>{let alive=true;async function load(){const n=++generation.current;setWorks([]);setAllowed(false);setError('');try{const rows=await crmRequests.request<{id:string;number:string;state:string}[]>(context,'/service/works?device_id='+deviceId);if(alive&&n===generation.current&&crmRequests.isCurrent(context)){setWorks(rows);setAllowed(true);}}catch(e){if(alive&&n===generation.current)setError(e instanceof ApiError&&e.status===403?'未授权售后查询；基础设备信息仍可用。':'售后摘要暂不可用，请重新查询。');}}void load();const focus=()=>void load();window.addEventListener('focus',focus);return()=>{alive=false;++generation.current;window.removeEventListener('focus',focus);};},[context.context_id,deviceId]);
 return <section className="nested-card" aria-label="售后摘要"><h4>售后履历</h4>{error&&<p>{error}</p>}{works.map(w=><p key={w.id}>{w.number} · {states[w.state]}</p>)}{allowed&&<button onClick={onOpen}>为此设备建立 / 查询售后工单</button>}</section>;
}
