/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Tenant */
        post: operations["selectTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["crmMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customers */
        get: operations["customers"];
        put?: never;
        /** Create */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer */
        get: operations["customer"];
        /** Update */
        put: operations["updateCustomer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skus */
        get: operations["skus_api_v1_catalog_skus_get"];
        put?: never;
        /** Create Sku */
        post: operations["create_sku_api_v1_catalog_skus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/skus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sku */
        get: operations["sku_api_v1_catalog_skus__id__get"];
        /** Update Sku */
        put: operations["update_sku_api_v1_catalog_skus__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rules */
        get: operations["rules_api_v1_catalog_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_catalog_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/rules/{id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Rule */
        post: operations["revise_rule_api_v1_catalog_rules__id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/boms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Boms */
        get: operations["boms_api_v1_catalog_boms_get"];
        put?: never;
        /** Create Bom */
        post: operations["create_bom_api_v1_catalog_boms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/boms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bom */
        get: operations["bom_api_v1_catalog_boms__id__get"];
        /** Update Bom */
        put: operations["update_bom_api_v1_catalog_boms__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/boms/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Bom */
        post: operations["publish_bom_api_v1_catalog_boms__id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/boms/{id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Bom */
        post: operations["revise_bom_api_v1_catalog_boms__id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/price-books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prices */
        get: operations["prices_api_v1_catalog_price_books_get"];
        put?: never;
        /** Create Price */
        post: operations["create_price_api_v1_catalog_price_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/price-books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price */
        get: operations["price_api_v1_catalog_price_books__id__get"];
        /** Update Price */
        put: operations["update_price_api_v1_catalog_price_books__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/price-books/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Price */
        post: operations["publish_price_api_v1_catalog_price_books__id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/price-books/{id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Price */
        post: operations["revise_price_api_v1_catalog_price_books__id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/current-price/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Price */
        get: operations["current_price_api_v1_catalog_current_price__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing */
        get: operations["listing_api_v1_quotes_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_v1_quotes_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/discount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discount */
        post: operations["discount_api_v1_quotes_discount_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_quotes__id__get"];
        /** Update */
        put: operations["update_api_v1_quotes__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bom */
        Bom: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "package" | "bom";
            /**
             * Subject Sku Id
             * Format: uuid
             */
            subject_sku_id: string;
            /** Rule Id */
            rule_id?: string | null;
            /** Lines */
            lines?: components["schemas"]["BomLine"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Revision */
            revision: number;
            /** Version */
            version: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "published";
            snapshot: components["schemas"]["BomSnapshot"];
        };
        /** BomInput */
        BomInput: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "package" | "bom";
            /**
             * Subject Sku Id
             * Format: uuid
             */
            subject_sku_id: string;
            /** Rule Id */
            rule_id?: string | null;
            /** Lines */
            lines?: components["schemas"]["BomLine"][];
        };
        /** BomLine */
        BomLine: {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Package Version Id */
            package_version_id?: string | null;
            /** Quantity */
            quantity: number;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Charge Mode
             * @enum {string}
             */
            charge_mode: "included" | "separate";
        };
        /** BomSnapshot */
        BomSnapshot: {
            subject: components["schemas"]["Sku"];
            /** Technical Lines */
            technical_lines: components["schemas"]["TechnicalLine"][];
            rule: components["schemas"]["Rule"] | null;
            /** Checks */
            checks: components["schemas"]["Check"][];
        };
        /** BomUpdate */
        BomUpdate: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "package" | "bom";
            /**
             * Subject Sku Id
             * Format: uuid
             */
            subject_sku_id: string;
            /** Rule Id */
            rule_id?: string | null;
            /** Lines */
            lines?: components["schemas"]["BomLine"][];
            /** Expected Version */
            expected_version: number;
        };
        /** Calculation */
        Calculation: {
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Config Hash */
            config_hash: string;
            /** Fingerprint */
            fingerprint: string;
            /** Priced Lines */
            priced_lines: components["schemas"]["PricedLine"][];
            /** Technical Lines */
            technical_lines: components["schemas"]["TechnicalLine"][];
            /** Checks */
            checks: components["schemas"]["Check"][];
            /** Subtotal */
            subtotal: string | null;
            /** Discount Amount */
            discount_amount: string | null;
            /** Total */
            total: string | null;
            /** Amount Complete */
            amount_complete: boolean;
            /**
             * Sale Ready
             * @default false
             */
            sale_ready: boolean;
            /**
             * Currency
             * @default CNY
             */
            currency: string;
            /** Tax Included */
            tax_included: boolean;
            discount?: components["schemas"]["DiscountRef"] | null;
            /** Discount Basis Points */
            discount_basis_points?: number | null;
            /**
             * Policy
             * @default development-v1; no tax conversion; no reservation/redemption
             */
            policy: string;
        };
        /** Check */
        Check: {
            /** Code */
            code: string;
            /**
             * Status
             * @enum {string}
             */
            status: "BLOCK" | "WARN" | "UNKNOWN" | "PASS";
            /** Message */
            message: string;
        };
        /** Contact */
        Contact: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Email
             * @default
             */
            email: string;
        };
        /** CurrentPrice */
        CurrentPrice: {
            /**
             * Status
             * @enum {string}
             */
            status: "KNOWN" | "UNKNOWN" | "EXPIRED" | "NOT_YET_VALID";
            /** Amount */
            amount?: string | null;
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Tax Included */
            tax_included: boolean;
            /** Scope */
            scope: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Book Id */
            book_id?: string | null;
            /** Revision */
            revision?: number | null;
            /** Source */
            source?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** CustomerDetail */
        CustomerDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string;
            /** Name */
            name: string;
            /** Province */
            province: string;
            /** City */
            city: string;
            /** Industry */
            industry: string;
            /** Level */
            level: string;
            /** Stage */
            stage: string;
            /** Contact Count */
            contact_count: number;
            /** Project Count */
            project_count: number;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Notes */
            notes: string;
            /** Contacts */
            contacts: components["schemas"]["Contact"][];
            /** Projects */
            projects: components["schemas"]["Project"][];
            /** Sites */
            sites: components["schemas"]["Site"][];
            /** Responsibilities */
            responsibilities: components["schemas"]["Responsibility"][];
            /** Role History */
            role_history: components["schemas"]["RoleHistory"][];
        };
        /** CustomerInput */
        CustomerInput: {
            /** Number */
            number: string;
            /** Name */
            name: string;
            /**
             * Province
             * @default
             */
            province: string;
            /**
             * City
             * @default
             */
            city: string;
            /**
             * Industry
             * @default
             */
            industry: string;
            /**
             * Level
             * @default 普通客户
             * @enum {string}
             */
            level: "普通客户" | "重点客户" | "战略客户";
            /**
             * Stage
             * @default 跟进中
             * @enum {string}
             */
            stage: "跟进中" | "稳定合作" | "交付推进" | "续保跟进";
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Contacts */
            contacts?: components["schemas"]["Contact"][];
            /** Projects */
            projects?: components["schemas"]["Project"][];
            /** Sites */
            sites?: components["schemas"]["Site"][];
            /** Responsibilities */
            responsibilities?: components["schemas"]["Responsibility"][];
        };
        /** CustomerPage */
        CustomerPage: {
            /** Contact Total */
            contact_total: number;
            /** Project Total */
            project_total: number;
            /** Province Total */
            province_total: number;
            /** Items */
            items: components["schemas"]["CustomerSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** CustomerSummary */
        CustomerSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string;
            /** Name */
            name: string;
            /** Province */
            province: string;
            /** City */
            city: string;
            /** Industry */
            industry: string;
            /** Level */
            level: string;
            /** Stage */
            stage: string;
            /** Contact Count */
            contact_count: number;
            /** Project Count */
            project_count: number;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CustomerUpdate */
        CustomerUpdate: {
            /** Number */
            number: string;
            /** Name */
            name: string;
            /**
             * Province
             * @default
             */
            province: string;
            /**
             * City
             * @default
             */
            city: string;
            /**
             * Industry
             * @default
             */
            industry: string;
            /**
             * Level
             * @default 普通客户
             * @enum {string}
             */
            level: "普通客户" | "重点客户" | "战略客户";
            /**
             * Stage
             * @default 跟进中
             * @enum {string}
             */
            stage: "跟进中" | "稳定合作" | "交付推进" | "续保跟进";
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Contacts */
            contacts?: components["schemas"]["Contact"][];
            /** Projects */
            projects?: components["schemas"]["Project"][];
            /** Sites */
            sites?: components["schemas"]["Site"][];
            /** Responsibilities */
            responsibilities?: components["schemas"]["Responsibility"][];
            /** Expected Version */
            expected_version: number;
        };
        /** DiscountCode */
        DiscountCode: {
            /** Code */
            code: string;
        };
        /** DiscountRef */
        DiscountRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** Error */
        Error: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogoutInfo */
        LogoutInfo: {
            /** Logout Url */
            logout_url: string;
        };
        /** Member */
        Member: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** PriceBook */
        PriceBook: {
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Tax Included */
            tax_included: boolean;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            /** Source */
            source: string;
            /** Lines */
            lines: components["schemas"]["PriceLine-Output"][];
            /** Checks */
            checks?: components["schemas"]["Check"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Revision */
            revision: number;
            /** Version */
            version: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "published";
        };
        /** PriceInput */
        PriceInput: {
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Tax Included */
            tax_included: boolean;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            /** Source */
            source: string;
            /** Lines */
            lines: components["schemas"]["PriceLine-Input"][];
        };
        /** PriceLine */
        "PriceLine-Input": {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Amount */
            amount: number | string;
        };
        /** PriceLine */
        "PriceLine-Output": {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Amount */
            amount: string;
        };
        /** PriceUpdate */
        PriceUpdate: {
            /** Name */
            name: string;
            /** Scope */
            scope: string;
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Tax Included */
            tax_included: boolean;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            /** Source */
            source: string;
            /** Lines */
            lines: components["schemas"]["PriceLine-Input"][];
            /** Expected Version */
            expected_version: number;
        };
        /** PricedLine */
        PricedLine: {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string | null;
            /** Line Amount */
            line_amount: string | null;
            source: components["schemas"]["CurrentPrice"];
        };
        /** Project */
        Project: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** People */
            people?: components["schemas"]["ProjectPerson"][];
        };
        /** ProjectPerson */
        ProjectPerson: {
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "project_lead" | "key_person";
        };
        /** QuoteDetail */
        QuoteDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            config: components["schemas"]["QuoteInput"];
            saved_calculation: components["schemas"]["Calculation"];
            current_calculation: components["schemas"]["Calculation"];
            /** Needs Reprice */
            needs_reprice: boolean;
        };
        /** QuoteInput */
        QuoteInput: {
            /** Name */
            name: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Bom Id
             * Format: uuid
             */
            bom_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /**
             * Scope
             * @default retail
             */
            scope: string;
            /**
             * Tax Included
             * @default true
             */
            tax_included: boolean;
            /** Additions */
            additions?: components["schemas"]["Selection"][];
            /** Excluded Sku Ids */
            excluded_sku_ids?: string[];
            /** Discount Id */
            discount_id?: string | null;
        };
        /** QuoteSummary */
        QuoteSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Version */
            version: number;
        };
        /** QuoteUpdate */
        QuoteUpdate: {
            /** Name */
            name: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Bom Id
             * Format: uuid
             */
            bom_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /**
             * Scope
             * @default retail
             */
            scope: string;
            /**
             * Tax Included
             * @default true
             */
            tax_included: boolean;
            /** Additions */
            additions?: components["schemas"]["Selection"][];
            /** Excluded Sku Ids */
            excluded_sku_ids?: string[];
            /** Discount Id */
            discount_id?: string | null;
            /** Expected Version */
            expected_version: number;
        };
        /** Responsibility */
        Responsibility: {
            /**
             * Role
             * @enum {string}
             */
            role: "sales" | "service";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** RoleHistory */
        RoleHistory: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Party */
            party: string;
            /** Project Id */
            project_id: string | null;
            /** Project Name */
            project_name: string;
            /** Role */
            role: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Person Name */
            person_name: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid Until */
            valid_until: string | null;
            /**
             * Changed By
             * Format: uuid
             */
            changed_by: string;
        };
        /** Rule */
        Rule: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /**
             * Socket
             * @default
             */
            socket: string;
            /**
             * Memory Generation
             * @default
             */
            memory_generation: string;
            /** Power Budget W */
            power_budget_w?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Family Id
             * Format: uuid
             */
            family_id: string;
            /** Revision */
            revision: number;
        };
        /** RuleInput */
        RuleInput: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /**
             * Socket
             * @default
             */
            socket: string;
            /**
             * Memory Generation
             * @default
             */
            memory_generation: string;
            /** Power Budget W */
            power_budget_w?: number | null;
        };
        /** RuleRevision */
        RuleRevision: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /**
             * Socket
             * @default
             */
            socket: string;
            /**
             * Memory Generation
             * @default
             */
            memory_generation: string;
            /** Power Budget W */
            power_budget_w?: number | null;
            /** Expected Version */
            expected_version: number;
        };
        /** SelectedTenant */
        SelectedTenant: {
            /**
             * Context Id
             * Format: uuid
             */
            context_id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** Selection */
        Selection: {
            /**
             * Sku Id
             * Format: uuid
             */
            sku_id: string;
            /** Quantity */
            quantity: number;
        };
        /** SessionInfo */
        SessionInfo: {
            /**
             * Context Id
             * Format: uuid
             */
            context_id: string;
            user: components["schemas"]["UserInfo"];
            /** Tenant Id */
            tenant_id: string | null;
            /** Memberships */
            memberships: components["schemas"]["TenantInfo"][];
        };
        /** Site */
        Site: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
        };
        /** Sku */
        Sku: {
            /** Number */
            number: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "host" | "cpu" | "gpu" | "memory" | "psu" | "system_disk" | "data_disk" | "nic" | "ib";
            /** Manufacturer */
            manufacturer: string;
            /** Brand */
            brand: string;
            /**
             * Brand Kind
             * @enum {string}
             */
            brand_kind: "own" | "third_party";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            specs?: components["schemas"]["Specs"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
        };
        /** SkuInput */
        SkuInput: {
            /** Number */
            number: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "host" | "cpu" | "gpu" | "memory" | "psu" | "system_disk" | "data_disk" | "nic" | "ib";
            /** Manufacturer */
            manufacturer: string;
            /** Brand */
            brand: string;
            /**
             * Brand Kind
             * @enum {string}
             */
            brand_kind: "own" | "third_party";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            specs?: components["schemas"]["Specs"];
        };
        /** SkuUpdate */
        SkuUpdate: {
            /** Number */
            number: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "host" | "cpu" | "gpu" | "memory" | "psu" | "system_disk" | "data_disk" | "nic" | "ib";
            /** Manufacturer */
            manufacturer: string;
            /** Brand */
            brand: string;
            /**
             * Brand Kind
             * @enum {string}
             */
            brand_kind: "own" | "third_party";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            specs?: components["schemas"]["Specs"];
            /** Expected Version */
            expected_version: number;
        };
        /** Specs */
        Specs: {
            /**
             * Socket
             * @default
             */
            socket: string;
            /**
             * Memory Generation
             * @default
             */
            memory_generation: string;
            /** Capacity Gb */
            capacity_gb?: number | null;
            /** Power W */
            power_w?: number | null;
            /** Slot Width */
            slot_width?: number | null;
            /**
             * Interface
             * @default
             */
            interface: string;
            /** Speed Gbps */
            speed_gbps?: number | null;
            /** Cpu Sockets */
            cpu_sockets?: number | null;
        };
        /** Status */
        Status: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "ready";
        };
        /** TechnicalLine */
        TechnicalLine: {
            sku: components["schemas"]["Sku"];
            /** Quantity */
            quantity: number;
            /** Required */
            required: boolean;
            /**
             * Charge Mode
             * @enum {string}
             */
            charge_mode: "included" | "separate";
        };
        /** TenantInfo */
        TenantInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** TenantSelection */
        TenantSelection: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** UserInfo */
        UserInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionCommand */
        VersionCommand: {
            /** Expected Version */
            expected_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: {
                state?: string;
                code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    selectTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectedTenant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutInfo"];
                };
            };
        };
    };
    crmMembers: {
        parameters: {
            query?: never;
            header?: {
                /** @description Page expected tenant, checked against locked server session; not authorization */
                "x-expected-tenant"?: string | null;
                /** @description Opaque context_id from session; changes on every tenant selection */
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customers: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                page_size?: number;
            };
            header?: {
                /** @description Page expected tenant, checked against locked server session; not authorization */
                "x-expected-tenant"?: string | null;
                /** @description Opaque context_id from session; changes on every tenant selection */
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
                /** @description Page expected tenant, checked against locked server session; not authorization */
                "x-expected-tenant"?: string | null;
                /** @description Opaque context_id from session; changes on every tenant selection */
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customer: {
        parameters: {
            query?: never;
            header?: {
                /** @description Page expected tenant, checked against locked server session; not authorization */
                "x-expected-tenant"?: string | null;
                /** @description Opaque context_id from session; changes on every tenant selection */
                "x-session-context"?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
                /** @description Page expected tenant, checked against locked server session; not authorization */
                "x-expected-tenant"?: string | null;
                /** @description Opaque context_id from session; changes on every tenant selection */
                "x-session-context"?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skus_api_v1_catalog_skus_get: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                page_size?: number;
            };
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sku"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sku_api_v1_catalog_skus_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sku"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sku_api_v1_catalog_skus__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sku"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sku_api_v1_catalog_skus__id__put: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sku"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rules_api_v1_catalog_rules_get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_v1_catalog_rules_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_rule_api_v1_catalog_rules__id__revise_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRevision"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    boms_api_v1_catalog_boms_get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bom"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bom_api_v1_catalog_boms_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BomInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bom"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bom_api_v1_catalog_boms__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bom"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bom_api_v1_catalog_boms__id__put: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bom"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_bom_api_v1_catalog_boms__id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bom"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_bom_api_v1_catalog_boms__id__revise_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bom"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prices_api_v1_catalog_price_books_get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBook"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_price_api_v1_catalog_price_books_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_api_v1_catalog_price_books__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_price_api_v1_catalog_price_books__id__put: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_price_api_v1_catalog_price_books__id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_price_api_v1_catalog_price_books__id__revise_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_price_api_v1_catalog_current_price__id__get: {
        parameters: {
            query: {
                scope: string;
                tax_included?: boolean;
                as_of?: string | null;
            };
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPrice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_api_v1_quotes_get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_quotes_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_v1_quotes_evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calculation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discount_api_v1_quotes_discount_post: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscountCode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscountRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_quotes__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_quotes__id__put: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string;
                "x-expected-tenant"?: string | null;
                "x-session-context"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
